// Project      : whfmt.SourceGenerator
// File         : WhfmtIncrementalGenerator.cs
// Description  : Roslyn IIncrementalGenerator that turns .whfmt AdditionalFiles
//                into strongly-typed C# parsers at compile time.
// Architecture : Reads per-file MSBuild metadata from AnalyzerConfigOptions to
//                configure namespace, class name, language, validation and async.
//                Delegates all text generation to WhfmtCodeGen.Generator.ParserGenerator
//                (shared via linked source files — no runtime dependency on whfmt.CodeGen CLI).
//                Generator version is embedded in the file header at generation time.

using System;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using WhfmtCodeGen.Generator;

namespace WhfmtSourceGenerator;

[Generator]
public sealed class WhfmtIncrementalGenerator : IIncrementalGenerator
{
    private static readonly string _version =
        typeof(WhfmtIncrementalGenerator).Assembly.GetName().Version?.ToString(3) ?? "1.0.0";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var whfmtFiles = context.AdditionalTextsProvider
            .Where(static f => f.Path.EndsWith(".whfmt", StringComparison.OrdinalIgnoreCase));

        var combined = whfmtFiles.Combine(context.AnalyzerConfigOptionsProvider);

        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var (file, configProvider) = pair;

            var json = file.GetText(spc.CancellationToken)?.ToString();
            if (string.IsNullOrWhiteSpace(json)) return;

            var opts = configProvider.GetOptions(file);

            opts.TryGetValue("build_metadata.AdditionalFiles.WhfmtNamespace", out var ns);
            opts.TryGetValue("build_metadata.AdditionalFiles.WhfmtClass",     out var cls);
            opts.TryGetValue("build_metadata.AdditionalFiles.WhfmtLanguage",  out var langStr);
            opts.TryGetValue("build_metadata.AdditionalFiles.WhfmtValidate",  out var validateStr);
            opts.TryGetValue("build_metadata.AdditionalFiles.WhfmtAsync",     out var asyncStr);

            var formatName   = System.IO.Path.GetFileNameWithoutExtension(file.Path);
            var resolvedNs   = string.IsNullOrWhiteSpace(ns)  ? "WhfmtGenerated"        : ns!;
            var resolvedCls  = string.IsNullOrWhiteSpace(cls) ? ToPascalCase(formatName) : cls!;
            var lang         = ParseLanguage(langStr, langStr, spc);
            var validate     = !string.Equals(validateStr, "false", StringComparison.OrdinalIgnoreCase);
            var genAsync     = string.Equals(asyncStr,     "true",  StringComparison.OrdinalIgnoreCase);

            try
            {
                var source = ParserGenerator.GenerateFromJson(
                    json!, resolvedNs, resolvedCls, validate, genAsync, lang);

                // Stamp the generator identity into the header (replaces the CLI tool name).
                source = source.Replace(
                    "//   Do not edit — regenerate with: whfmt-codegen generate",
                    $"//   Do not edit — generated by whfmt.SourceGenerator v{_version}");

                // Prefix with "whfmt." to avoid hint-path collisions with user-defined types.
                spc.AddSource($"whfmt.{resolvedCls}.g.cs", SourceText.From(source, Encoding.UTF8));
            }
            catch (Exception ex)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.GenerationFailed,
                    Location.None,
                    file.Path,
                    ex.Message));
            }
        });
    }

    private static OutputLanguage ParseLanguage(string? value, string? rawValue,
        SourceProductionContext spc)
    {
        if (string.IsNullOrWhiteSpace(value)) return OutputLanguage.CSharp;

        return value!.ToLowerInvariant() switch
        {
            "csharp"      => OutputLanguage.CSharp,
            "csharpspan"  => OutputLanguage.CSharpSpan,
            // Unsupported targets: emit WHSG002 and fall back to CSharp.
            _ => UnsupportedLang(rawValue ?? value, spc)
        };
    }

    private static OutputLanguage UnsupportedLang(string lang, SourceProductionContext spc)
    {
        spc.ReportDiagnostic(Diagnostic.Create(
            DiagnosticDescriptors.UnsupportedLanguage,
            Location.None,
            lang));
        return OutputLanguage.CSharp;
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return "Format";
        // "png" → "Png", "my-format" → "My-format" (best effort; users can override via WhfmtClass)
        return char.ToUpperInvariant(name[0]) + name.Substring(1);
    }
}
