//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexEditor.Shell.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DockingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DockingResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexEditor.Shell.Properties.DockingResources", typeof(DockingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color document tabs by.
        /// </summary>
        internal static string Docking_TabSettings_ColorBy {
            get {
                return ResourceManager.GetString("Docking_TabSettings_ColorBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color.
        /// </summary>
        internal static string Docking_TabSettings_ColorColumn {
            get {
                return ResourceManager.GetString("Docking_TabSettings_ColorColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File extension.
        /// </summary>
        internal static string Docking_TabSettings_FileExtension {
            get {
                return ResourceManager.GetString("Docking_TabSettings_FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a hex color: #RRGGBB or #AARRGGBB.
        /// </summary>
        internal static string Docking_TabSettings_HexColorTooltip {
            get {
                return ResourceManager.GetString("Docking_TabSettings_HexColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left.
        /// </summary>
        internal static string Docking_TabSettings_Left {
            get {
                return ResourceManager.GetString("Docking_TabSettings_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No colorization.
        /// </summary>
        internal static string Docking_TabSettings_NoColorization {
            get {
                return ResourceManager.GetString("Docking_TabSettings_NoColorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pattern (regex).
        /// </summary>
        internal static string Docking_TabSettings_PatternColumn {
            get {
                return ResourceManager.GetString("Docking_TabSettings_PatternColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press Delete to remove a selected row..
        /// </summary>
        internal static string Docking_TabSettings_PressDelete {
            get {
                return ResourceManager.GetString("Docking_TabSettings_PressDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project.
        /// </summary>
        internal static string Docking_TabSettings_Project {
            get {
                return ResourceManager.GetString("Docking_TabSettings_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Regex rules — first match wins:.
        /// </summary>
        internal static string Docking_TabSettings_RegexFirstMatch {
            get {
                return ResourceManager.GetString("Docking_TabSettings_RegexFirstMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Regex rules.
        /// </summary>
        internal static string Docking_TabSettings_RegexRules {
            get {
                return ResourceManager.GetString("Docking_TabSettings_RegexRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right.
        /// </summary>
        internal static string Docking_TabSettings_Right {
            get {
                return ResourceManager.GetString("Docking_TabSettings_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show tabs in multiple rows.
        /// </summary>
        internal static string Docking_TabSettings_ShowMultipleRows {
            get {
                return ResourceManager.GetString("Docking_TabSettings_ShowMultipleRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tab rows.
        /// </summary>
        internal static string Docking_TabSettings_TabRows {
            get {
                return ResourceManager.GetString("Docking_TabSettings_TabRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tab strip placement.
        /// </summary>
        internal static string Docking_TabSettings_TabStripPlacement {
            get {
                return ResourceManager.GetString("Docking_TabSettings_TabStripPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document Tab Options.
        /// </summary>
        internal static string Docking_TabSettings_Title {
            get {
                return ResourceManager.GetString("Docking_TabSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle rows with mouse wheel.
        /// </summary>
        internal static string Docking_TabSettings_ToggleWithWheel {
            get {
                return ResourceManager.GetString("Docking_TabSettings_ToggleWithWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top (default).
        /// </summary>
        internal static string Docking_TabSettings_Top {
            get {
                return ResourceManager.GetString("Docking_TabSettings_Top", resourceCulture);
            }
        }
    }
}
