// ==========================================================
// Project: WpfHexEditor.PluginSandbox
// File: Program.cs
// Author: Derek Tremblay (derektremblay666@gmail.com)
// Contributors: Claude Sonnet 4.6
// Created: 2026-03-15
// Description:
//     Entry point for the sandbox child process.
//     Connects to the IDE host via Named Pipe, then runs a message loop
//     dispatching all incoming IPC envelopes to SandboxedPluginRunner.
//
// Usage:
//     WpfHexEditor.PluginSandbox.exe <pipeName>
//
// Architecture Notes:
//     - The IDE is the pipe SERVER; this process is the pipe CLIENT.
//     - pipeName is generated by SandboxProcessManager with a per-plugin Guid suffix.
//     - All unhandled exceptions are caught and pushed as CrashNotification.
//     - Exit codes: 0=clean, 1=bad args, 2=fatal exception.
// ==========================================================

using System.IO.Pipes;
using WpfHexEditor.PluginSandbox;
using WpfHexEditor.SDK.Sandbox;

internal static class Program
{
    private static async Task<int> Main(string[] args)
    {
        if (args.Length < 1)
        {
            Console.Error.WriteLine("Usage: WpfHexEditor.PluginSandbox <pipeName>");
            return 1;
        }

        var pipeName = args[0];
        using var cts = new CancellationTokenSource();
        Console.CancelKeyPress += (_, e) => { e.Cancel = true; cts.Cancel(); };

        IpcChannel? channel = null;
        SandboxedPluginRunner? runner = null;

        try
        {
            // 1. Connect to IDE pipe server
            var pipe = new NamedPipeClientStream(
                ".", pipeName, PipeDirection.InOut, PipeOptions.Asynchronous);
            await pipe.ConnectAsync(cts.Token).ConfigureAwait(false);

            channel = new IpcChannel(pipe);
            var relay = new SandboxMetricsRelay(channel);
            runner = new SandboxedPluginRunner(channel, relay, cts.Token, Console.Error.WriteLine);

            // 2. Message loop
            while (!cts.IsCancellationRequested)
            {
                var envelope = await channel.ReceiveAsync<SandboxEnvelope>(cts.Token)
                    .ConfigureAwait(false);

                if (envelope is null) break; // Pipe closed by host

                var continueLoop = await runner.HandleAsync(envelope).ConfigureAwait(false);
                if (!continueLoop) break;
            }

            return 0;
        }
        catch (OperationCanceledException) { return 0; }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"[Sandbox] Fatal: {ex.Message}");

            if (channel is not null && runner is not null)
                await runner.PushCrash("unknown", ex, "Startup").ConfigureAwait(false);

            return 2;
        }
        finally
        {
            if (runner is not null) await runner.DisposeAsync().ConfigureAwait(false);
            if (channel is not null) await channel.DisposeAsync().ConfigureAwait(false);
        }
    }
}
