//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexEditor.Editor.StructureEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StructureEditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StructureEditorResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexEditor.Editor.StructureEditor.Properties.StructureEditorResources", typeof(StructureEditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ＋ Add Assertion.
        /// </summary>
        internal static string SE_AddAssertion {
            get {
                return ResourceManager.GetString("SE_AddAssertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ＋ Add Checksum.
        /// </summary>
        internal static string SE_AddChecksum {
            get {
                return ResourceManager.GetString("SE_AddChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        internal static string SE_BE_Action {
            get {
                return ResourceManager.GetString("SE_BE_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ＋ Add Bitfield.
        /// </summary>
        internal static string SE_BE_AddBitfield {
            get {
                return ResourceManager.GetString("SE_BE_AddBitfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ＋ Add Color.
        /// </summary>
        internal static string SE_BE_AddColor {
            get {
                return ResourceManager.GetString("SE_BE_AddColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ＋ Add Value Map Entry.
        /// </summary>
        internal static string SE_BE_AddValueMapEntry {
            get {
                return ResourceManager.GetString("SE_BE_AddValueMapEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Array.
        /// </summary>
        internal static string SE_BE_Array {
            get {
                return ResourceManager.GetString("SE_BE_Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bitfields.
        /// </summary>
        internal static string SE_BE_Bitfields {
            get {
                return ResourceManager.GetString("SE_BE_Bitfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bits.
        /// </summary>
        internal static string SE_BE_Bits {
            get {
                return ResourceManager.GetString("SE_BE_Bits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bounds.
        /// </summary>
        internal static string SE_BE_Bounds {
            get {
                return ResourceManager.GetString("SE_BE_Bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Then / Else blocks are shown as children in the tree..
        /// </summary>
        internal static string SE_BE_BranchHint {
            get {
                return ResourceManager.GetString("SE_BE_BranchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Branch Labels.
        /// </summary>
        internal static string SE_BE_BranchLabels {
            get {
                return ResourceManager.GetString("SE_BE_BranchLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse….
        /// </summary>
        internal static string SE_BE_Browse {
            get {
                return ResourceManager.GetString("SE_BE_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Child fields are shown in the block tree..
        /// </summary>
        internal static string SE_BE_ChildFieldsHint {
            get {
                return ResourceManager.GetString("SE_BE_ChildFieldsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Children are shown in the block tree — use the tree to add/reorder child blocks..
        /// </summary>
        internal static string SE_BE_ChildrenInTreeHint {
            get {
                return ResourceManager.GetString("SE_BE_ChildrenInTreeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color Cycle.
        /// </summary>
        internal static string SE_BE_ColorCycle {
            get {
                return ResourceManager.GetString("SE_BE_ColorCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Computation.
        /// </summary>
        internal static string SE_BE_Computation {
            get {
                return ResourceManager.GetString("SE_BE_Computation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Condition.
        /// </summary>
        internal static string SE_BE_Condition {
            get {
                return ResourceManager.GetString("SE_BE_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Count.
        /// </summary>
        internal static string SE_BE_Count {
            get {
                return ResourceManager.GetString("SE_BE_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discriminant.
        /// </summary>
        internal static string SE_BE_Discriminant {
            get {
                return ResourceManager.GetString("SE_BE_Discriminant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entry fields are shown as children in the tree..
        /// </summary>
        internal static string SE_BE_EntryFieldsHint {
            get {
                return ResourceManager.GetString("SE_BE_EntryFieldsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entry Size.
        /// </summary>
        internal static string SE_BE_EntrySize {
            get {
                return ResourceManager.GetString("SE_BE_EntrySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error Message.
        /// </summary>
        internal static string SE_BE_ErrorMessage {
            get {
                return ResourceManager.GetString("SE_BE_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expression.
        /// </summary>
        internal static string SE_BE_Expression {
            get {
                return ResourceManager.GetString("SE_BE_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à False Label.
        /// </summary>
        internal static string SE_BE_FalseLabel {
            get {
                return ResourceManager.GetString("SE_BE_FalseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Group.
        /// </summary>
        internal static string SE_BE_Group {
            get {
                return ResourceManager.GetString("SE_BE_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A group visually labels a set of child fields with a color overlay. It does not consume bytes itself..
        /// </summary>
        internal static string SE_BE_GroupHint {
            get {
                return ResourceManager.GetString("SE_BE_GroupHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index Var.
        /// </summary>
        internal static string SE_BE_IndexVar {
            get {
                return ResourceManager.GetString("SE_BE_IndexVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Label.
        /// </summary>
        internal static string SE_BE_Label {
            get {
                return ResourceManager.GetString("SE_BE_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Length.
        /// </summary>
        internal static string SE_BE_Length {
            get {
                return ResourceManager.GetString("SE_BE_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Body blocks are shown as children in the tree..
        /// </summary>
        internal static string SE_BE_LoopBodyHint {
            get {
                return ResourceManager.GetString("SE_BE_LoopBodyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loop Condition.
        /// </summary>
        internal static string SE_BE_LoopCondition {
            get {
                return ResourceManager.GetString("SE_BE_LoopCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mapped Store As.
        /// </summary>
        internal static string SE_BE_MappedStoreAs {
            get {
                return ResourceManager.GetString("SE_BE_MappedStoreAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max Iterations.
        /// </summary>
        internal static string SE_BE_MaxIterations {
            get {
                return ResourceManager.GetString("SE_BE_MaxIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max Length.
        /// </summary>
        internal static string SE_BE_MaxLength {
            get {
                return ResourceManager.GetString("SE_BE_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max Value.
        /// </summary>
        internal static string SE_BE_MaxValue {
            get {
                return ResourceManager.GetString("SE_BE_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Min Value.
        /// </summary>
        internal static string SE_BE_MinValue {
            get {
                return ResourceManager.GetString("SE_BE_MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string SE_BE_Name {
            get {
                return ResourceManager.GetString("SE_BE_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nested Struct.
        /// </summary>
        internal static string SE_BE_NestedStruct {
            get {
                return ResourceManager.GetString("SE_BE_NestedStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Offset.
        /// </summary>
        internal static string SE_BE_Offset {
            get {
                return ResourceManager.GetString("SE_BE_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Offset Add.
        /// </summary>
        internal static string SE_BE_OffsetAdd {
            get {
                return ResourceManager.GetString("SE_BE_OffsetAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Offset From.
        /// </summary>
        internal static string SE_BE_OffsetFrom {
            get {
                return ResourceManager.GetString("SE_BE_OffsetFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pattern (regex).
        /// </summary>
        internal static string SE_BE_PatternRegex {
            get {
                return ResourceManager.GetString("SE_BE_PatternRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pointer Location.
        /// </summary>
        internal static string SE_BE_PointerLocation {
            get {
                return ResourceManager.GetString("SE_BE_PointerLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position.
        /// </summary>
        internal static string SE_BE_Position {
            get {
                return ResourceManager.GetString("SE_BE_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position &amp; Size.
        /// </summary>
        internal static string SE_BE_PositionSize {
            get {
                return ResourceManager.GetString("SE_BE_PositionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marks a raw byte region with a color overlay. No value is extracted..
        /// </summary>
        internal static string SE_BE_RawDataDescription {
            get {
                return ResourceManager.GetString("SE_BE_RawDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Raw Data Region.
        /// </summary>
        internal static string SE_BE_RawDataRegion {
            get {
                return ResourceManager.GetString("SE_BE_RawDataRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sentinel (Until).
        /// </summary>
        internal static string SE_BE_SentinelUntil {
            get {
                return ResourceManager.GetString("SE_BE_SentinelUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Storage.
        /// </summary>
        internal static string SE_BE_Storage {
            get {
                return ResourceManager.GetString("SE_BE_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Store As.
        /// </summary>
        internal static string SE_BE_StoreAs {
            get {
                return ResourceManager.GetString("SE_BE_StoreAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Struct Ref.
        /// </summary>
        internal static string SE_BE_StructRef {
            get {
                return ResourceManager.GetString("SE_BE_StructRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target &amp; Storage.
        /// </summary>
        internal static string SE_BE_TargetStorage {
            get {
                return ResourceManager.GetString("SE_BE_TargetStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target Var.
        /// </summary>
        internal static string SE_BE_TargetVar {
            get {
                return ResourceManager.GetString("SE_BE_TargetVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable used as the base offset for this array.
        /// </summary>
        internal static string SE_BE_Tip_ArrayBaseVar {
            get {
                return ResourceManager.GetString("SE_BE_Tip_ArrayBaseVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File offset where the array starts — Ctrl+Space for autocomplete.
        /// </summary>
        internal static string SE_BE_Tip_ArrayOffset {
            get {
                return ResourceManager.GetString("SE_BE_Tip_ArrayOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bit range e.g. 7-6 or single bit e.g. 3.
        /// </summary>
        internal static string SE_BE_Tip_BitRange {
            get {
                return ResourceManager.GetString("SE_BE_Tip_BitRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit this block as raw JSON.
        /// </summary>
        internal static string SE_BE_Tip_EditAsJson {
            get {
                return ResourceManager.GetString("SE_BE_Tip_EditAsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of entries — Ctrl+Space for variable suggestions.
        /// </summary>
        internal static string SE_BE_Tip_EntryCount {
            get {
                return ResourceManager.GetString("SE_BE_Tip_EntryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size of each entry in bytes — Ctrl+Space for variable suggestions.
        /// </summary>
        internal static string SE_BE_Tip_EntrySize {
            get {
                return ResourceManager.GetString("SE_BE_Tip_EntrySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Math expression using variables and functions — Ctrl+Space for autocomplete.
        /// </summary>
        internal static string SE_BE_Tip_Expression {
            get {
                return ResourceManager.GetString("SE_BE_Tip_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format name or relative path to the .whfmt file.
        /// </summary>
        internal static string SE_BE_Tip_FormatPath {
            get {
                return ResourceManager.GetString("SE_BE_Tip_FormatPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ctrl+Space for autocomplete — integer, var:name, calc:expr.
        /// </summary>
        internal static string SE_BE_Tip_LengthAuto {
            get {
                return ResourceManager.GetString("SE_BE_Tip_LengthAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fixed integer or var:name — Ctrl+Space for suggestions.
        /// </summary>
        internal static string SE_BE_Tip_LoopCount {
            get {
                return ResourceManager.GetString("SE_BE_Tip_LoopCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable to store the iteration count after loop completes — Ctrl+Space for suggestions.
        /// </summary>
        internal static string SE_BE_Tip_LoopCountStore {
            get {
                return ResourceManager.GetString("SE_BE_Tip_LoopCountStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable that receives the current iteration index (0-based).
        /// </summary>
        internal static string SE_BE_Tip_LoopIdxStore {
            get {
                return ResourceManager.GetString("SE_BE_Tip_LoopIdxStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loop index variable name (e.g. i).
        /// </summary>
        internal static string SE_BE_Tip_LoopIndex {
            get {
                return ResourceManager.GetString("SE_BE_Tip_LoopIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Safety cap — integer.
        /// </summary>
        internal static string SE_BE_Tip_LoopMaxCap {
            get {
                return ResourceManager.GetString("SE_BE_Tip_LoopMaxCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of the variable this metadata block reads.
        /// </summary>
        internal static string SE_BE_Tip_MetaVarName {
            get {
                return ResourceManager.GetString("SE_BE_Tip_MetaVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Additional bytes added to OffsetFrom.
        /// </summary>
        internal static string SE_BE_Tip_OffsetAddBytes {
            get {
                return ResourceManager.GetString("SE_BE_Tip_OffsetAddBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ctrl+Space for autocomplete — integer, var:name, calc:expr, offset:N.
        /// </summary>
        internal static string SE_BE_Tip_OffsetAuto {
            get {
                return ResourceManager.GetString("SE_BE_Tip_OffsetAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable name whose value is the base offset — Ctrl+Space for suggestions.
        /// </summary>
        internal static string SE_BE_Tip_OffsetFromVar {
            get {
                return ResourceManager.GetString("SE_BE_Tip_OffsetFromVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable name used as the base offset.
        /// </summary>
        internal static string SE_BE_Tip_PtrBaseVar {
            get {
                return ResourceManager.GetString("SE_BE_Tip_PtrBaseVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annotation label shown in the hex view.
        /// </summary>
        internal static string SE_BE_Tip_PtrLabel {
            get {
                return ResourceManager.GetString("SE_BE_Tip_PtrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File offset where the pointer value is read — Ctrl+Space for autocomplete.
        /// </summary>
        internal static string SE_BE_Tip_PtrOffset {
            get {
                return ResourceManager.GetString("SE_BE_Tip_PtrOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size of the pointer value in bytes (e.g. 4 for uint32) — or var:name.
        /// </summary>
        internal static string SE_BE_Tip_PtrSize {
            get {
                return ResourceManager.GetString("SE_BE_Tip_PtrSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable to store the raw pointer value.
        /// </summary>
        internal static string SE_BE_Tip_PtrStoreRaw {
            get {
                return ResourceManager.GetString("SE_BE_Tip_PtrStoreRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable that will receive the resolved pointer address.
        /// </summary>
        internal static string SE_BE_Tip_PtrTargetVar {
            get {
                return ResourceManager.GetString("SE_BE_Tip_PtrTargetVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à raw=Display (e.g. 0=Grayscale).
        /// </summary>
        internal static string SE_BE_Tip_RawDisplayMap {
            get {
                return ResourceManager.GetString("SE_BE_Tip_RawDisplayMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable name to store the computed result — Ctrl+Space for suggestions.
        /// </summary>
        internal static string SE_BE_Tip_StoreExpr {
            get {
                return ResourceManager.GetString("SE_BE_Tip_StoreExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable name for ValueMap-translated value — Ctrl+Space for suggestions.
        /// </summary>
        internal static string SE_BE_Tip_StoreMapped {
            get {
                return ResourceManager.GetString("SE_BE_Tip_StoreMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable name to store parsed value — Ctrl+Space for suggestions.
        /// </summary>
        internal static string SE_BE_Tip_StoreParsed {
            get {
                return ResourceManager.GetString("SE_BE_Tip_StoreParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hex pattern or var:name to stop reading at. Replaces Length when set..
        /// </summary>
        internal static string SE_BE_Tip_UntilPattern {
            get {
                return ResourceManager.GetString("SE_BE_Tip_UntilPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Safety cap (bytes) if the Until pattern is never found. 0 = use interpreter default (4096)..
        /// </summary>
        internal static string SE_BE_Tip_UntilSafetyCap {
            get {
                return ResourceManager.GetString("SE_BE_Tip_UntilSafetyCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable that drives the variant selection — Ctrl+Space for suggestions.
        /// </summary>
        internal static string SE_BE_Tip_VariantVar {
            get {
                return ResourceManager.GetString("SE_BE_Tip_VariantVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of the variable to act on — type to see suggestions (Ctrl+Space).
        /// </summary>
        internal static string SE_BE_Tip_VarName {
            get {
                return ResourceManager.GetString("SE_BE_Tip_VarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value to set / amount to add or subtract — supports var:name.
        /// </summary>
        internal static string SE_BE_Tip_VarValue {
            get {
                return ResourceManager.GetString("SE_BE_Tip_VarValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à True Label.
        /// </summary>
        internal static string SE_BE_TrueLabel {
            get {
                return ResourceManager.GetString("SE_BE_TrueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Union.
        /// </summary>
        internal static string SE_BE_Union {
            get {
                return ResourceManager.GetString("SE_BE_Union", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Until.
        /// </summary>
        internal static string SE_BE_Until {
            get {
                return ResourceManager.GetString("SE_BE_Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Until Inclusive (include pattern bytes in field length).
        /// </summary>
        internal static string SE_BE_UntilInclusive {
            get {
                return ResourceManager.GetString("SE_BE_UntilInclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation Rules.
        /// </summary>
        internal static string SE_BE_ValidationRules {
            get {
                return ResourceManager.GetString("SE_BE_ValidationRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value.
        /// </summary>
        internal static string SE_BE_Value {
            get {
                return ResourceManager.GetString("SE_BE_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value Map.
        /// </summary>
        internal static string SE_BE_ValueMap {
            get {
                return ResourceManager.GetString("SE_BE_ValueMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value Type.
        /// </summary>
        internal static string SE_BE_ValueType {
            get {
                return ResourceManager.GetString("SE_BE_ValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable.
        /// </summary>
        internal static string SE_BE_Variable {
            get {
                return ResourceManager.GetString("SE_BE_Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable Name.
        /// </summary>
        internal static string SE_BE_VariableName {
            get {
                return ResourceManager.GetString("SE_BE_VariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variants.
        /// </summary>
        internal static string SE_BE_Variants {
            get {
                return ResourceManager.GetString("SE_BE_Variants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Block Type.
        /// </summary>
        internal static string SE_BlockType {
            get {
                return ResourceManager.GetString("SE_BlockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Offset.
        /// </summary>
        internal static string SE_ColOffset {
            get {
                return ResourceManager.GetString("SE_ColOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Required.
        /// </summary>
        internal static string SE_ColRequired {
            get {
                return ResourceManager.GetString("SE_ColRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Strength.
        /// </summary>
        internal static string SE_ColStrength {
            get {
                return ResourceManager.GetString("SE_ColStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color.
        /// </summary>
        internal static string SE_PropColor {
            get {
                return ResourceManager.GetString("SE_PropColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string SE_PropDescription {
            get {
                return ResourceManager.GetString("SE_PropDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Endianness.
        /// </summary>
        internal static string SE_PropEndianness {
            get {
                return ResourceManager.GetString("SE_PropEndianness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hidden.
        /// </summary>
        internal static string SE_PropHidden {
            get {
                return ResourceManager.GetString("SE_PropHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string SE_PropName {
            get {
                return ResourceManager.GetString("SE_PropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opacity.
        /// </summary>
        internal static string SE_PropOpacity {
            get {
                return ResourceManager.GetString("SE_PropOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string SE_PropType {
            get {
                return ResourceManager.GetString("SE_PropType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show:.
        /// </summary>
        internal static string SE_ShowLabel {
            get {
                return ResourceManager.GetString("SE_ShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hex digits only (e.g. FF, 4D5A).
        /// </summary>
        internal static string SE_TipHexDigitsOnly {
            get {
                return ResourceManager.GetString("SE_TipHexDigitsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Struct name (C struct).
        /// </summary>
        internal static string SE_TipStructName {
            get {
                return ResourceManager.GetString("SE_TipStructName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Template Name.
        /// </summary>
        internal static string SE_TipTemplateName {
            get {
                return ResourceManager.GetString("SE_TipTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code Bottom.
        /// </summary>
        internal static string StrLayout_CodeBottom {
            get {
                return ResourceManager.GetString("StrLayout_CodeBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code Left.
        /// </summary>
        internal static string StrLayout_CodeLeft {
            get {
                return ResourceManager.GetString("StrLayout_CodeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code Right.
        /// </summary>
        internal static string StrLayout_CodeRight {
            get {
                return ResourceManager.GetString("StrLayout_CodeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code Top.
        /// </summary>
        internal static string StrLayout_CodeTop {
            get {
                return ResourceManager.GetString("StrLayout_CodeTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blocks.
        /// </summary>
        internal static string StrSb_BlocksLabel {
            get {
                return ResourceManager.GetString("StrSb_BlocksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format.
        /// </summary>
        internal static string StrSb_FormatLabel {
            get {
                return ResourceManager.GetString("StrSb_FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tab.
        /// </summary>
        internal static string StrSb_TabLabel {
            get {
                return ResourceManager.GetString("StrSb_TabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation.
        /// </summary>
        internal static string StrSb_ValidationLabel {
            get {
                return ResourceManager.GetString("StrSb_ValidationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Block (Ctrl+N).
        /// </summary>
        internal static string StrTb_AddBlock {
            get {
                return ResourceManager.GetString("StrTb_AddBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Layout.
        /// </summary>
        internal static string StrTb_LayoutLabel {
            get {
                return ResourceManager.GetString("StrTb_LayoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code view layout.
        /// </summary>
        internal static string StrTb_LayoutTooltip {
            get {
                return ResourceManager.GetString("StrTb_LayoutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Live Code View.
        /// </summary>
        internal static string StrTb_ToggleLiveCode {
            get {
                return ResourceManager.GetString("StrTb_ToggleLiveCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate (Ctrl+Shift+V).
        /// </summary>
        internal static string StrTb_Validate {
            get {
                return ResourceManager.GetString("StrTb_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Length:.
        /// </summary>
        internal static string StructureEd_ConditionRow_LengthLabel {
            get {
                return ResourceManager.GetString("StructureEd_ConditionRow_LengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string StructureEditor_AddBlockButton {
            get {
                return ResourceManager.GetString("StructureEditor_AddBlockButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string StructureEditor_AddBlockCancel {
            get {
                return ResourceManager.GetString("StructureEditor_AddBlockCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Block.
        /// </summary>
        internal static string StructureEditor_AddBlockTitle {
            get {
                return ResourceManager.GetString("StructureEditor_AddBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add block (Ctrl+N).
        /// </summary>
        internal static string StructureEditor_AddBlockToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_AddBlockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Block....
        /// </summary>
        internal static string StructureEditor_BlocksAddMenuItem {
            get {
                return ResourceManager.GetString("StructureEditor_BlocksAddMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy as JSON.
        /// </summary>
        internal static string StructureEditor_BlocksCopyJsonMenuItem {
            get {
                return ResourceManager.GetString("StructureEditor_BlocksCopyJsonMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duplicate.
        /// </summary>
        internal static string StructureEditor_BlocksDuplicateMenuItem {
            get {
                return ResourceManager.GetString("StructureEditor_BlocksDuplicateMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a block to edit its properties,.
        /// </summary>
        internal static string StructureEditor_BlocksEmptyLine1 {
            get {
                return ResourceManager.GetString("StructureEditor_BlocksEmptyLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à or press Ctrl+N / right-click to add a new block..
        /// </summary>
        internal static string StructureEditor_BlocksEmptyLine2 {
            get {
                return ResourceManager.GetString("StructureEditor_BlocksEmptyLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter blocks by name.
        /// </summary>
        internal static string StructureEditor_BlocksFilterToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_BlocksFilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move Down.
        /// </summary>
        internal static string StructureEditor_BlocksMoveDownMenuItem {
            get {
                return ResourceManager.GetString("StructureEditor_BlocksMoveDownMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move Up.
        /// </summary>
        internal static string StructureEditor_BlocksMoveUpMenuItem {
            get {
                return ResourceManager.GetString("StructureEditor_BlocksMoveUpMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste Block.
        /// </summary>
        internal static string StructureEditor_BlocksPasteMenuItem {
            get {
                return ResourceManager.GetString("StructureEditor_BlocksPasteMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        internal static string StructureEditor_BlocksRemoveMenuItem {
            get {
                return ResourceManager.GetString("StructureEditor_BlocksRemoveMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ＋ Add Pattern.
        /// </summary>
        internal static string StructureEditor_DetectionAddPatternButton {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionAddPatternButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ＋ Add Signature.
        /// </summary>
        internal static string StructureEditor_DetectionAddSigButton {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionAddSigButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Content Patterns (text formats).
        /// </summary>
        internal static string StructureEditor_DetectionContentPatternsLabel {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionContentPatternsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entropy Hint.
        /// </summary>
        internal static string StructureEditor_DetectionEntropyLabel {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionEntropyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hex bytes without spaces, e.g. 89504E47 for PNG.
        /// </summary>
        internal static string StructureEditor_DetectionHexBytesToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionHexBytesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hex Signature.
        /// </summary>
        internal static string StructureEditor_DetectionHexSigLabel {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionHexSigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hex value.
        /// </summary>
        internal static string StructureEditor_DetectionHexValueToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionHexValueToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Label.
        /// </summary>
        internal static string StructureEditor_DetectionLabelToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionLabelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Match Mode.
        /// </summary>
        internal static string StructureEditor_DetectionMatchModeLabel {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionMatchModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max Entropy.
        /// </summary>
        internal static string StructureEditor_DetectionMaxEntropyLabel {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionMaxEntropyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Min Entropy.
        /// </summary>
        internal static string StructureEditor_DetectionMinEntropyLabel {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionMinEntropyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimum Score.
        /// </summary>
        internal static string StructureEditor_DetectionMinScoreLabel {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionMinScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Offset.
        /// </summary>
        internal static string StructureEditor_DetectionOffsetToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionOffsetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Regex pattern.
        /// </summary>
        internal static string StructureEditor_DetectionRegexToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionRegexToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Score Threshold.
        /// </summary>
        internal static string StructureEditor_DetectionScoreThresholdLabel {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionScoreThresholdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signature.
        /// </summary>
        internal static string StructureEditor_DetectionSigLabel {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionSigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à v2.0 Signatures.
        /// </summary>
        internal static string StructureEditor_DetectionV2SigsLabel {
            get {
                return ResourceManager.GetString("StructureEditor_DetectionV2SigsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duplicate block (Ctrl+D).
        /// </summary>
        internal static string StructureEditor_DuplicateBlockToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_DuplicateBlockToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visual editor for .whfmt structure definition files. Edit blocks, types, offsets, lengths and colors in a DataGrid..
        /// </summary>
        internal static string StructureEditor_FactoryDescription {
            get {
                return ResourceManager.GetString("StructureEditor_FactoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Structure Editor.
        /// </summary>
        internal static string StructureEditor_FactoryDisplayName {
            get {
                return ResourceManager.GetString("StructureEditor_FactoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Live Code View.
        /// </summary>
        internal static string StructureEditor_LiveCodeViewToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_LiveCodeViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ＋ Add Extension.
        /// </summary>
        internal static string StructureEditor_MetaAddExtensionButton {
            get {
                return ResourceManager.GetString("StructureEditor_MetaAddExtensionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ＋ Add MIME Type.
        /// </summary>
        internal static string StructureEditor_MetaAddMimeButton {
            get {
                return ResourceManager.GetString("StructureEditor_MetaAddMimeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ＋ Add Software.
        /// </summary>
        internal static string StructureEditor_MetaAddSoftwareButton {
            get {
                return ResourceManager.GetString("StructureEditor_MetaAddSoftwareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author.
        /// </summary>
        internal static string StructureEditor_MetaAuthorLabel {
            get {
                return ResourceManager.GetString("StructureEditor_MetaAuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author of this definition file.
        /// </summary>
        internal static string StructureEditor_MetaAuthorToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_MetaAuthorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Category.
        /// </summary>
        internal static string StructureEditor_MetaCategoryLabel {
            get {
                return ResourceManager.GetString("StructureEditor_MetaCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Category (auto-set from folder structure: Archives, Images, Audio, Video, etc.).
        /// </summary>
        internal static string StructureEditor_MetaCategoryToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_MetaCategoryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Core.
        /// </summary>
        internal static string StructureEditor_MetaCoreSection {
            get {
                return ResourceManager.GetString("StructureEditor_MetaCoreSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string StructureEditor_MetaDescriptionLabel {
            get {
                return ResourceManager.GetString("StructureEditor_MetaDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diff Mode.
        /// </summary>
        internal static string StructureEditor_MetaDiffModeLabel {
            get {
                return ResourceManager.GetString("StructureEditor_MetaDiffModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preferred diff algorithm for DiffViewer.
        /// </summary>
        internal static string StructureEditor_MetaDiffModeToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_MetaDiffModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File Extensions.
        /// </summary>
        internal static string StructureEditor_MetaExtensionsLabel {
            get {
                return ResourceManager.GetString("StructureEditor_MetaExtensionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Is text format (opens in Code Editor by default).
        /// </summary>
        internal static string StructureEditor_MetaIsTextFormat {
            get {
                return ResourceManager.GetString("StructureEditor_MetaIsTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MIME Types.
        /// </summary>
        internal static string StructureEditor_MetaMimeTypesLabel {
            get {
                return ResourceManager.GetString("StructureEditor_MetaMimeTypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format Name.
        /// </summary>
        internal static string StructureEditor_MetaNameLabel {
            get {
                return ResourceManager.GetString("StructureEditor_MetaNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Human-readable format name (e.g., &apos;ZIP Archive&apos;, &apos;PNG Image&apos;).
        /// </summary>
        internal static string StructureEditor_MetaNameToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_MetaNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preferred Editor.
        /// </summary>
        internal static string StructureEditor_MetaPreferredEditorLabel {
            get {
                return ResourceManager.GetString("StructureEditor_MetaPreferredEditorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preferred editor factory ID for files matching this format.
        /// </summary>
        internal static string StructureEditor_MetaPreferredEditorToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_MetaPreferredEditorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Software.
        /// </summary>
        internal static string StructureEditor_MetaSoftwareLabel {
            get {
                return ResourceManager.GetString("StructureEditor_MetaSoftwareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        internal static string StructureEditor_MetaVersionLabel {
            get {
                return ResourceManager.GetString("StructureEditor_MetaVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version of this definition (e.g., &apos;1.0&apos;, &apos;2.0&apos;).
        /// </summary>
        internal static string StructureEditor_MetaVersionToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_MetaVersionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto-refined (enriched by script — read-only).
        /// </summary>
        internal static string StructureEditor_QualityAutoRefined {
            get {
                return ResourceManager.GetString("StructureEditor_QualityAutoRefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Block Coverage.
        /// </summary>
        internal static string StructureEditor_QualityBlockCoverage {
            get {
                return ResourceManager.GetString("StructureEditor_QualityBlockCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blocks.
        /// </summary>
        internal static string StructureEditor_QualityBlocksLabel {
            get {
                return ResourceManager.GetString("StructureEditor_QualityBlocksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Completeness Score.
        /// </summary>
        internal static string StructureEditor_QualityCompletenessScore {
            get {
                return ResourceManager.GetString("StructureEditor_QualityCompletenessScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Computed Metrics.
        /// </summary>
        internal static string StructureEditor_QualityComputedSection {
            get {
                return ResourceManager.GetString("StructureEditor_QualityComputedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Depth.
        /// </summary>
        internal static string StructureEditor_QualityDepthLabel {
            get {
                return ResourceManager.GetString("StructureEditor_QualityDepthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Documentation Level.
        /// </summary>
        internal static string StructureEditor_QualityDocLevel {
            get {
                return ResourceManager.GetString("StructureEditor_QualityDocLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last Updated.
        /// </summary>
        internal static string StructureEditor_QualityLastUpdated {
            get {
                return ResourceManager.GetString("StructureEditor_QualityLastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format: YYYY-MM-DD (auto-filled on save).
        /// </summary>
        internal static string StructureEditor_QualityLastUpdatedToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_QualityLastUpdatedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Metadata.
        /// </summary>
        internal static string StructureEditor_QualityMetadataLabel {
            get {
                return ResourceManager.GetString("StructureEditor_QualityMetadataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Priority Format (top 100).
        /// </summary>
        internal static string StructureEditor_QualityPriorityFormat {
            get {
                return ResourceManager.GetString("StructureEditor_QualityPriorityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rules.
        /// </summary>
        internal static string StructureEditor_QualityRulesLabel {
            get {
                return ResourceManager.GetString("StructureEditor_QualityRulesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type Distribution.
        /// </summary>
        internal static string StructureEditor_QualityTypeDistribution {
            get {
                return ResourceManager.GetString("StructureEditor_QualityTypeDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variables.
        /// </summary>
        internal static string StructureEditor_QualityVariablesLabel {
            get {
                return ResourceManager.GetString("StructureEditor_QualityVariablesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply.
        /// </summary>
        internal static string StructureEditor_RawJsonApply {
            get {
                return ResourceManager.GetString("StructureEditor_RawJsonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string StructureEditor_RawJsonCancel {
            get {
                return ResourceManager.GetString("StructureEditor_RawJsonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Raw JSON — {0}.
        /// </summary>
        internal static string StructureEditor_RawJsonTitle {
            get {
                return ResourceManager.GetString("StructureEditor_RawJsonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Redo (Ctrl+Y).
        /// </summary>
        internal static string StructureEditor_RedoToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_RedoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save (Ctrl+S).
        /// </summary>
        internal static string StructureEditor_SaveToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Advanced.
        /// </summary>
        internal static string StructureEditor_TabAdvanced {
            get {
                return ResourceManager.GetString("StructureEditor_TabAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blocks.
        /// </summary>
        internal static string StructureEditor_TabBlocks {
            get {
                return ResourceManager.GetString("StructureEditor_TabBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detection.
        /// </summary>
        internal static string StructureEditor_TabDetection {
            get {
                return ResourceManager.GetString("StructureEditor_TabDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Metadata.
        /// </summary>
        internal static string StructureEditor_TabMetadata {
            get {
                return ResourceManager.GetString("StructureEditor_TabMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quality.
        /// </summary>
        internal static string StructureEditor_TabQuality {
            get {
                return ResourceManager.GetString("StructureEditor_TabQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test.
        /// </summary>
        internal static string StructureEditor_TabTest {
            get {
                return ResourceManager.GetString("StructureEditor_TabTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variables.
        /// </summary>
        internal static string StructureEditor_TabVariables {
            get {
                return ResourceManager.GetString("StructureEditor_TabVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse….
        /// </summary>
        internal static string StructureEditor_TestBrowseButton {
            get {
                return ResourceManager.GetString("StructureEditor_TestBrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a binary file to test against.
        /// </summary>
        internal static string StructureEditor_TestBrowseDialogTitle {
            get {
                return ResourceManager.GetString("StructureEditor_TestBrowseDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Block Name.
        /// </summary>
        internal static string StructureEditor_TestColBlockName {
            get {
                return ResourceManager.GetString("StructureEditor_TestColBlockName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Len.
        /// </summary>
        internal static string StructureEditor_TestColLen {
            get {
                return ResourceManager.GetString("StructureEditor_TestColLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Note.
        /// </summary>
        internal static string StructureEditor_TestColNote {
            get {
                return ResourceManager.GetString("StructureEditor_TestColNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Offset.
        /// </summary>
        internal static string StructureEditor_TestColOffset {
            get {
                return ResourceManager.GetString("StructureEditor_TestColOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parsed Value.
        /// </summary>
        internal static string StructureEditor_TestColParsed {
            get {
                return ResourceManager.GetString("StructureEditor_TestColParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Raw (hex).
        /// </summary>
        internal static string StructureEditor_TestColRaw {
            get {
                return ResourceManager.GetString("StructureEditor_TestColRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        internal static string StructureEditor_TestColStatus {
            get {
                return ResourceManager.GetString("StructureEditor_TestColStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string StructureEditor_TestColType {
            get {
                return ResourceManager.GetString("StructureEditor_TestColType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy results to clipboard (TSV).
        /// </summary>
        internal static string StructureEditor_TestCopyToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_TestCopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a file and click ▶ Run Test to test the current format definition..
        /// </summary>
        internal static string StructureEditor_TestEmptyMessage {
            get {
                return ResourceManager.GetString("StructureEditor_TestEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path to the binary file to test.
        /// </summary>
        internal static string StructureEditor_TestFilePathToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_TestFilePathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✕ Error.
        /// </summary>
        internal static string StructureEditor_TestFilterError {
            get {
                return ResourceManager.GetString("StructureEditor_TestFilterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ✓ OK.
        /// </summary>
        internal static string StructureEditor_TestFilterOk {
            get {
                return ResourceManager.GetString("StructureEditor_TestFilterOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⊘ Skipped.
        /// </summary>
        internal static string StructureEditor_TestFilterSkipped {
            get {
                return ResourceManager.GetString("StructureEditor_TestFilterSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⚠ Warning.
        /// </summary>
        internal static string StructureEditor_TestFilterWarning {
            get {
                return ResourceManager.GetString("StructureEditor_TestFilterWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ▶ Run Test.
        /// </summary>
        internal static string StructureEditor_TestRunButton {
            get {
                return ResourceManager.GetString("StructureEditor_TestRunButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test Format Against File.
        /// </summary>
        internal static string StructureEditor_TestSection {
            get {
                return ResourceManager.GetString("StructureEditor_TestSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifies a variable (increment, decrement, setVariable)..
        /// </summary>
        internal static string StructureEditor_TypeHintAction {
            get {
                return ResourceManager.GetString("StructureEditor_TypeHintAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evaluates a math expression and stores the result..
        /// </summary>
        internal static string StructureEditor_TypeHintCompute {
            get {
                return ResourceManager.GetString("StructureEditor_TypeHintCompute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conditionally parses blocks based on a field value or variable..
        /// </summary>
        internal static string StructureEditor_TypeHintConditional {
            get {
                return ResourceManager.GetString("StructureEditor_TypeHintConditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A binary field with a fixed or variable offset and length..
        /// </summary>
        internal static string StructureEditor_TypeHintField {
            get {
                return ResourceManager.GetString("StructureEditor_TypeHintField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repeats a block body while a condition is true..
        /// </summary>
        internal static string StructureEditor_TypeHintLoop {
            get {
                return ResourceManager.GetString("StructureEditor_TypeHintLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reads a variable-length or symbolic value into a named variable..
        /// </summary>
        internal static string StructureEditor_TypeHintMetadata {
            get {
                return ResourceManager.GetString("StructureEditor_TypeHintMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Embeds an external struct definition by reference..
        /// </summary>
        internal static string StructureEditor_TypeHintNested {
            get {
                return ResourceManager.GetString("StructureEditor_TypeHintNested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creates a navigation annotation to a pointed-to offset..
        /// </summary>
        internal static string StructureEditor_TypeHintPointer {
            get {
                return ResourceManager.GetString("StructureEditor_TypeHintPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parses a fixed-count array of structured entries..
        /// </summary>
        internal static string StructureEditor_TypeHintRepeating {
            get {
                return ResourceManager.GetString("StructureEditor_TypeHintRepeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Magic bytes that identify the format at a specific offset..
        /// </summary>
        internal static string StructureEditor_TypeHintSignature {
            get {
                return ResourceManager.GetString("StructureEditor_TypeHintSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selects a variant block set based on a discriminant variable..
        /// </summary>
        internal static string StructureEditor_TypeHintUnion {
            get {
                return ResourceManager.GetString("StructureEditor_TypeHintUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Undo (Ctrl+Z).
        /// </summary>
        internal static string StructureEditor_UndoToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_UndoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unsaved changes.
        /// </summary>
        internal static string StructureEditor_UnsavedChangesToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_UnsavedChangesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ＋ Add Bookmark.
        /// </summary>
        internal static string StructureEditor_V2AddBookmarkButton {
            get {
                return ResourceManager.GetString("StructureEditor_V2AddBookmarkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à + Add Import.
        /// </summary>
        internal static string StructureEditor_V2AddImportButton {
            get {
                return ResourceManager.GetString("StructureEditor_V2AddImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ＋ Add Template.
        /// </summary>
        internal static string StructureEditor_V2AddTemplateButton {
            get {
                return ResourceManager.GetString("StructureEditor_V2AddTemplateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AI Hints.
        /// </summary>
        internal static string StructureEditor_V2AIHintsHeader {
            get {
                return ResourceManager.GetString("StructureEditor_V2AIHintsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à var:name equals 0 or calc:expr.
        /// </summary>
        internal static string StructureEditor_V2AssertionPlaceholder {
            get {
                return ResourceManager.GetString("StructureEditor_V2AssertionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assertions.
        /// </summary>
        internal static string StructureEditor_V2AssertionsHeader {
            get {
                return ResourceManager.GetString("StructureEditor_V2AssertionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boolean expression — Ctrl+Space for functions and variables.
        /// </summary>
        internal static string StructureEditor_V2AssertionToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_V2AssertionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à variableName.
        /// </summary>
        internal static string StructureEditor_V2BookmarkPlaceholder {
            get {
                return ResourceManager.GetString("StructureEditor_V2BookmarkPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable holding the byte offset — Ctrl+Space for suggestions.
        /// </summary>
        internal static string StructureEditor_V2BookmarkToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_V2BookmarkToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checksums.
        /// </summary>
        internal static string StructureEditor_V2ChecksumsHeader {
            get {
                return ResourceManager.GetString("StructureEditor_V2ChecksumsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Templates.
        /// </summary>
        internal static string StructureEditor_V2ExportTemplatesHeader {
            get {
                return ResourceManager.GetString("StructureEditor_V2ExportTemplatesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forensic.
        /// </summary>
        internal static string StructureEditor_V2ForensicHeader {
            get {
                return ResourceManager.GetString("StructureEditor_V2ForensicHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alias used in structRef e.g. PEOpt.
        /// </summary>
        internal static string StructureEditor_V2ImportAliasToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_V2ImportAliasToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format ref e.g. structs/PE_OptionalHeader.
        /// </summary>
        internal static string StructureEditor_V2ImportRefToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_V2ImportRefToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ref = format name (or structs/Name), as = alias used in structRef blocks..
        /// </summary>
        internal static string StructureEditor_V2ImportsDescription {
            get {
                return ResourceManager.GetString("StructureEditor_V2ImportsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Imports ($ref Composition).
        /// </summary>
        internal static string StructureEditor_V2ImportsHeader {
            get {
                return ResourceManager.GetString("StructureEditor_V2ImportsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inspector Layout.
        /// </summary>
        internal static string StructureEditor_V2InspectorLayoutHeader {
            get {
                return ResourceManager.GetString("StructureEditor_V2InspectorLayoutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Navigation Bookmarks.
        /// </summary>
        internal static string StructureEditor_V2NavBookmarksHeader {
            get {
                return ResourceManager.GetString("StructureEditor_V2NavBookmarksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Versioning (VersionDetection / VersionedBlocks).
        /// </summary>
        internal static string StructureEditor_V2VersioningHeader {
            get {
                return ResourceManager.GetString("StructureEditor_V2VersioningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate (Ctrl+Shift+V).
        /// </summary>
        internal static string StructureEditor_ValidateToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_ValidateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} error(s).
        /// </summary>
        internal static string StructureEditor_ValidationErrorCount {
            get {
                return ResourceManager.GetString("StructureEditor_ValidationErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} warning(s).
        /// </summary>
        internal static string StructureEditor_ValidationWarningCount {
            get {
                return ResourceManager.GetString("StructureEditor_ValidationWarningCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ＋ Add Variable.
        /// </summary>
        internal static string StructureEditor_VarsAddButton {
            get {
                return ResourceManager.GetString("StructureEditor_VarsAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string StructureEditor_VarsColDescription {
            get {
                return ResourceManager.GetString("StructureEditor_VarsColDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initial Value.
        /// </summary>
        internal static string StructureEditor_VarsColInitialValue {
            get {
                return ResourceManager.GetString("StructureEditor_VarsColInitialValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variable Name.
        /// </summary>
        internal static string StructureEditor_VarsColName {
            get {
                return ResourceManager.GetString("StructureEditor_VarsColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string StructureEditor_VarsColType {
            get {
                return ResourceManager.GetString("StructureEditor_VarsColType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initial variables available to the block interpreter (e.g. loop counters, computed offsets)..
        /// </summary>
        internal static string StructureEditor_VarsDescription {
            get {
                return ResourceManager.GetString("StructureEditor_VarsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter variables by name.
        /// </summary>
        internal static string StructureEditor_VarsFilterToolTip {
            get {
                return ResourceManager.GetString("StructureEditor_VarsFilterToolTip", resourceCulture);
            }
        }
    }
}
