// ==========================================================
// Project: WpfHexEditor.SDK
// File: DocumentDescriptor.cs
// Author: Auto
// Created: 2026-03-06
// Description:
//     Metadata for a document tab contributed by a plugin via IUIRegistry.RegisterDocumentTab.
//
// Architecture Notes:
//     Document tabs live in the central document host (not dockable side panels).
//     ContentId must be globally unique — use the UIId generated by IUIRegistry.
//
// ==========================================================

namespace WpfHexEditor.SDK.Descriptors;

/// <summary>
/// Describes a document tab (central area) contributed by a plugin.
/// </summary>
public sealed class DocumentDescriptor
{
    /// <summary>Title displayed in the document tab header.</summary>
    public string Title { get; init; } = string.Empty;

    /// <summary>
    /// Unique content identifier for the docking engine.
    /// Must follow the pattern: <c>doc-plugin-{pluginId}-{name}</c>.
    /// </summary>
    public string ContentId { get; init; } = string.Empty;

    /// <summary>Tooltip shown when hovering over the tab header.</summary>
    public string? ToolTip { get; init; }

    /// <summary>Whether the tab can be closed by the user (default: true).</summary>
    public bool CanClose { get; init; } = true;
}
