///////////////////////////////////////////////////////////////
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// GNU Affero General Public License v3.0  2026
// Author : Derek Tremblay (derektremblay666@gmail.com)
// Contributors: Claude Sonnet 4.6
// Project     : WpfHexEditor.Editor.DisassemblyViewer
// File        : DisassemblyViewerResources.Designer.cs
// Description : Strongly-typed accessor for DisassemblyViewerResources.resx.
///////////////////////////////////////////////////////////////

using System.Globalization;
using System.Resources;

namespace WpfHexEditor.Editor.DisassemblyViewer.Properties;

/// <summary>
/// Strongly-typed resource accessor for DisassemblyViewerResources.resx.
/// </summary>
internal static class DisassemblyViewerResources
{
    private static ResourceManager? _resourceManager;
    private static CultureInfo? _resourceCulture;

    /// <summary>
    /// Returns the cached <see cref="ResourceManager"/> for this resource class.
    /// </summary>
    internal static ResourceManager ResourceManager
    {
        get
        {
            _resourceManager ??= new ResourceManager(
                "WpfHexEditor.Editor.DisassemblyViewer.Properties.DisassemblyViewerResources",
                typeof(DisassemblyViewerResources).Assembly);
            return _resourceManager;
        }
    }

    /// <summary>
    /// Overrides the culture used for resource lookup.
    /// Pass <see langword="null"/> to use the current thread's UI culture.
    /// </summary>
    internal static CultureInfo? Culture
    {
        get => _resourceCulture;
        set => _resourceCulture = value;
    }

    private static string GetString(string name) =>
        ResourceManager.GetString(name, _resourceCulture) ?? name;

    // ═══════════════════════════════════════════════════════════════
    // DISASSEMBLY VIEWER
    // ═══════════════════════════════════════════════════════════════

    internal static string DisassemblyViewer_RefreshToolTip   => GetString(nameof(DisassemblyViewer_RefreshToolTip));
    internal static string DisassemblyViewer_OverflowToolTip  => GetString(nameof(DisassemblyViewer_OverflowToolTip));
    internal static string DisassemblyViewer_CopyAllHeader    => GetString(nameof(DisassemblyViewer_CopyAllHeader));
    internal static string DisassemblyViewer_CopyAllToolTip   => GetString(nameof(DisassemblyViewer_CopyAllToolTip));
    internal static string DisassemblyViewer_OverlayDecompiling => GetString(nameof(DisassemblyViewer_OverlayDecompiling));
}
