//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexEditor.PluginDev.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PluginDevResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginDevResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexEditor.PluginDev.Properties.PluginDevResources", typeof(PluginDevResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rebuild plugin automatically on file save.
        /// </summary>
        internal static string PluginDev_AutoRebuild {
            get {
                return ResourceManager.GetString("PluginDev_AutoRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto-scroll to latest entry.
        /// </summary>
        internal static string PluginDev_AutoScroll {
            get {
                return ResourceManager.GetString("PluginDev_AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse….
        /// </summary>
        internal static string PluginDev_Browse {
            get {
                return ResourceManager.GetString("PluginDev_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse.
        /// </summary>
        internal static string PluginDev_Browse_Tab {
            get {
                return ResourceManager.GetString("PluginDev_Browse_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear log.
        /// </summary>
        internal static string PluginDev_ClearLog {
            get {
                return ResourceManager.GetString("PluginDev_ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string PluginDev_Close {
            get {
                return ResourceManager.GetString("PluginDev_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author.
        /// </summary>
        internal static string PluginDev_Col_Author {
            get {
                return ResourceManager.GetString("PluginDev_Col_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloads.
        /// </summary>
        internal static string PluginDev_Col_Downloads {
            get {
                return ResourceManager.GetString("PluginDev_Col_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string PluginDev_Col_Name {
            get {
                return ResourceManager.GetString("PluginDev_Col_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rating.
        /// </summary>
        internal static string PluginDev_Col_Rating {
            get {
                return ResourceManager.GetString("PluginDev_Col_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        internal static string PluginDev_Col_Version {
            get {
                return ResourceManager.GetString("PluginDev_Col_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Level.
        /// </summary>
        internal static string PluginDev_ColLevel {
            get {
                return ResourceManager.GetString("PluginDev_ColLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message.
        /// </summary>
        internal static string PluginDev_ColMessage {
            get {
                return ResourceManager.GetString("PluginDev_ColMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        internal static string PluginDev_ColSource {
            get {
                return ResourceManager.GetString("PluginDev_ColSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time.
        /// </summary>
        internal static string PluginDev_ColTime {
            get {
                return ResourceManager.GetString("PluginDev_ColTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Config:.
        /// </summary>
        internal static string PluginDev_ConfigLabel {
            get {
                return ResourceManager.GetString("PluginDev_ConfigLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy output to plugin directory after successful build.
        /// </summary>
        internal static string PluginDev_CopyOutput {
            get {
                return ResourceManager.GetString("PluginDev_CopyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create &amp; Open.
        /// </summary>
        internal static string PluginDev_CreateAndOpen {
            get {
                return ResourceManager.GetString("PluginDev_CreateAndOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string PluginDev_Error {
            get {
                return ResourceManager.GetString("PluginDev_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Extension Dev Log.
        /// </summary>
        internal static string PluginDev_ExportDevLog {
            get {
                return ResourceManager.GetString("PluginDev_ExportDevLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export log to file.
        /// </summary>
        internal static string PluginDev_ExportLog {
            get {
                return ResourceManager.GetString("PluginDev_ExportLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension:.
        /// </summary>
        internal static string PluginDev_ExtensionLabel {
            get {
                return ResourceManager.GetString("PluginDev_ExtensionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension Marketplace.
        /// </summary>
        internal static string PluginDev_ExtensionMarketplace {
            get {
                return ResourceManager.GetString("PluginDev_ExtensionMarketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter by source.
        /// </summary>
        internal static string PluginDev_FilterBySource {
            get {
                return ResourceManager.GetString("PluginDev_FilterBySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Init timeout (ms):.
        /// </summary>
        internal static string PluginDev_InitTimeout {
            get {
                return ResourceManager.GetString("PluginDev_InitTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installed.
        /// </summary>
        internal static string PluginDev_Installed {
            get {
                return ResourceManager.GetString("PluginDev_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Isolation Mode.
        /// </summary>
        internal static string PluginDev_IsolationMode {
            get {
                return ResourceManager.GetString("PluginDev_IsolationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load Priority (10–90):.
        /// </summary>
        internal static string PluginDev_LoadPriority {
            get {
                return ResourceManager.GetString("PluginDev_LoadPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Debug.
        /// </summary>
        internal static string PluginDev_LogDebug {
            get {
                return ResourceManager.GetString("PluginDev_LogDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string PluginDev_LogError {
            get {
                return ResourceManager.GetString("PluginDev_LogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Info.
        /// </summary>
        internal static string PluginDev_LogInfo {
            get {
                return ResourceManager.GetString("PluginDev_LogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log level:.
        /// </summary>
        internal static string PluginDev_LogLevelLabel {
            get {
                return ResourceManager.GetString("PluginDev_LogLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        internal static string PluginDev_LogWarning {
            get {
                return ResourceManager.GetString("PluginDev_LogWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Extension Project.
        /// </summary>
        internal static string PluginDev_NewExtensionProject {
            get {
                return ResourceManager.GetString("PluginDev_NewExtensionProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next &gt;.
        /// </summary>
        internal static string PluginDev_Next {
            get {
                return ResourceManager.GetString("PluginDev_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open output folder in Explorer.
        /// </summary>
        internal static string PluginDev_OpenOutputFolder {
            get {
                return ResourceManager.GetString("PluginDev_OpenOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Package.
        /// </summary>
        internal static string PluginDev_Package {
            get {
                return ResourceManager.GetString("PluginDev_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Permissions.
        /// </summary>
        internal static string PluginDev_Permissions {
            get {
                return ResourceManager.GetString("PluginDev_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plugin Created.
        /// </summary>
        internal static string PluginDev_PluginCreated {
            get {
                return ResourceManager.GetString("PluginDev_PluginCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publish Extension Package.
        /// </summary>
        internal static string PluginDev_PublishExtensionPackage {
            get {
                return ResourceManager.GetString("PluginDev_PublishExtensionPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ready.
        /// </summary>
        internal static string PluginDev_Ready {
            get {
                return ResourceManager.GetString("PluginDev_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        internal static string PluginDev_Refresh {
            get {
                return ResourceManager.GetString("PluginDev_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full (out-of-process Named Pipe).
        /// </summary>
        internal static string PluginDev_SandboxFull {
            get {
                return ResourceManager.GetString("PluginDev_SandboxFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Light (in-process, catch exceptions).
        /// </summary>
        internal static string PluginDev_SandboxLight {
            get {
                return ResourceManager.GetString("PluginDev_SandboxLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sandbox mode:.
        /// </summary>
        internal static string PluginDev_SandboxModeLabel {
            get {
                return ResourceManager.GetString("PluginDev_SandboxModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        internal static string PluginDev_Search {
            get {
                return ResourceManager.GetString("PluginDev_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select output directory for the plugin project.
        /// </summary>
        internal static string PluginDev_SelectOutputDir {
            get {
                return ResourceManager.GetString("PluginDev_SelectOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select output directory.
        /// </summary>
        internal static string PluginDev_SelectOutputDirPackage {
            get {
                return ResourceManager.GetString("PluginDev_SelectOutputDirPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show &apos;Plugin Dev Mode&apos; indicator in status bar.
        /// </summary>
        internal static string PluginDev_ShowDevMode {
            get {
                return ResourceManager.GetString("PluginDev_ShowDevMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign package before publishing.
        /// </summary>
        internal static string PluginDev_SignBeforePublish {
            get {
                return ResourceManager.GetString("PluginDev_SignBeforePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update All.
        /// </summary>
        internal static string PluginDev_UpdateAll {
            get {
                return ResourceManager.GetString("PluginDev_UpdateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Updates.
        /// </summary>
        internal static string PluginDev_Updates {
            get {
                return ResourceManager.GetString("PluginDev_Updates", resourceCulture);
            }
        }
    }
}
