//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexEditor.Core.Localization.Properties
{
    using System;
    using System.Reflection;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() { }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexEditor.Core.Localization.Properties.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        /// <summary>Gets Ok</summary>
        public static string OkString => ResourceManager.GetString("OkString", resourceCulture)!;

        /// <summary>Gets Cancel</summary>
        public static string CancelString => ResourceManager.GetString("CancelString", resourceCulture)!;

        /// <summary>Gets Close</summary>
        public static string CloseString => ResourceManager.GetString("CloseString", resourceCulture)!;

        /// <summary>Gets Delete</summary>
        public static string DeleteString => ResourceManager.GetString("DeleteString", resourceCulture)!;

        /// <summary>Gets Clear</summary>
        public static string ClearString => ResourceManager.GetString("ClearString", resourceCulture)!;

        /// <summary>Gets Copy</summary>
        public static string CopyString => ResourceManager.GetString("CopyString", resourceCulture)!;

        /// <summary>Gets Paste</summary>
        public static string PasteString => ResourceManager.GetString("PasteString", resourceCulture)!;

        /// <summary>Gets Undo</summary>
        public static string UndoString => ResourceManager.GetString("UndoString", resourceCulture)!;

        /// <summary>Gets Select all</summary>
        public static string SelectAllString => ResourceManager.GetString("SelectAllString", resourceCulture)!;

        /// <summary>Gets Find</summary>
        public static string FindString => ResourceManager.GetString("FindString", resourceCulture)!;

        /// <summary>Gets Replace</summary>
        public static string ReplaceString => ResourceManager.GetString("ReplaceString", resourceCulture)!;

        /// <summary>Gets Find Next</summary>
        public static string FindNextString => ResourceManager.GetString("FindNextString", resourceCulture)!;

        /// <summary>Gets Previous</summary>
        public static string FindPreviousButton => ResourceManager.GetString("FindPreviousButton", resourceCulture)!;

        /// <summary>Gets Find All</summary>
        public static string FindAllString => ResourceManager.GetString("FindAllString", resourceCulture)!;

        /// <summary>Gets Replace All</summary>
        public static string ReplaceAllString => ResourceManager.GetString("ReplaceAllString", resourceCulture)!;

        /// <summary>Gets Replace Next</summary>
        public static string ReplaceNextString => ResourceManager.GetString("ReplaceNextString", resourceCulture)!;

        /// <summary>Gets Value</summary>
        public static string ValueString => ResourceManager.GetString("ValueString", resourceCulture)!;

        /// <summary>Gets Description</summary>
        public static string DescriptionString => ResourceManager.GetString("DescriptionString", resourceCulture)!;

        /// <summary>Gets Length</summary>
        public static string LengthString => ResourceManager.GetString("LengthString", resourceCulture)!;

        /// <summary>Gets Position</summary>
        public static string PositionString => ResourceManager.GetString("PositionString", resourceCulture)!;

        /// <summary>Gets Offset</summary>
        public static string OffsetString => ResourceManager.GetString("OffsetString", resourceCulture)!;

        /// <summary>Gets Count of</summary>
        public static string CountOfString => ResourceManager.GetString("CountOfString", resourceCulture)!;

        /// <summary>Gets Hex</summary>
        public static string HexString => ResourceManager.GetString("HexString", resourceCulture)!;

        /// <summary>Gets File Size</summary>
        public static string FileSizeString => ResourceManager.GetString("FileSizeString", resourceCulture)!;

        /// <summary>Gets Ready</summary>
        public static string ReadyString => ResourceManager.GetString("ReadyString", resourceCulture)!;

        /// <summary>Gets Preview:</summary>
        public static string PreviewString => ResourceManager.GetString("PreviewString", resourceCulture)!;

        /// <summary>Gets Properties</summary>
        public static string PropertiesString => ResourceManager.GetString("PropertiesString", resourceCulture)!;

        /// <summary>Gets Zoom</summary>
        public static string ZoomString => ResourceManager.GetString("ZoomString", resourceCulture)!;

        /// <summary>Gets Reset zoom to 100%</summary>
        public static string ZoomResetString => ResourceManager.GetString("ZoomResetString", resourceCulture)!;

        /// <summary>Gets Status Message</summary>
        public static string StatusMessageString => ResourceManager.GetString("StatusMessageString", resourceCulture)!;

        /// <summary>Gets Command Palette</summary>
        public static string CommandPaletteString => ResourceManager.GetString("CommandPaletteString", resourceCulture)!;

        /// <summary>Gets Show confirmation dialog</summary>
        public static string ShowConfirmationString => ResourceManager.GetString("ShowConfirmationString", resourceCulture)!;

        /// <summary>Gets Byte</summary>
        public static string ByteString => ResourceManager.GetString("ByteString", resourceCulture)!;

        /// <summary>Gets Bytes</summary>
        public static string BytesTagString => ResourceManager.GetString("BytesTagString", resourceCulture)!;

        /// <summary>Gets Kb</summary>
        public static string KBTagString => ResourceManager.GetString("KBTagString", resourceCulture)!;

        /// <summary>Gets Mb</summary>
        public static string MBTagString => ResourceManager.GetString("MBTagString", resourceCulture)!;

        /// <summary>Gets Long</summary>
        public static string LongString => ResourceManager.GetString("LongString", resourceCulture)!;

        /// <summary>Gets end tag</summary>
        public static string EndTagString => ResourceManager.GetString("EndTagString", resourceCulture)!;

        /// <summary>Gets line tag</summary>
        public static string LineTagString => ResourceManager.GetString("LineTagString", resourceCulture)!;

        /// <summary>Gets Ln</summary>
        public static string LineStatusBarTagString => ResourceManager.GetString("LineStatusBarTagString", resourceCulture)!;

        /// <summary>Gets First byte</summary>
        public static string FirstByteString => ResourceManager.GetString("FirstByteString", resourceCulture)!;

        /// <summary>Gets Invalid hexadecimal value</summary>
        public static string ValidationInvalidHexString => ResourceManager.GetString("ValidationInvalidHexString", resourceCulture)!;

        /// <summary>Gets Value required</summary>
        public static string ValidationRequiredString => ResourceManager.GetString("ValidationRequiredString", resourceCulture)!;

        /// <summary>Gets Error: {0}</summary>
        public static string StatusError => ResourceManager.GetString("StatusError", resourceCulture)!;

        /// <summary>Gets An error is occurs when writing.</summary>
        public static string WritingErrorExeptionString => ResourceManager.GetString("WritingErrorExeptionString", resourceCulture)!;

        /// <summary>Gets Can't convert this string to long</summary>
        public static string ConvertStringToLongErrorString => ResourceManager.GetString("ConvertStringToLongErrorString", resourceCulture)!;

        /// <summary>Gets file dropping confirmation</summary>
        public static string FileDroppingConfirmationString => ResourceManager.GetString("FileDroppingConfirmationString", resourceCulture)!;

        /// <summary>Gets open as read only message</summary>
        public static string OpenAsReadOnlyString => ResourceManager.GetString("OpenAsReadOnlyString", resourceCulture)!;

        /// <summary>Gets Copy as hexadecimal</summary>
        public static string CopyAsHexadecimalString => ResourceManager.GetString("CopyAsHexadecimalString", resourceCulture)!;

        /// <summary>Gets Copy as decimal</summary>
        public static string CopyAsDecimalString => ResourceManager.GetString("CopyAsDecimalString", resourceCulture)!;

        /// <summary>Gets Copy as ASCII</summary>
        public static string CopyAsASCIIString => ResourceManager.GetString("CopyAsASCIIString", resourceCulture)!;

        /// <summary>Gets Cut Selection</summary>
        public static string CutSelectionString => ResourceManager.GetString("CutSelectionString", resourceCulture)!;

        /// <summary>Gets Copy Selection</summary>
        public static string CopySelectionString => ResourceManager.GetString("CopySelectionString", resourceCulture)!;

        /// <summary>Gets Delete Byte</summary>
        public static string DeleteByteString => ResourceManager.GetString("DeleteByteString", resourceCulture)!;

        /// <summary>Gets Insert Byte...</summary>
        public static string InsertByteString => ResourceManager.GetString("InsertByteString", resourceCulture)!;

        /// <summary>Gets Invert Selection</summary>
        public static string InvertSelectionString => ResourceManager.GetString("InvertSelectionString", resourceCulture)!;

        /// <summary>Gets Go to Offset...</summary>
        public static string GoToOffsetString => ResourceManager.GetString("GoToOffsetString", resourceCulture)!;

        /// <summary>Gets Edit Mode</summary>
        public static string EditModeString => ResourceManager.GetString("EditModeString", resourceCulture)!;

        /// <summary>Gets Mode: Overwrite</summary>
        public static string ModeOverwriteString => ResourceManager.GetString("ModeOverwriteString", resourceCulture)!;

        /// <summary>Gets Cancel (progress button)</summary>
        public static string ProgressButtonCancel => ResourceManager.GetString("ProgressButtonCancel", resourceCulture)!;
    }
}
