// ==========================================================
// Project: WpfHexEditor.Editor.XamlDesigner
// File: Services/CodeGen/XamlCodeBehindGenerator.cs
// Author: Derek Tremblay
// Created: 2026-05-05
// Description:
//     Emits a C# partial class from a XamlCodeModel.
//     The generated file contains:
//       - Named element fields (one per x:Name)
//       - Event handler stubs (one per event sink)
//     All generated members are annotated with [GeneratedCode] so the
//     CodeBehindMergeEngine can surgically replace them on re-generation
//     without touching any user-written code.
//
// Architecture Notes:
//     StringBuilder-based template emit — NOT Roslyn SyntaxFactory.
//     Roslyn SyntaxFactory would be correct but overly verbose for this use case.
//     Roslyn is reserved for the MergeEngine where AST understanding is required.
//     Generated code compiles as a standalone partial class — the counterpart
//     "user" partial class (the hand-written code-behind) contains InitializeComponent()
//     invocation and all business logic.
// ==========================================================

using System.Text;
using WpfHexEditor.Editor.XamlDesigner.Models;

namespace WpfHexEditor.Editor.XamlDesigner.Services.CodeGen;

/// <summary>
/// Emits C# source for the auto-generated portion of a XAML code-behind file.
/// </summary>
public sealed class XamlCodeBehindGenerator
{
    private readonly EventArgTypeResolver _argResolver;

    public XamlCodeBehindGenerator(EventArgTypeResolver argResolver)
        => _argResolver = argResolver;

    // ── Public API ────────────────────────────────────────────────────────────

    /// <summary>
    /// Generates the complete auto-generated partial class C# source for
    /// <paramref name="model"/>. Returns null when <paramref name="model"/>
    /// has no x:Class (code generation not applicable).
    /// </summary>
    public string? Generate(XamlCodeModel model, string xamlFilePath)
    {
        if (!model.IsCodeGenEnabled)
            return null;

        var sb = new StringBuilder(2048);

        EmitFileHeader(sb, xamlFilePath);
        EmitOpenNamespace(sb, model.Namespace!);
        EmitOpenClass(sb, model);
        EmitNamedElementFields(sb, model);
        EmitEventHandlerStubs(sb,
            model.EventSinks.Select(s => (s.HandlerName, s.EventAttributeName)),
            "// ── Event Handlers (auto-generated stubs) ────────────────────────────────",
            "// TODO: implement");
        EmitEventHandlerStubs(sb,
            model.StyleEventSinks.Select(s => (s.HandlerName, s.EventAttributeName)),
            "// ── Style EventSetter Handlers (auto-generated) ──────────────────────────",
            "// TODO: implement (from Style EventSetter)");
        EmitCloseClass(sb);
        EmitCloseNamespace(sb);

        return sb.ToString();
    }

    // ── Emit helpers ──────────────────────────────────────────────────────────

    private static void EmitFileHeader(StringBuilder sb, string xamlFilePath)
    {
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   WARNING: This file is auto-generated by the WpfHexEditor XAML Designer.");
        sb.AppendLine("//   Named element fields and event handler stubs are synchronized with the XAML source.");
        sb.AppendLine("//   Do NOT remove, rename, or modify the [GeneratedCode] members in this file.");
        sb.AppendLine("//   User code inside event handler bodies is preserved across regenerations.");
        sb.AppendLine($"//   Source: {System.IO.Path.GetFileName(xamlFilePath)}");
        sb.AppendLine($"//   Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Windows;");
        sb.AppendLine("using System.Windows.Controls;");
        sb.AppendLine("using System.Windows.Input;");
        sb.AppendLine();
    }

    private static void EmitOpenNamespace(StringBuilder sb, string ns)
    {
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
    }

    private static void EmitOpenClass(StringBuilder sb, XamlCodeModel model)
    {
        sb.AppendLine($"    // ── Auto-generated partial class ─────────────────────────────────────────");
        sb.AppendLine($"    public partial class {model.ClassName} : {model.RootTypeName}");
        sb.AppendLine("    {");
    }

    private void EmitNamedElementFields(StringBuilder sb, XamlCodeModel model)
    {
        if (model.NamedElements.IsEmpty)
            return;

        sb.AppendLine("        // ── Named Elements (auto-generated) ──────────────────────────────────────");
        sb.AppendLine();

        foreach (var el in model.NamedElements)
        {
            sb.AppendLine($"        [GeneratedCode(\"WpfHexEditor.XamlDesigner\", \"1.0\")]");
            sb.AppendLine($"        private {el.WpfTypeName} {el.Name};");
            sb.AppendLine();
        }
    }

    private void EmitEventHandlerStubs(
        StringBuilder sb,
        IEnumerable<(string HandlerName, string EventAttributeName)> sinks,
        string sectionComment,
        string bodyComment)
    {
        var distinct = sinks
            .GroupBy(s => s.HandlerName, StringComparer.Ordinal)
            .Select(g => g.First())
            .ToList();

        if (distinct.Count == 0)
            return;

        sb.AppendLine($"        {sectionComment}");
        sb.AppendLine();

        foreach (var sink in distinct)
        {
            string argsType = _argResolver.Resolve(sink.EventAttributeName);
            sb.AppendLine($"        [GeneratedCode(\"WpfHexEditor.XamlDesigner\", \"1.0\")]");
            sb.AppendLine($"        private void {sink.HandlerName}(object sender, {argsType} e)");
            sb.AppendLine("        {");
            sb.AppendLine($"            {bodyComment}");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }

    private static void EmitCloseClass(StringBuilder sb)
    {
        sb.AppendLine("    }");
    }

    private static void EmitCloseNamespace(StringBuilder sb)
    {
        sb.AppendLine("}");
    }
}
