// ==========================================================
// Project: whfmt.CodeGen
// File: Generator/VBGenerator.cs
// Description: Generates VB.NET parser classes from parsed .whfmt block definitions.
// Architecture: Mirrors ParserGenerator layout — enum valueMap → Enum, bitflags → <Flags> Enum,
//   big-endian fields → ReverseBytes() helper, BinaryReader-based Parse().
// ==========================================================

using System.Text;

namespace WhfmtCodeGen.Generator;

using BlockDef    = ParserGenerator.BlockDef;
using ChecksumDef = ParserGenerator.ChecksumDef;

/// <summary>Generates a VB.NET parser class from .whfmt block definitions.</summary>
internal static class VBGenerator
{
    public static string Generate(
        string formatName,
        string category,
        string version,
        string desc,
        string namespaceName,
        string className,
        List<BlockDef> blocks,
        List<ChecksumDef> checksums)
    {
        var sb = new StringBuilder();
        var enums = BuildVBEnumDefs(blocks);
        bool needsBSwap = blocks.Any(b => b.Endian == "big" && b.Type != "bytes" && b.Type != "string");

        EmitHeader(sb, formatName, category, version, desc);
        sb.AppendLine($"Namespace {namespaceName}");
        sb.AppendLine();
        EmitEnums(sb, enums);
        EmitClass(sb, className, blocks, enums, needsBSwap);
        sb.AppendLine();
        sb.AppendLine($"End Namespace");
        return sb.ToString();
    }

    // ── Header ───────────────────────────────────────────────────────────────

    private static void EmitHeader(StringBuilder sb, string formatName, string category, string version, string desc)
    {
        sb.AppendLine($"' Auto-generated by whfmt.CodeGen — do not edit");
        sb.AppendLine($"' Format  : {formatName}  v{version}  [{category}]");
        if (!string.IsNullOrEmpty(desc))
            sb.AppendLine($"' {desc}");
        sb.AppendLine();
        sb.AppendLine("Imports System.IO");
        sb.AppendLine();
    }

    // ── Enums ────────────────────────────────────────────────────────────────

    private static void EmitEnums(StringBuilder sb, List<VBEnumDef> enums)
    {
        foreach (var e in enums)
        {
            if (e.IsFlags) sb.AppendLine("    <Flags>");
            sb.AppendLine($"    Public Enum {e.Name}");
            foreach (var (key, val) in e.Members)
                sb.AppendLine($"        {ToVBIdentifier(key)} = {val}");
            sb.AppendLine($"    End Enum");
            sb.AppendLine();
        }
    }

    // ── Class ────────────────────────────────────────────────────────────────

    private static void EmitClass(StringBuilder sb, string className, List<BlockDef> blocks, List<VBEnumDef> enums, bool needsBSwap)
    {
        sb.AppendLine($"    Public Class {className}");
        sb.AppendLine();

        // Properties
        foreach (var b in blocks)
        {
            string vbType = VBType(b, enums);
            string propName = b.PropertyName;
            if (!string.IsNullOrEmpty(b.Description))
                sb.AppendLine($"        ''' <summary>{b.Description}</summary>");
            sb.AppendLine($"        Public Property {propName} As {vbType}");
        }

        sb.AppendLine();

        // Parse()
        sb.AppendLine($"        Public Shared Function Parse(data As Byte()) As {className}");
        sb.AppendLine($"            Using reader As New BinaryReader(New MemoryStream(data))");
        sb.AppendLine($"                Dim result As New {className}()");
        sb.AppendLine();

        foreach (var b in blocks)
            EmitReadStatement(sb, b, enums);

        sb.AppendLine();
        sb.AppendLine($"                Return result");
        sb.AppendLine($"            End Using");
        sb.AppendLine($"        End Function");

        // BSwap helpers
        if (needsBSwap)
        {
            sb.AppendLine();
            EmitBSwapHelpers(sb);
        }

        sb.AppendLine();
        sb.AppendLine($"    End Class");
    }

    // ── Read statements ───────────────────────────────────────────────────────

    private static void EmitReadStatement(StringBuilder sb, BlockDef b, List<VBEnumDef> enums)
    {
        bool bigEndian = b.Endian == "big";
        string prop = $"result.{b.PropertyName}";
        string indent = "                ";

        string readExpr = b.Type switch
        {
            "uint8"   => "reader.ReadByte()",
            "int8"    => "reader.ReadSByte()",
            "uint16"  => bigEndian ? "ReverseBytes(reader.ReadUInt16())" : "reader.ReadUInt16()",
            "int16"   => bigEndian ? "CShort(ReverseBytes(reader.ReadUInt16()))" : "reader.ReadInt16()",
            "uint32"  => bigEndian ? "ReverseBytes(reader.ReadUInt32())" : "reader.ReadUInt32()",
            "int32"   => bigEndian ? "CInt(ReverseBytes(reader.ReadUInt32()))" : "reader.ReadInt32()",
            "uint64"  => bigEndian ? "ReverseBytes(reader.ReadUInt64())" : "reader.ReadUInt64()",
            "int64"   => bigEndian ? "CLng(ReverseBytes(reader.ReadUInt64()))" : "reader.ReadInt64()",
            "float32" => "reader.ReadSingle()",
            "float64" => "reader.ReadDouble()",
            "string"  => $"System.Text.Encoding.ASCII.GetString(reader.ReadBytes({b.Length})).TrimEnd(Chr(0))",
            _         => $"reader.ReadBytes({b.Length})",
        };

        // Apply enum cast if applicable
        var enumDef = enums.FirstOrDefault(e => e.OwnerPropertyName == b.PropertyName);
        if (enumDef is not null)
            readExpr = $"CType({readExpr}, {enumDef.Name})";

        if (b.IsConditional)
        {
            sb.AppendLine($"{indent}If reader.BaseStream.Position + {b.Length} <= reader.BaseStream.Length Then");
            sb.AppendLine($"{indent}    {prop} = {readExpr}");
            sb.AppendLine($"{indent}End If");
        }
        else if (b.IsRepeating)
        {
            string itemType = enumDef is not null ? enumDef.Name : MapVBType(b.Type, b.Length);
            sb.AppendLine($"{indent}{prop} = New List(Of {itemType})()");
            sb.AppendLine($"{indent}Do While reader.BaseStream.Position + {b.Length} <= reader.BaseStream.Length");
            sb.AppendLine($"{indent}    {prop}.Add({readExpr})");
            sb.AppendLine($"{indent}Loop");
        }
        else
        {
            sb.AppendLine($"{indent}{prop} = {readExpr}");
        }
    }

    // ── BSwap helpers ─────────────────────────────────────────────────────────

    private static void EmitBSwapHelpers(StringBuilder sb)
    {
        sb.AppendLine("        Private Shared Function ReverseBytes(value As UShort) As UShort");
        sb.AppendLine("            Return CUShort((value >> 8) Or (value << 8))");
        sb.AppendLine("        End Function");
        sb.AppendLine();
        sb.AppendLine("        Private Shared Function ReverseBytes(value As UInteger) As UInteger");
        sb.AppendLine("            Return ((value And &HFF000000UI) >> 24) Or");
        sb.AppendLine("                   ((value And &H00FF0000UI) >> 8)  Or");
        sb.AppendLine("                   ((value And &H0000FF00UI) << 8)  Or");
        sb.AppendLine("                   ((value And &H000000FFUI) << 24)");
        sb.AppendLine("        End Function");
        sb.AppendLine();
        sb.AppendLine("        Private Shared Function ReverseBytes(value As ULong) As ULong");
        sb.AppendLine("            Dim b As Byte() = BitConverter.GetBytes(value)");
        sb.AppendLine("            Array.Reverse(b)");
        sb.AppendLine("            Return BitConverter.ToUInt64(b, 0)");
        sb.AppendLine("        End Function");
    }

    // ── Type mapping ──────────────────────────────────────────────────────────

    private static string VBType(BlockDef b, List<VBEnumDef> enums)
    {
        var enumDef = enums.FirstOrDefault(e => e.OwnerPropertyName == b.PropertyName);
        if (enumDef is not null)
        {
            if (b.IsConditional) return $"{enumDef.Name}?";
            if (b.IsRepeating)   return $"List(Of {enumDef.Name})";
            return enumDef.Name;
        }

        string mapped = MapVBType(b.Type, b.Length);
        if (b.IsConditional && mapped != "Byte()") return $"{mapped}?";
        if (b.IsRepeating   && mapped != "Byte()") return $"List(Of {mapped})";
        return mapped;
    }

    private static string MapVBType(string type, int length) => type switch
    {
        "uint8"   => "Byte",
        "int8"    => "SByte",
        "uint16"  => "UShort",
        "int16"   => "Short",
        "uint32"  => "UInteger",
        "int32"   => "Integer",
        "uint64"  => "ULong",
        "int64"   => "Long",
        "float32" => "Single",
        "float64" => "Double",
        "string"  => "String",
        _         => "Byte()",
    };

    // ── Enum building ─────────────────────────────────────────────────────────

    private static List<VBEnumDef> BuildVBEnumDefs(List<BlockDef> blocks)
    {
        var result = new List<VBEnumDef>();
        foreach (var b in blocks)
        {
            if (b.ValueMap.Count == 0) continue;
            bool numeric = b.ValueMap.Keys.All(k => long.TryParse(k, out _));
            if (!numeric) continue;

            result.Add(new VBEnumDef
            {
                Name              = b.PropertyName + "Value",
                OwnerPropertyName = b.PropertyName,
                IsFlags           = b.IsBitFlags,
                Members           = b.ValueMap,
            });
        }
        return result;
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static string ToVBIdentifier(string raw)
    {
        var sb = new StringBuilder();
        bool nextUpper = true;
        foreach (char c in raw)
        {
            if (char.IsLetterOrDigit(c)) { sb.Append(nextUpper ? char.ToUpper(c) : c); nextUpper = false; }
            else nextUpper = true;
        }
        // Escape VB reserved words
        string id = sb.ToString();
        return IsVBReserved(id) ? $"[{id}]" : id;
    }

    private static bool IsVBReserved(string id) => id is
        "AddressOf" or "Alias" or "And" or "AndAlso" or "As" or "Boolean" or "ByRef" or
        "Byte" or "ByVal" or "Call" or "Case" or "Catch" or "CBool" or "CByte" or "CChar" or
        "CDate" or "CDbl" or "CDec" or "Char" or "CInt" or "Class" or "CLng" or "CObj" or
        "Continue" or "CSByte" or "CShort" or "CSng" or "CStr" or "CType" or "CUInt" or
        "CULng" or "CUShort" or "Date" or "Decimal" or "Declare" or "Default" or "Delegate" or
        "Dim" or "DirectCast" or "Do" or "Double" or "Each" or "Else" or "ElseIf" or "End" or
        "Enum" or "Erase" or "Error" or "Event" or "Exit" or "False" or "Finally" or "For" or
        "Friend" or "Function" or "Get" or "GetType" or "Global" or "GoTo" or "Handles" or
        "If" or "Implements" or "Imports" or "In" or "Inherits" or "Integer" or "Interface" or
        "Is" or "IsNot" or "Let" or "Lib" or "Like" or "Long" or "Loop" or "Me" or "Mod" or
        "Module" or "MustInherit" or "MustOverride" or "MyBase" or "MyClass" or "Namespace" or
        "Narrowing" or "New" or "Next" or "Not" or "Nothing" or "NotInheritable" or
        "NotOverridable" or "Object" or "Of" or "On" or "Operator" or "Option" or "Optional" or
        "Or" or "OrElse" or "Out" or "Overloads" or "Overridable" or "Overrides" or "ParamArray" or
        "Partial" or "Private" or "Property" or "Protected" or "Public" or "RaiseEvent" or
        "ReadOnly" or "ReDim" or "REM" or "RemoveHandler" or "Resume" or "Return" or "SByte" or
        "Select" or "Set" or "Shadows" or "Shared" or "Short" or "Single" or "Static" or
        "Step" or "Stop" or "String" or "Structure" or "Sub" or "SyncLock" or "Then" or
        "Throw" or "To" or "True" or "Try" or "TryCast" or "TypeOf" or "UInteger" or "ULong" or
        "UShort" or "Using" or "When" or "While" or "Widening" or "With" or "WithEvents" or
        "WriteOnly" or "Xor";

    // ── Shared VBEnumDef model ────────────────────────────────────────────────

    internal sealed class VBEnumDef
    {
        public string Name              { get; init; } = "";
        public string OwnerPropertyName { get; init; } = "";
        public bool   IsFlags           { get; init; }
        public Dictionary<string, string> Members { get; init; } = [];
    }
}
