//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexEditor.Editor.TextEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextEditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextEditorResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexEditor.Editor.TextEditor.Properties.TextEditorResources", typeof(TextEditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encoding.
        /// </summary>
        internal static string TeSb_EncodingLabel {
            get {
                return ResourceManager.GetString("TeSb_EncodingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File encoding.
        /// </summary>
        internal static string TeSb_EncodingTooltip {
            get {
                return ResourceManager.GetString("TeSb_EncodingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string TeSb_LanguageLabel {
            get {
                return ResourceManager.GetString("TeSb_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active syntax language.
        /// </summary>
        internal static string TeSb_LanguageTooltip {
            get {
                return ResourceManager.GetString("TeSb_LanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position.
        /// </summary>
        internal static string TeSb_PositionLabel {
            get {
                return ResourceManager.GetString("TeSb_PositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Caret line and column.
        /// </summary>
        internal static string TeSb_PositionTooltip {
            get {
                return ResourceManager.GetString("TeSb_PositionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        internal static string TeSb_RefreshLabel {
            get {
                return ResourceManager.GetString("TeSb_RefreshLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Render frame time in milliseconds.
        /// </summary>
        internal static string TeSb_RefreshTooltip {
            get {
                return ResourceManager.GetString("TeSb_RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom.
        /// </summary>
        internal static string TeSb_ZoomLabel {
            get {
                return ResourceManager.GetString("TeSb_ZoomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editor zoom level.
        /// </summary>
        internal static string TeSb_ZoomTooltip {
            get {
                return ResourceManager.GetString("TeSb_ZoomTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plain Text.
        /// </summary>
        internal static string TextEditor_LanguageLabelPlainText {
            get {
                return ResourceManager.GetString("TextEditor_LanguageLabelPlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ln 1, Col 1.
        /// </summary>
        internal static string TextEditor_StatusBarCaretPosition {
            get {
                return ResourceManager.GetString("TextEditor_StatusBarCaretPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UTF-8.
        /// </summary>
        internal static string TextEditor_StatusBarEncoding {
            get {
                return ResourceManager.GetString("TextEditor_StatusBarEncoding", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cu_t.
        /// </summary>
        internal static string TextEd_Menu_Cut {
            get {
                return ResourceManager.GetString("TextEd_Menu_Cut", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Copy.
        /// </summary>
        internal static string TextEd_Menu_Copy {
            get {
                return ResourceManager.GetString("TextEd_Menu_Copy", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Paste.
        /// </summary>
        internal static string TextEd_Menu_Paste {
            get {
                return ResourceManager.GetString("TextEd_Menu_Paste", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Undo.
        /// </summary>
        internal static string TextEd_Menu_Undo {
            get {
                return ResourceManager.GetString("TextEd_Menu_Undo", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Redo.
        /// </summary>
        internal static string TextEd_Menu_Redo {
            get {
                return ResourceManager.GetString("TextEd_Menu_Redo", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select _All.
        /// </summary>
        internal static string TextEd_Menu_SelectAll {
            get {
                return ResourceManager.GetString("TextEd_Menu_SelectAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Delete.
        /// </summary>
        internal static string TextEd_Menu_Delete {
            get {
                return ResourceManager.GetString("TextEd_Menu_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show _Whitespace.
        /// </summary>
        internal static string TextEd_Menu_ShowWhitespace {
            get {
                return ResourceManager.GetString("TextEd_Menu_ShowWhitespace", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string TextEd_Menu_WrapNone {
            get {
                return ResourceManager.GetString("TextEd_Menu_WrapNone", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selection Only.
        /// </summary>
        internal static string TextEd_Menu_WrapSelectionOnly {
            get {
                return ResourceManager.GetString("TextEd_Menu_WrapSelectionOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Always.
        /// </summary>
        internal static string TextEd_Menu_WrapAlways {
            get {
                return ResourceManager.GetString("TextEd_Menu_WrapAlways", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Opening.
        /// </summary>
        internal static string TextEd_Status_Opening {
            get {
                return ResourceManager.GetString("TextEd_Status_Opening", resourceCulture);
            }
        }
    }
}
