// Project      : whfmt.SourceGenerator.Tests
// File         : GeneratorIntegrationTests.cs
using Microsoft.CodeAnalysis;
// Description  : Integration tests for WhfmtIncrementalGenerator using CSharpGeneratorDriver.
//                Verifies that valid .whfmt files produce compilable C# source.

namespace whfmt.SourceGenerator.Tests;

[TestClass]
public class GeneratorIntegrationTests
{
    // ── Happy path — C# ────────────────────────────────────────────────────────

    [TestMethod]
    public void SimpleWhfmt_GeneratesCSharp_WithExpectedClassName()
    {
        var result = GeneratorTestHelper.Run("Simple.whfmt", WhfmtFixtures.Simple);

        Assert.AreEqual(0, result.Diagnostics.Length, "No diagnostics expected for valid input.");
        var source = GetSingleSource(result);
        // The generator uses the formatName from the JSON ("Simple Test" → class name "Simple")
        // or falls back to the file name. Either way a class declaration must exist.
        StringAssert.Contains(source, "class ",
            "Generated source should contain a class declaration.");
    }

    [TestMethod]
    public void SimpleWhfmt_GeneratedSource_ContainsExpectedFields()
    {
        var result = GeneratorTestHelper.Run("Simple.whfmt", WhfmtFixtures.Simple);

        var source = GetSingleSource(result);
        StringAssert.Contains(source, "Magic",    "Should contain Magic field.");
        StringAssert.Contains(source, "Version",  "Should contain Version field.");
        StringAssert.Contains(source, "DataSize", "Should contain DataSize field.");
    }

    [TestMethod]
    public void SimpleWhfmt_GeneratedSource_ContainsParseMethods()
    {
        var result = GeneratorTestHelper.Run("Simple.whfmt", WhfmtFixtures.Simple);

        var source = GetSingleSource(result);
        StringAssert.Contains(source, "Parse(",     "Should contain Parse(Stream) method.");
        StringAssert.Contains(source, "ParseFile(", "Should contain ParseFile method.");
    }

    [TestMethod]
    public void SimpleWhfmt_GeneratedSource_HasAutoGeneratedHeader()
    {
        var result = GeneratorTestHelper.Run("Simple.whfmt", WhfmtFixtures.Simple);

        var source = GetSingleSource(result);
        StringAssert.Contains(source, "<auto-generated", "Generated file must have auto-generated marker.");
    }

    // ── Signature + checksum ───────────────────────────────────────────────────

    [TestMethod]
    public void SignatureWhfmt_WithValidation_GeneratesExceptionClasses()
    {
        var result = GeneratorTestHelper.Run(
            "PNGLike.whfmt", WhfmtFixtures.WithSignatureAndChecksum,
            new() { ["build_metadata.AdditionalFiles.WhfmtValidate"] = "true" });

        var source = GetSingleSource(result);
        StringAssert.Contains(source, "InvalidSignatureException",
            "Validation-enabled output should contain InvalidSignatureException.");
    }

    [TestMethod]
    public void SignatureWhfmt_WithoutValidation_OmitsExceptionClasses()
    {
        var result = GeneratorTestHelper.Run(
            "PNGLike.whfmt", WhfmtFixtures.WithSignatureAndChecksum,
            new() { ["build_metadata.AdditionalFiles.WhfmtValidate"] = "false" });

        var source = GetSingleSource(result);
        Assert.IsFalse(source.Contains("InvalidSignatureException"),
            "Validation-disabled output must not contain InvalidSignatureException.");
    }

    // ── Enum / valueMap ────────────────────────────────────────────────────────

    [TestMethod]
    public void EnumWhfmt_GeneratedSource_ContainsEnum()
    {
        var result = GeneratorTestHelper.Run("EnumTest.whfmt", WhfmtFixtures.WithEnum);

        var source = GetSingleSource(result);
        StringAssert.Contains(source, "enum ", "valueMap fields should produce an enum.");
        StringAssert.Contains(source, "Text",   "Enum should contain Text member.");
        StringAssert.Contains(source, "Binary", "Enum should contain Binary member.");
    }

    // ── Repeating field ────────────────────────────────────────────────────────

    [TestMethod]
    public void RepeatingWhfmt_GeneratedSource_ContainsList()
    {
        var result = GeneratorTestHelper.Run("RepTest.whfmt", WhfmtFixtures.WithRepeating);

        var source = GetSingleSource(result);
        StringAssert.Contains(source, "List<", "Repeating fields should produce List<T>.");
    }

    // ── CSharpSpan language ────────────────────────────────────────────────────

    [TestMethod]
    public void SpanLanguage_GeneratesRefStruct()
    {
        var result = GeneratorTestHelper.Run(
            "Simple.whfmt", WhfmtFixtures.Simple,
            new() { ["build_metadata.AdditionalFiles.WhfmtLanguage"] = "CSharpSpan" });

        var source = GetSingleSource(result);
        StringAssert.Contains(source, "ref struct",
            "CSharpSpan output must use ref struct.");
    }

    // ── JSONC (comments + trailing commas) ────────────────────────────────────

    [TestMethod]
    public void JsoncWhfmt_WithComments_ParsesSuccessfully()
    {
        var result = GeneratorTestHelper.Run("JsoncTest.whfmt", WhfmtFixtures.WithComments);

        Assert.AreEqual(0, result.Diagnostics.Length,
            "JSONC with comments and trailing commas should parse without diagnostics.");
        Assert.AreEqual(1, result.GeneratedTrees.Length, "Should produce exactly one generated file.");
    }

    // ── Non-.whfmt file is ignored ─────────────────────────────────────────────

    [TestMethod]
    public void NonWhfmtFile_IsIgnored_NoSourceGenerated()
    {
        var result = GeneratorTestHelper.Run("NotAFormat.txt", "some text content");

        Assert.AreEqual(0, result.GeneratedTrees.Length, "Non-.whfmt files must be ignored.");
        Assert.AreEqual(0, result.Diagnostics.Length, "No diagnostics for ignored files.");
    }

    // ── Multiple files ─────────────────────────────────────────────────────────

    [TestMethod]
    public void MultipleWhfmtFiles_EachGetsSeparateGeneratedSource()
    {
        var result = GeneratorTestHelper.Run(new[]
        {
            ("FormatA.whfmt", WhfmtFixtures.Simple,   (Dictionary<string, string>?)null),
            ("FormatB.whfmt", WhfmtFixtures.WithEnum,  null),
        });

        Assert.AreEqual(2, result.GeneratedTrees.Length,
            "Two .whfmt files should produce two generated sources.");
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static string GetSingleSource(GeneratorDriverRunResult result)
    {
        Assert.AreEqual(1, result.GeneratedTrees.Length,
            $"Expected exactly 1 generated source but got {result.GeneratedTrees.Length}.");
        return result.GeneratedTrees[0].ToString();
    }
}
