//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexEditor.App.Properties {
    using System;


    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }

        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexEditor.App.Properties.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Existing Item.
        /// </summary>
        internal static string App_AddExistingItem {
            get {
                return ResourceManager.GetString("App_AddExistingItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string App_CloseToolTip {
            get {
                return ResourceManager.GetString("App_CloseToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Command Palette (Ctrl+Shift+P).
        /// </summary>
        internal static string App_CommandPaletteToolTip {
            get {
                return ResourceManager.GetString("App_CommandPaletteToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compare with HEAD.
        /// </summary>
        internal static string App_CompareWithHead {
            get {
                return ResourceManager.GetString("App_CompareWithHead", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à No git repository found for this file..
        /// </summary>
        internal static string App_CompareWithHeadNoRepo {
            get {
                return ResourceManager.GetString("App_CompareWithHeadNoRepo", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not extract HEAD version from git..
        /// </summary>
        internal static string App_CompareWithHeadNoVersion {
            get {
                return ResourceManager.GetString("App_CompareWithHeadNoVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Convert TBL.
        /// </summary>
        internal static string App_ConvertTbl {
            get {
                return ResourceManager.GetString("App_ConvertTbl", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customize Layout (Ctrl+Shift+L).
        /// </summary>
        internal static string App_CustomizeLayoutToolTip {
            get {
                return ResourceManager.GetString("App_CustomizeLayoutToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete File.
        /// </summary>
        internal static string App_DeleteFile {
            get {
                return ResourceManager.GetString("App_DeleteFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete &apos;{0}&apos; and send it to the Recycle Bin?{1}{1}This will also remove it from the project..
        /// </summary>
        internal static string App_DeleteFileMessage {
            get {
                return ResourceManager.GetString("App_DeleteFileMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string App_Error {
            get {
                return ResourceManager.GetString("App_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Format Definition.
        /// </summary>
        internal static string App_ExportFormatDefinitionTitle {
            get {
                return ResourceManager.GetString("App_ExportFormatDefinitionTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to create file:{0}{1}.
        /// </summary>
        internal static string App_FailedCreateFile {
            get {
                return ResourceManager.GetString("App_FailedCreateFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to create project:{0}{1}.
        /// </summary>
        internal static string App_FailedCreateProject {
            get {
                return ResourceManager.GetString("App_FailedCreateProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to create solution:
        ///{0}.
        /// </summary>
        internal static string App_FailedCreateSolution {
            get {
                return ResourceManager.GetString("App_FailedCreateSolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to load layout:{0}{1}.
        /// </summary>
        internal static string App_FailedLoadLayout {
            get {
                return ResourceManager.GetString("App_FailedLoadLayout", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to open solution:
        ///{0}.
        /// </summary>
        internal static string App_FailedOpenSolution {
            get {
                return ResourceManager.GetString("App_FailedOpenSolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to write TBLX file:{0}{1}.
        /// </summary>
        internal static string App_FailedWriteTblx {
            get {
                return ResourceManager.GetString("App_FailedWriteTblx", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format Upgrade.
        /// </summary>
        internal static string App_FormatUpgrade {
            get {
                return ResourceManager.GetString("App_FormatUpgrade", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format Upgrade Required.
        /// </summary>
        internal static string App_FormatUpgradeRequired {
            get {
                return ResourceManager.GetString("App_FormatUpgradeRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string App_GoToOffset_Cancel {
            get {
                return ResourceManager.GetString("App_GoToOffset_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decimal.
        /// </summary>
        internal static string App_GoToOffset_Decimal {
            get {
                return ResourceManager.GetString("App_GoToOffset_Decimal", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter offset:.
        /// </summary>
        internal static string App_GoToOffset_EnterOffset {
            get {
                return ResourceManager.GetString("App_GoToOffset_EnterOffset", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go.
        /// </summary>
        internal static string App_GoToOffset_Go {
            get {
                return ResourceManager.GetString("App_GoToOffset_Go", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hexadecimal (0x…).
        /// </summary>
        internal static string App_GoToOffset_Hexadecimal {
            get {
                return ResourceManager.GetString("App_GoToOffset_Hexadecimal", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go To Offset.
        /// </summary>
        internal static string App_GoToOffset_Title {
            get {
                return ResourceManager.GetString("App_GoToOffset_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author:.
        /// </summary>
        internal static string App_ImportFormat_AuthorLabel {
            get {
                return ResourceManager.GetString("App_ImportFormat_AuthorLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string App_ImportFormat_Cancel {
            get {
                return ResourceManager.GetString("App_ImportFormat_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Destination folder:.
        /// </summary>
        internal static string App_ImportFormat_DestinationFolder {
            get {
                return ResourceManager.GetString("App_ImportFormat_DestinationFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions.
        /// </summary>
        internal static string App_ImportFormat_ExtensionsLabel {
            get {
                return ResourceManager.GetString("App_ImportFormat_ExtensionsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Import.
        /// </summary>
        internal static string App_ImportFormat_Import {
            get {
                return ResourceManager.GetString("App_ImportFormat_Import", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preview.
        /// </summary>
        internal static string App_ImportFormat_PreviewLabel {
            get {
                return ResourceManager.GetString("App_ImportFormat_PreviewLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quality.
        /// </summary>
        internal static string App_ImportFormat_QualityLabel {
            get {
                return ResourceManager.GetString("App_ImportFormat_QualityLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Built-in Format Definition.
        /// </summary>
        internal static string App_ImportFormat_Title {
            get {
                return ResourceManager.GetString("App_ImportFormat_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version:.
        /// </summary>
        internal static string App_ImportFormat_VersionLabel {
            get {
                return ResourceManager.GetString("App_ImportFormat_VersionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import into Project.
        /// </summary>
        internal static string App_ImportIntoProject {
            get {
                return ResourceManager.GetString("App_ImportIntoProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy &quot;{0}&quot; into the project directory?{1}{2}{1}The original file will not be deleted..
        /// </summary>
        internal static string App_ImportIntoProjectMessage {
            get {
                return ResourceManager.GetString("App_ImportIntoProjectMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string App_ImportSyntax_Cancel {
            get {
                return ResourceManager.GetString("App_ImportSyntax_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Destination folder:.
        /// </summary>
        internal static string App_ImportSyntax_DestinationFolder {
            get {
                return ResourceManager.GetString("App_ImportSyntax_DestinationFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions.
        /// </summary>
        internal static string App_ImportSyntax_ExtensionsLabel {
            get {
                return ResourceManager.GetString("App_ImportSyntax_ExtensionsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Import.
        /// </summary>
        internal static string App_ImportSyntax_Import {
            get {
                return ResourceManager.GetString("App_ImportSyntax_Import", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Preview.
        /// </summary>
        internal static string App_ImportSyntax_ShowPreview {
            get {
                return ResourceManager.GetString("App_ImportSyntax_ShowPreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Built-in Syntax Definition.
        /// </summary>
        internal static string App_ImportSyntax_Title {
            get {
                return ResourceManager.GetString("App_ImportSyntax_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable.
        /// </summary>
        internal static string App_InfoBar_Disable {
            get {
                return ResourceManager.GetString("App_InfoBar_Disable", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ignore.
        /// </summary>
        internal static string App_InfoBar_Ignore {
            get {
                return ResourceManager.GetString("App_InfoBar_Ignore", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keep my edits.
        /// </summary>
        internal static string App_InfoBar_KeepEdits {
            get {
                return ResourceManager.GetString("App_InfoBar_KeepEdits", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reload.
        /// </summary>
        internal static string App_InfoBar_Reload {
            get {
                return ResourceManager.GetString("App_InfoBar_Reload", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart.
        /// </summary>
        internal static string App_InfoBar_Restart {
            get {
                return ResourceManager.GetString("App_InfoBar_Restart", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximize.
        /// </summary>
        internal static string App_MaximizeToolTip {
            get {
                return ResourceManager.GetString("App_MaximizeToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add E_xisting Item....
        /// </summary>
        internal static string App_Menu_AddExistingItem {
            get {
                return ResourceManager.GetString("App_Menu_AddExistingItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add _New Item....
        /// </summary>
        internal static string App_Menu_AddNewItem {
            get {
                return ResourceManager.GetString("App_Menu_AddNewItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add New _Project....
        /// </summary>
        internal static string App_Menu_AddNewProject {
            get {
                return ResourceManager.GetString("App_Menu_AddNewProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Advanced Find / Replace....
        /// </summary>
        internal static string App_Menu_AdvancedFindReplace {
            get {
                return ResourceManager.GetString("App_Menu_AdvancedFindReplace", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Build.
        /// </summary>
        internal static string App_Menu_Build {
            get {
                return ResourceManager.GetString("App_Menu_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Build _Project.
        /// </summary>
        internal static string App_Menu_BuildProject {
            get {
                return ResourceManager.GetString("App_Menu_BuildProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Build _Solution.
        /// </summary>
        internal static string App_Menu_BuildSolution {
            get {
                return ResourceManager.GetString("App_Menu_BuildSolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à C_ancel Build.
        /// </summary>
        internal static string App_Menu_CancelBuild {
            get {
                return ResourceManager.GetString("App_Menu_CancelBuild", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clean _Project.
        /// </summary>
        internal static string App_Menu_CleanProject {
            get {
                return ResourceManager.GetString("App_Menu_CleanProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Clean Solution.
        /// </summary>
        internal static string App_Menu_CleanSolution {
            get {
                return ResourceManager.GetString("App_Menu_CleanSolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Close.
        /// </summary>
        internal static string App_Menu_Close {
            get {
                return ResourceManager.GetString("App_Menu_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close All _But This.
        /// </summary>
        internal static string App_Menu_CloseAllButThis {
            get {
                return ResourceManager.GetString("App_Menu_CloseAllButThis", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close _All Documents.
        /// </summary>
        internal static string App_Menu_CloseAllDocuments {
            get {
                return ResourceManager.GetString("App_Menu_CloseAllDocuments", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close _All Documents.
        /// </summary>
        internal static string App_Menu_CloseAllDocuments2 {
            get {
                return ResourceManager.GetString("App_Menu_CloseAllDocuments2", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close _All Tab Groups.
        /// </summary>
        internal static string App_Menu_CloseAllTabGroups {
            get {
                return ResourceManager.GetString("App_Menu_CloseAllTabGroups", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Close Document.
        /// </summary>
        internal static string App_Menu_CloseDocument {
            get {
                return ResourceManager.GetString("App_Menu_CloseDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close _Solution.
        /// </summary>
        internal static string App_Menu_CloseSolution {
            get {
                return ResourceManager.GetString("App_Menu_CloseSolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Close Tab Group.
        /// </summary>
        internal static string App_Menu_CloseTabGroup {
            get {
                return ResourceManager.GetString("App_Menu_CloseTabGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à C_lose Workspace.
        /// </summary>
        internal static string App_Menu_CloseWorkspace {
            get {
                return ResourceManager.GetString("App_Menu_CloseWorkspace", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Configuration Manager....
        /// </summary>
        internal static string App_Menu_ConfigurationManager {
            get {
                return ResourceManager.GetString("App_Menu_ConfigurationManager", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Copy.
        /// </summary>
        internal static string App_Menu_Copy {
            get {
                return ResourceManager.GetString("App_Menu_Copy", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Crop Mode.
        /// </summary>
        internal static string App_Menu_CropMode {
            get {
                return ResourceManager.GetString("App_Menu_CropMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cu_t.
        /// </summary>
        internal static string App_Menu_Cut {
            get {
                return ResourceManager.GetString("App_Menu_Cut", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Debug.
        /// </summary>
        internal static string App_Menu_Debug {
            get {
                return ResourceManager.GetString("App_Menu_Debug", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Delete.
        /// </summary>
        internal static string App_Menu_Delete {
            get {
                return ResourceManager.GetString("App_Menu_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Edit.
        /// </summary>
        internal static string App_Menu_Edit {
            get {
                return ResourceManager.GetString("App_Menu_Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à E_xit.
        /// </summary>
        internal static string App_Menu_Exit {
            get {
                return ResourceManager.GetString("App_Menu_Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Export....
        /// </summary>
        internal static string App_Menu_Export {
            get {
                return ResourceManager.GetString("App_Menu_Export", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension _Dev Watch....
        /// </summary>
        internal static string App_Menu_ExtensionDevWatch {
            get {
                return ResourceManager.GetString("App_Menu_ExtensionDevWatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Extension Manager.
        /// </summary>
        internal static string App_Menu_ExtensionManager {
            get {
                return ResourceManager.GetString("App_Menu_ExtensionManager", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension _Marketplace.
        /// </summary>
        internal static string App_Menu_ExtensionMarketplace {
            get {
                return ResourceManager.GetString("App_Menu_ExtensionMarketplace", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Extensions.
        /// </summary>
        internal static string App_Menu_Extensions {
            get {
                return ResourceManager.GetString("App_Menu_Extensions", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions _Monitor.
        /// </summary>
        internal static string App_Menu_ExtensionsMonitor {
            get {
                return ResourceManager.GetString("App_Menu_ExtensionsMonitor", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension System _Settings....
        /// </summary>
        internal static string App_Menu_ExtensionSystemSettings {
            get {
                return ResourceManager.GetString("App_Menu_ExtensionSystemSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _File.
        /// </summary>
        internal static string App_Menu_File {
            get {
                return ResourceManager.GetString("App_Menu_File", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Find....
        /// </summary>
        internal static string App_Menu_Find {
            get {
                return ResourceManager.GetString("App_Menu_Find", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find _Next.
        /// </summary>
        internal static string App_Menu_FindNext {
            get {
                return ResourceManager.GetString("App_Menu_FindNext", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find _Previous.
        /// </summary>
        internal static string App_Menu_FindPrevious {
            get {
                return ResourceManager.GetString("App_Menu_FindPrevious", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flip _Horizontal.
        /// </summary>
        internal static string App_Menu_FlipHorizontal {
            get {
                return ResourceManager.GetString("App_Menu_FlipHorizontal", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flip _Vertical.
        /// </summary>
        internal static string App_Menu_FlipVertical {
            get {
                return ResourceManager.GetString("App_Menu_FlipVertical", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format _Document.
        /// </summary>
        internal static string App_Menu_FormatDocument {
            get {
                return ResourceManager.GetString("App_Menu_FormatDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format _Selection.
        /// </summary>
        internal static string App_Menu_FormatSelection {
            get {
                return ResourceManager.GetString("App_Menu_FormatSelection", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Full Screen.
        /// </summary>
        internal static string App_Menu_FullScreen {
            get {
                return ResourceManager.GetString("App_Menu_FullScreen", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Go To Offset….
        /// </summary>
        internal static string App_Menu_GoToOffset {
            get {
                return ResourceManager.GetString("App_Menu_GoToOffset", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Image.
        /// </summary>
        internal static string App_Menu_Image {
            get {
                return ResourceManager.GetString("App_Menu_Image", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Install from File....
        /// </summary>
        internal static string App_Menu_InstallFromFile {
            get {
                return ResourceManager.GetString("App_Menu_InstallFromFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Layout.
        /// </summary>
        internal static string App_Menu_Layout {
            get {
                return ResourceManager.GetString("App_Menu_Layout", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Load Layout.
        /// </summary>
        internal static string App_Menu_LoadLayout {
            get {
                return ResourceManager.GetString("App_Menu_LoadLayout", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move to _Next Tab Group.
        /// </summary>
        internal static string App_Menu_MoveToNextTabGroup {
            get {
                return ResourceManager.GetString("App_Menu_MoveToNextTabGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move to _Previous Tab Group.
        /// </summary>
        internal static string App_Menu_MoveToPreviousTabGroup {
            get {
                return ResourceManager.GetString("App_Menu_MoveToPreviousTabGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _New.
        /// </summary>
        internal static string App_Menu_New {
            get {
                return ResourceManager.GetString("App_Menu_New", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _File....
        /// </summary>
        internal static string App_Menu_NewFile {
            get {
                return ResourceManager.GetString("App_Menu_NewFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à New _Horizontal Tab Group.
        /// </summary>
        internal static string App_Menu_NewHorizontalTabGroup {
            get {
                return ResourceManager.GetString("App_Menu_NewHorizontalTabGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Project....
        /// </summary>
        internal static string App_Menu_NewProject {
            get {
                return ResourceManager.GetString("App_Menu_NewProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Solution....
        /// </summary>
        internal static string App_Menu_NewSolution {
            get {
                return ResourceManager.GetString("App_Menu_NewSolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à New _Vertical Tab Group.
        /// </summary>
        internal static string App_Menu_NewVerticalTabGroup {
            get {
                return ResourceManager.GetString("App_Menu_NewVerticalTabGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _New Workspace….
        /// </summary>
        internal static string App_Menu_NewWorkspace {
            get {
                return ResourceManager.GetString("App_Menu_NewWorkspace", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Next Document.
        /// </summary>
        internal static string App_Menu_NextDocument {
            get {
                return ResourceManager.GetString("App_Menu_NextDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Open.
        /// </summary>
        internal static string App_Menu_Open {
            get {
                return ResourceManager.GetString("App_Menu_Open", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _File....
        /// </summary>
        internal static string App_Menu_OpenFile {
            get {
                return ResourceManager.GetString("App_Menu_OpenFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Folder....
        /// </summary>
        internal static string App_Menu_OpenFolder {
            get {
                return ResourceManager.GetString("App_Menu_OpenFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Solution/Project....
        /// </summary>
        internal static string App_Menu_OpenSolutionProject {
            get {
                return ResourceManager.GetString("App_Menu_OpenSolutionProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Open Workspace….
        /// </summary>
        internal static string App_Menu_OpenWorkspace {
            get {
                return ResourceManager.GetString("App_Menu_OpenWorkspace", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Options....
        /// </summary>
        internal static string App_Menu_Options {
            get {
                return ResourceManager.GetString("App_Menu_Options", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Paste.
        /// </summary>
        internal static string App_Menu_Paste {
            get {
                return ResourceManager.GetString("App_Menu_Paste", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Previous Document.
        /// </summary>
        internal static string App_Menu_PreviousDocument {
            get {
                return ResourceManager.GetString("App_Menu_PreviousDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Project.
        /// </summary>
        internal static string App_Menu_Project {
            get {
                return ResourceManager.GetString("App_Menu_Project", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à P_roperties....
        /// </summary>
        internal static string App_Menu_Properties {
            get {
                return ResourceManager.GetString("App_Menu_Properties", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rebuild _Project.
        /// </summary>
        internal static string App_Menu_RebuildProject {
            get {
                return ResourceManager.GetString("App_Menu_RebuildProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Rebuild Solution.
        /// </summary>
        internal static string App_Menu_RebuildSolution {
            get {
                return ResourceManager.GetString("App_Menu_RebuildSolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recent _Files.
        /// </summary>
        internal static string App_Menu_RecentFiles {
            get {
                return ResourceManager.GetString("App_Menu_RecentFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recent _Solutions.
        /// </summary>
        internal static string App_Menu_RecentSolutions {
            get {
                return ResourceManager.GetString("App_Menu_RecentSolutions", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Refresh All Extensions.
        /// </summary>
        internal static string App_Menu_RefreshAllExtensions {
            get {
                return ResourceManager.GetString("App_Menu_RefreshAllExtensions", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset to _Original Image.
        /// </summary>
        internal static string App_Menu_ResetImage {
            get {
                return ResourceManager.GetString("App_Menu_ResetImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Reset Layout.
        /// </summary>
        internal static string App_Menu_ResetLayout {
            get {
                return ResourceManager.GetString("App_Menu_ResetLayout", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à R_esize....
        /// </summary>
        internal static string App_Menu_Resize {
            get {
                return ResourceManager.GetString("App_Menu_Resize", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotate _Left.
        /// </summary>
        internal static string App_Menu_RotateLeft {
            get {
                return ResourceManager.GetString("App_Menu_RotateLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotate _Right.
        /// </summary>
        internal static string App_Menu_RotateRight {
            get {
                return ResourceManager.GetString("App_Menu_RotateRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Save.
        /// </summary>
        internal static string App_Menu_Save {
            get {
                return ResourceManager.GetString("App_Menu_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save _All.
        /// </summary>
        internal static string App_Menu_SaveAll {
            get {
                return ResourceManager.GetString("App_Menu_SaveAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Save Layout.
        /// </summary>
        internal static string App_Menu_SaveLayout {
            get {
                return ResourceManager.GetString("App_Menu_SaveLayout", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Save Workspace.
        /// </summary>
        internal static string App_Menu_SaveWorkspace {
            get {
                return ResourceManager.GetString("App_Menu_SaveWorkspace", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Workspace _As….
        /// </summary>
        internal static string App_Menu_SaveWorkspaceAs {
            get {
                return ResourceManager.GetString("App_Menu_SaveWorkspaceAs", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select _All.
        /// </summary>
        internal static string App_Menu_SelectAll {
            get {
                return ResourceManager.GetString("App_Menu_SelectAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tab _Groups.
        /// </summary>
        internal static string App_Menu_TabGroups {
            get {
                return ResourceManager.GetString("App_Menu_TabGroups", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Terminal.
        /// </summary>
        internal static string App_Menu_Terminal {
            get {
                return ResourceManager.GetString("App_Menu_Terminal", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Theme.
        /// </summary>
        internal static string App_Menu_Theme {
            get {
                return ResourceManager.GetString("App_Menu_Theme", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catppuccin _Latte.
        /// </summary>
        internal static string App_Menu_ThemeCatppuccinLatte {
            get {
                return ResourceManager.GetString("App_Menu_ThemeCatppuccinLatte", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catppuccin _Mocha.
        /// </summary>
        internal static string App_Menu_ThemeCatppuccinMocha {
            get {
                return ResourceManager.GetString("App_Menu_ThemeCatppuccinMocha", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Cyberpunk.
        /// </summary>
        internal static string App_Menu_ThemeCyberpunk {
            get {
                return ResourceManager.GetString("App_Menu_ThemeCyberpunk", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Dark.
        /// </summary>
        internal static string App_Menu_ThemeDark {
            get {
                return ResourceManager.GetString("App_Menu_ThemeDark", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dark _Glass.
        /// </summary>
        internal static string App_Menu_ThemeDarkGlass {
            get {
                return ResourceManager.GetString("App_Menu_ThemeDarkGlass", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dr_acula.
        /// </summary>
        internal static string App_Menu_ThemeDracula {
            get {
                return ResourceManager.GetString("App_Menu_ThemeDracula", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Forest.
        /// </summary>
        internal static string App_Menu_ThemeForest {
            get {
                return ResourceManager.GetString("App_Menu_ThemeForest", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gruvbo_x Dark.
        /// </summary>
        internal static string App_Menu_ThemeGruvbox {
            get {
                return ResourceManager.GetString("App_Menu_ThemeGruvbox", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _High Contrast.
        /// </summary>
        internal static string App_Menu_ThemeHighContrast {
            get {
                return ResourceManager.GetString("App_Menu_ThemeHighContrast", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Light.
        /// </summary>
        internal static string App_Menu_ThemeLight {
            get {
                return ResourceManager.GetString("App_Menu_ThemeLight", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matri_x / Terminal.
        /// </summary>
        internal static string App_Menu_ThemeMatrix {
            get {
                return ResourceManager.GetString("App_Menu_ThemeMatrix", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Minimal.
        /// </summary>
        internal static string App_Menu_ThemeMinimal {
            get {
                return ResourceManager.GetString("App_Menu_ThemeMinimal", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Nord.
        /// </summary>
        internal static string App_Menu_ThemeNord {
            get {
                return ResourceManager.GetString("App_Menu_ThemeNord", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Office.
        /// </summary>
        internal static string App_Menu_ThemeOffice {
            get {
                return ResourceManager.GetString("App_Menu_ThemeOffice", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Synthwave &apos;8_4.
        /// </summary>
        internal static string App_Menu_ThemeSynthwave {
            get {
                return ResourceManager.GetString("App_Menu_ThemeSynthwave", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tokyo _Night.
        /// </summary>
        internal static string App_Menu_ThemeTokyoNight {
            get {
                return ResourceManager.GetString("App_Menu_ThemeTokyoNight", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Visual Studio.
        /// </summary>
        internal static string App_Menu_ThemeVisualStudio {
            get {
                return ResourceManager.GetString("App_Menu_ThemeVisualStudio", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à VS2022 Dar_k.
        /// </summary>
        internal static string App_Menu_ThemeVS2022Dark {
            get {
                return ResourceManager.GetString("App_Menu_ThemeVS2022Dark", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle _Locked Layout.
        /// </summary>
        internal static string App_Menu_ToggleLockedLayout {
            get {
                return ResourceManager.GetString("App_Menu_ToggleLockedLayout", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Tools.
        /// </summary>
        internal static string App_Menu_Tools {
            get {
                return ResourceManager.GetString("App_Menu_Tools", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _View.
        /// </summary>
        internal static string App_Menu_View {
            get {
                return ResourceManager.GetString("App_Menu_View", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Window.
        /// </summary>
        internal static string App_Menu_Window {
            get {
                return ResourceManager.GetString("App_Menu_Window", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Workspace.
        /// </summary>
        internal static string App_Menu_Workspace {
            get {
                return ResourceManager.GetString("App_Menu_Workspace", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Write to Disk.
        /// </summary>
        internal static string App_Menu_WriteToDisk {
            get {
                return ResourceManager.GetString("App_Menu_WriteToDisk", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimize.
        /// </summary>
        internal static string App_MinimizeToolTip {
            get {
                return ResourceManager.GetString("App_MinimizeToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notifications.
        /// </summary>
        internal static string App_NotificationsToolTip {
            get {
                return ResourceManager.GetString("App_NotificationsToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Folder.
        /// </summary>
        internal static string App_OpenFolder {
            get {
                return ResourceManager.GetString("App_OpenFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Solution or Project.
        /// </summary>
        internal static string App_OpenSolutionProject {
            get {
                return ResourceManager.GetString("App_OpenSolutionProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Applies to:.
        /// </summary>
        internal static string App_OptionsAppliesToLabel {
            get {
                return ResourceManager.GetString("App_OptionsAppliesToLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear (Escape).
        /// </summary>
        internal static string App_OptionsClearToolTip {
            get {
                return ResourceManager.GetString("App_OptionsClearToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit user settings as JSON.
        /// </summary>
        internal static string App_OptionsEditJsonToolTip {
            get {
                return ResourceManager.GetString("App_OptionsEditJsonToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter:.
        /// </summary>
        internal static string App_OptionsFilterLabel {
            get {
                return ResourceManager.GetString("App_OptionsFilterLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à No settings found..
        /// </summary>
        internal static string App_OptionsNoResults {
            get {
                return ResourceManager.GetString("App_OptionsNoResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search settings (Ctrl+F)….
        /// </summary>
        internal static string App_OptionsSearchPlaceholder {
            get {
                return ResourceManager.GetString("App_OptionsSearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à User (installation).
        /// </summary>
        internal static string App_OptionsUserInstallation {
            get {
                return ResourceManager.GetString("App_OptionsUserInstallation", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error List.
        /// </summary>
        internal static string App_PanelErrorList {
            get {
                return ResourceManager.GetString("App_PanelErrorList", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions Monitor.
        /// </summary>
        internal static string App_PanelExtensionsMonitor {
            get {
                return ResourceManager.GetString("App_PanelExtensionsMonitor", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format Catalog.
        /// </summary>
        internal static string App_PanelFormatCatalog {
            get {
                return ResourceManager.GetString("App_PanelFormatCatalog", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        internal static string App_PanelOptions {
            get {
                return ResourceManager.GetString("App_PanelOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Output.
        /// </summary>
        internal static string App_PanelOutput {
            get {
                return ResourceManager.GetString("App_PanelOutput", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Solution Explorer.
        /// </summary>
        internal static string App_PanelSolutionExplorer {
            get {
                return ResourceManager.GetString("App_PanelSolutionExplorer", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome.
        /// </summary>
        internal static string App_PanelWelcome {
            get {
                return ResourceManager.GetString("App_PanelWelcome", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à A file named.
        /// </summary>
        internal static string App_PasteConflict_AlreadyExists1 {
            get {
                return ResourceManager.GetString("App_PasteConflict_AlreadyExists1", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à already exists in the destination folder..
        /// </summary>
        internal static string App_PasteConflict_AlreadyExists2 {
            get {
                return ResourceManager.GetString("App_PasteConflict_AlreadyExists2", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel All.
        /// </summary>
        internal static string App_PasteConflict_CancelAll {
            get {
                return ResourceManager.GetString("App_PasteConflict_CancelAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a new name to rename the pasted file, or choose an action below..
        /// </summary>
        internal static string App_PasteConflict_Instructions {
            get {
                return ResourceManager.GetString("App_PasteConflict_Instructions", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à New name:.
        /// </summary>
        internal static string App_PasteConflict_NewNameLabel {
            get {
                return ResourceManager.GetString("App_PasteConflict_NewNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename.
        /// </summary>
        internal static string App_PasteConflict_Rename {
            get {
                return ResourceManager.GetString("App_PasteConflict_Rename", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skip.
        /// </summary>
        internal static string App_PasteConflict_Skip {
            get {
                return ResourceManager.GetString("App_PasteConflict_Skip", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à File Already Exists.
        /// </summary>
        internal static string App_PasteConflict_Title {
            get {
                return ResourceManager.GetString("App_PasteConflict_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove folder.
        /// </summary>
        internal static string App_RemoveFolder {
            get {
                return ResourceManager.GetString("App_RemoveFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove folder &apos;{0}&apos; from the project?{1}Items inside will be kept at the project root. The physical directory will not be deleted..
        /// </summary>
        internal static string App_RemoveFolderMessage {
            get {
                return ResourceManager.GetString("App_RemoveFolderMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove from Project.
        /// </summary>
        internal static string App_RemoveFromProject {
            get {
                return ResourceManager.GetString("App_RemoveFromProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove &apos;{0}&apos; from the project?\n(The file on disk will not be deleted.).
        /// </summary>
        internal static string App_RemoveFromProjectMessage {
            get {
                return ResourceManager.GetString("App_RemoveFromProjectMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove solution folder.
        /// </summary>
        internal static string App_RemoveSolutionFolder {
            get {
                return ResourceManager.GetString("App_RemoveSolutionFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove solution folder &apos;{0}&apos;?{1}Projects inside will be kept at the solution root..
        /// </summary>
        internal static string App_RemoveSolutionFolderMessage {
            get {
                return ResourceManager.GetString("App_RemoveSolutionFolderMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename.
        /// </summary>
        internal static string App_RenameTitle {
            get {
                return ResourceManager.GetString("App_RenameTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save As.
        /// </summary>
        internal static string App_SaveAs {
            get {
                return ResourceManager.GetString("App_SaveAs", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string App_SaveChanges_Cancel {
            get {
                return ResourceManager.GetString("App_SaveChanges_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t Save.
        /// </summary>
        internal static string App_SaveChanges_DontSave {
            get {
                return ResourceManager.GetString("App_SaveChanges_DontSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string App_SaveChanges_Save {
            get {
                return ResourceManager.GetString("App_SaveChanges_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select All.
        /// </summary>
        internal static string App_SaveChanges_SelectAll {
            get {
                return ResourceManager.GetString("App_SaveChanges_SelectAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Changes.
        /// </summary>
        internal static string App_SaveChanges_Title {
            get {
                return ResourceManager.GetString("App_SaveChanges_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select file for entropy analysis.
        /// </summary>
        internal static string App_SelectEntropyFile {
            get {
                return ResourceManager.GetString("App_SelectEntropyFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the folder to import.
        /// </summary>
        internal static string App_SelectImportFolder {
            get {
                return ResourceManager.GetString("App_SelectImportFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active character table.
        /// </summary>
        internal static string App_Toolbar_ActiveCharTable {
            get {
                return ResourceManager.GetString("App_Toolbar_ActiveCharTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Build Configuration.
        /// </summary>
        internal static string App_Toolbar_BuildConfig {
            get {
                return ResourceManager.GetString("App_Toolbar_BuildConfig", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Build Solution (Ctrl+Shift+B).
        /// </summary>
        internal static string App_Toolbar_BuildSolution {
            get {
                return ResourceManager.GetString("App_Toolbar_BuildSolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel Build.
        /// </summary>
        internal static string App_Toolbar_CancelBuild {
            get {
                return ResourceManager.GetString("App_Toolbar_CancelBuild", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel operation.
        /// </summary>
        internal static string App_Toolbar_CancelOperation {
            get {
                return ResourceManager.GetString("App_Toolbar_CancelOperation", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Character Table.
        /// </summary>
        internal static string App_Toolbar_CharacterTable {
            get {
                return ResourceManager.GetString("App_Toolbar_CharacterTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clean Solution.
        /// </summary>
        internal static string App_Toolbar_CleanSolution {
            get {
                return ResourceManager.GetString("App_Toolbar_CleanSolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue (F5).
        /// </summary>
        internal static string App_Toolbar_Continue {
            get {
                return ResourceManager.GetString("App_Toolbar_Continue", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy (Ctrl+C).
        /// </summary>
        internal static string App_Toolbar_Copy {
            get {
                return ResourceManager.GetString("App_Toolbar_Copy", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cut (Ctrl+X).
        /// </summary>
        internal static string App_Toolbar_Cut {
            get {
                return ResourceManager.GetString("App_Toolbar_Cut", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dismiss.
        /// </summary>
        internal static string App_Toolbar_Dismiss {
            get {
                return ResourceManager.GetString("App_Toolbar_Dismiss", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find… (Ctrl+F).
        /// </summary>
        internal static string App_Toolbar_Find {
            get {
                return ResourceManager.GetString("App_Toolbar_Find", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find Next (F3).
        /// </summary>
        internal static string App_Toolbar_FindNext {
            get {
                return ResourceManager.GetString("App_Toolbar_FindNext", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find Previous (Shift+F3).
        /// </summary>
        internal static string App_Toolbar_FindPrevious {
            get {
                return ResourceManager.GetString("App_Toolbar_FindPrevious", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à New….
        /// </summary>
        internal static string App_Toolbar_New {
            get {
                return ResourceManager.GetString("App_Toolbar_New", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open….
        /// </summary>
        internal static string App_Toolbar_Open {
            get {
                return ResourceManager.GetString("App_Toolbar_Open", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Output.
        /// </summary>
        internal static string App_Toolbar_Output {
            get {
                return ResourceManager.GetString("App_Toolbar_Output", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parsed Fields.
        /// </summary>
        internal static string App_Toolbar_ParsedFields {
            get {
                return ResourceManager.GetString("App_Toolbar_ParsedFields", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste (Ctrl+V).
        /// </summary>
        internal static string App_Toolbar_Paste {
            get {
                return ResourceManager.GetString("App_Toolbar_Paste", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause.
        /// </summary>
        internal static string App_Toolbar_Pause {
            get {
                return ResourceManager.GetString("App_Toolbar_Pause", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plugin updates available — click to open Marketplace.
        /// </summary>
        internal static string App_Toolbar_PluginUpdates {
            get {
                return ResourceManager.GetString("App_Toolbar_PluginUpdates", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Properties (F4).
        /// </summary>
        internal static string App_Toolbar_Properties {
            get {
                return ResourceManager.GetString("App_Toolbar_Properties", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rebuild Solution.
        /// </summary>
        internal static string App_Toolbar_RebuildSolution {
            get {
                return ResourceManager.GetString("App_Toolbar_RebuildSolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save (Ctrl+S).
        /// </summary>
        internal static string App_Toolbar_Save {
            get {
                return ResourceManager.GetString("App_Toolbar_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save All (Ctrl+Shift+S).
        /// </summary>
        internal static string App_Toolbar_SaveAll {
            get {
                return ResourceManager.GetString("App_Toolbar_SaveAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Solution Explorer (Ctrl+Alt+L).
        /// </summary>
        internal static string App_Toolbar_SolutionExplorer {
            get {
                return ResourceManager.GetString("App_Toolbar_SolutionExplorer", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Without Debugging (Ctrl+F5).
        /// </summary>
        internal static string App_Toolbar_StartNoDebug {
            get {
                return ResourceManager.GetString("App_Toolbar_StartNoDebug", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Startup Project — launched by ▶ Start (Ctrl+F5).
        /// </summary>
        internal static string App_Toolbar_StartupProject {
            get {
                return ResourceManager.GetString("App_Toolbar_StartupProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Step Into (F11).
        /// </summary>
        internal static string App_Toolbar_StepInto {
            get {
                return ResourceManager.GetString("App_Toolbar_StepInto", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Step Out (Shift+F11).
        /// </summary>
        internal static string App_Toolbar_StepOut {
            get {
                return ResourceManager.GetString("App_Toolbar_StepOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Step Over (F10).
        /// </summary>
        internal static string App_Toolbar_StepOver {
            get {
                return ResourceManager.GetString("App_Toolbar_StepOver", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop Debugging (Shift+F5).
        /// </summary>
        internal static string App_Toolbar_StopDebugging {
            get {
                return ResourceManager.GetString("App_Toolbar_StopDebugging", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to switch branch.
        /// </summary>
        internal static string App_Toolbar_SwitchBranch {
            get {
                return ResourceManager.GetString("App_Toolbar_SwitchBranch", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target Platform.
        /// </summary>
        internal static string App_Toolbar_TargetPlatform {
            get {
                return ResourceManager.GetString("App_Toolbar_TargetPlatform", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Uncommitted changes.
        /// </summary>
        internal static string App_Toolbar_UncommittedChanges {
            get {
                return ResourceManager.GetString("App_Toolbar_UncommittedChanges", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upgrade failed: {0}.
        /// </summary>
        internal static string App_UpgradeFailedMessage {
            get {
                return ResourceManager.GetString("App_UpgradeFailedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The following files use an older format (v{0}) that will be upgraded to v{1}:{2}{2}  • {3}{2}{2}A backup (.v{0}.bak) will be created for each file.{2}{2}Upgrade now?.
        /// </summary>
        internal static string App_UpgradeMessagePattern {
            get {
                return ResourceManager.GetString("App_UpgradeMessagePattern", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome Page.
        /// </summary>
        internal static string App_WelcomePageToolTip {
            get {
                return ResourceManager.GetString("App_WelcomePageToolTip", resourceCulture);
            }
        }

        // ── DockItem / panel titles ───────────────────────────────────────────

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension Manager.
        /// </summary>
        internal static string App_DockTitle_ExtensionManager {
            get {
                return ResourceManager.GetString("App_DockTitle_ExtensionManager", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions Monitor.
        /// </summary>
        internal static string App_DockTitle_ExtensionsMonitor {
            get {
                return ResourceManager.GetString("App_DockTitle_ExtensionsMonitor", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension Marketplace.
        /// </summary>
        internal static string App_DockTitle_ExtensionMarketplace {
            get {
                return ResourceManager.GetString("App_DockTitle_ExtensionMarketplace", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminal.
        /// </summary>
        internal static string App_DockTitle_Terminal {
            get {
                return ResourceManager.GetString("App_DockTitle_Terminal", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à settings.json.
        /// </summary>
        internal static string App_DockTitle_SettingsJson {
            get {
                return ResourceManager.GetString("App_DockTitle_SettingsJson", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} — Properties.
        /// </summary>
        internal static string App_DockTitle_Properties {
            get {
                return ResourceManager.GetString("App_DockTitle_Properties", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à NuGet — {0}.
        /// </summary>
        internal static string App_DockTitle_NuGet {
            get {
                return ResourceManager.GetString("App_DockTitle_NuGet", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à NuGet — {0} (Solution).
        /// </summary>
        internal static string App_DockTitle_NuGetSolution {
            get {
                return ResourceManager.GetString("App_DockTitle_NuGetSolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à References — {0}.
        /// </summary>
        internal static string App_DockTitle_References {
            get {
                return ResourceManager.GetString("App_DockTitle_References", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à WpfHexEditor — {0} [read-only format v{1}].
        /// </summary>
        internal static string App_DockTitle_ReadOnly {
            get {
                return ResourceManager.GetString("App_DockTitle_ReadOnly", resourceCulture);
            }
        }

        // ── Context-menu items ────────────────────────────────────────────────

        /// <summary>
        ///   Recherche une chaîne localisée semblable à (none).
        /// </summary>
        internal static string App_ContextMenu_None {
            get {
                return ResourceManager.GetString("App_ContextMenu_None", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compare with Active Editor.
        /// </summary>
        internal static string App_ContextMenu_CompareWithActive {
            get {
                return ResourceManager.GetString("App_ContextMenu_CompareWithActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compare with Another File….
        /// </summary>
        internal static string App_ContextMenu_CompareWithAnother {
            get {
                return ResourceManager.GetString("App_ContextMenu_CompareWithAnother", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recent Projects.
        /// </summary>
        internal static string App_JumpList_RecentProjects {
            get {
                return ResourceManager.GetString("App_JumpList_RecentProjects", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recent Files.
        /// </summary>
        internal static string App_JumpList_RecentFiles {
            get {
                return ResourceManager.GetString("App_JumpList_RecentFiles", resourceCulture);
            }
        }

        // ── Workspace dialogs ─────────────────────────────────────────────────

        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Workspace.
        /// </summary>
        internal static string App_Workspace_NewTitle {
            get {
                return ResourceManager.GetString("App_Workspace_NewTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to create workspace:{0}{1}.
        /// </summary>
        internal static string App_Workspace_NewFailed {
            get {
                return ResourceManager.GetString("App_Workspace_NewFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Workspace.
        /// </summary>
        internal static string App_Workspace_OpenTitle {
            get {
                return ResourceManager.GetString("App_Workspace_OpenTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to open workspace:{0}{1}.
        /// </summary>
        internal static string App_Workspace_OpenFailed {
            get {
                return ResourceManager.GetString("App_Workspace_OpenFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to save workspace:{0}{1}.
        /// </summary>
        internal static string App_Workspace_SaveFailed {
            get {
                return ResourceManager.GetString("App_Workspace_SaveFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Workspace As.
        /// </summary>
        internal static string App_Workspace_SaveAsTitle {
            get {
                return ResourceManager.GetString("App_Workspace_SaveAsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close Workspace.
        /// </summary>
        internal static string App_Workspace_CloseTitle {
            get {
                return ResourceManager.GetString("App_Workspace_CloseTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save workspace &apos;{0}&apos; before closing?.
        /// </summary>
        internal static string App_Workspace_CloseSavePrompt {
            get {
                return ResourceManager.GetString("App_Workspace_CloseSavePrompt", resourceCulture);
            }
        }

        // ── Debugger dialogs ──────────────────────────────────────────────────

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attach to Process.
        /// </summary>
        internal static string App_Debug_AttachTitle {
            get {
                return ResourceManager.GetString("App_Debug_AttachTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Debugger service not available..
        /// </summary>
        internal static string App_Debug_AttachNotAvailable {
            get {
                return ResourceManager.GetString("App_Debug_AttachNotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the process ID (PID) to attach to:.
        /// </summary>
        internal static string App_Debug_AttachPidPrompt {
            get {
                return ResourceManager.GetString("App_Debug_AttachPidPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Debugging.
        /// </summary>
        internal static string App_Debug_StartTitle {
            get {
                return ResourceManager.GetString("App_Debug_StartTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à No startup project is set. Please set a startup project before debugging..
        /// </summary>
        internal static string App_Debug_NoStartupProject {
            get {
                return ResourceManager.GetString("App_Debug_NoStartupProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Build failed. Fix the errors before debugging..
        /// </summary>
        internal static string App_Debug_BuildFailed {
            get {
                return ResourceManager.GetString("App_Debug_BuildFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot find the program to debug:{0}{1}{0}{0}The project was built but the output executable was not found..
        /// </summary>
        internal static string App_Debug_ExeNotFound {
            get {
                return ResourceManager.GetString("App_Debug_ExeNotFound", resourceCulture);
            }
        }

        // ── TBL import ────────────────────────────────────────────────────────

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to load TBL file:{0}{1}.
        /// </summary>
        internal static string App_TblImport_Failed {
            get {
                return ResourceManager.GetString("App_TblImport_Failed", resourceCulture);
            }
        }

        // ── Extensions dialog folder picker ───────────────────────────────────

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Extension Build Output Directory.
        /// </summary>
        internal static string App_Extensions_SelectOutputDir {
            get {
                return ResourceManager.GetString("App_Extensions_SelectOutputDir", resourceCulture);
            }
        }

        internal static string App_Convert_Title {
            get { return ResourceManager.GetString("App_Convert_Title", resourceCulture); }
        }
        internal static string App_Convert_NoSolution {
            get { return ResourceManager.GetString("App_Convert_NoSolution", resourceCulture); }
        }
        internal static string App_Convert_NotSln {
            get { return ResourceManager.GetString("App_Convert_NotSln", resourceCulture); }
        }
        internal static string App_Convert_NotSlnx {
            get { return ResourceManager.GetString("App_Convert_NotSlnx", resourceCulture); }
        }
        internal static string App_Convert_AlreadyWhsln {
            get { return ResourceManager.GetString("App_Convert_AlreadyWhsln", resourceCulture); }
        }
        internal static string App_Convert_Confirm {
            get { return ResourceManager.GetString("App_Convert_Confirm", resourceCulture); }
        }
        internal static string App_Convert_NoLoader {
            get { return ResourceManager.GetString("App_Convert_NoLoader", resourceCulture); }
        }
        internal static string App_Convert_NoLoaderSimple {
            get { return ResourceManager.GetString("App_Convert_NoLoaderSimple", resourceCulture); }
        }
        internal static string App_Convert_Success {
            get { return ResourceManager.GetString("App_Convert_Success", resourceCulture); }
        }
        internal static string App_Convert_Failed {
            get { return ResourceManager.GetString("App_Convert_Failed", resourceCulture); }
        }

        internal static string App_Editor_HexEditor {
            get { return ResourceManager.GetString("App_Editor_HexEditor", resourceCulture); }
        }
        internal static string App_Editor_Encodings {
            get { return ResourceManager.GetString("App_Editor_Encodings", resourceCulture); }
        }
        internal static string App_Editor_ProjectTables {
            get { return ResourceManager.GetString("App_Editor_ProjectTables", resourceCulture); }
        }
        internal static string App_Editor_FileNotFound {
            get { return ResourceManager.GetString("App_Editor_FileNotFound", resourceCulture); }
        }
        internal static string App_Editor_NewDocumentText {
            get { return ResourceManager.GetString("App_Editor_NewDocumentText", resourceCulture); }
        }
        internal static string App_Editor_RefreshPrefix {
            get { return ResourceManager.GetString("App_Editor_RefreshPrefix", resourceCulture); }
        }

        internal static string App_LSP_TryOpenFile {
            get { return ResourceManager.GetString("App_LSP_TryOpenFile", resourceCulture); }
        }
        internal static string App_LSP_LoadAssembly {
            get { return ResourceManager.GetString("App_LSP_LoadAssembly", resourceCulture); }
        }

        internal static string App_Breadcrumb_ProjectNotFound {
            get { return ResourceManager.GetString("App_Breadcrumb_ProjectNotFound", resourceCulture); }
        }
        internal static string App_Breadcrumb_SolutionNotLoaded {
            get { return ResourceManager.GetString("App_Breadcrumb_SolutionNotLoaded", resourceCulture); }
        }

        internal static string App_Debugger_AdapterNotFound {
            get { return ResourceManager.GetString("App_Debugger_AdapterNotFound", resourceCulture); }
        }
        internal static string App_Debugger_AdapterMissing {
            get { return ResourceManager.GetString("App_Debugger_AdapterMissing", resourceCulture); }
        }
        internal static string App_Debugger_Title {
            get { return ResourceManager.GetString("App_Debugger_Title", resourceCulture); }
        }

    }
}
