// Project:     WpfHexEditor.App
// File:        Properties/AppResources.Designer.cs
// Description: Auto-generated strongly-typed resource accessor class.
// Architecture: Internal static class — consumed by XAML code-behind and ViewModels only.
//               Do not reference directly from XAML markup; use x:Static with the resx key.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexEditor.App.Properties
{
    using System;
    using System.Reflection;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal static class AppResources
    {
        private static global::System.Resources.ResourceManager? _resourceManager;

        private static global::System.Globalization.CultureInfo? _resourceCulture;

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (_resourceManager is null)
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                        "WpfHexEditor.App.Properties.AppResources",
                        typeof(AppResources).Assembly);
                    _resourceManager = temp;
                }
                return _resourceManager;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo? Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        // ── Window chrome tooltips ──────────────────────────────────────────

        internal static string App_MinimizeToolTip
            => ResourceManager.GetString(nameof(App_MinimizeToolTip), _resourceCulture)!;

        internal static string App_MaximizeToolTip
            => ResourceManager.GetString(nameof(App_MaximizeToolTip), _resourceCulture)!;

        internal static string App_CloseToolTip
            => ResourceManager.GetString(nameof(App_CloseToolTip), _resourceCulture)!;

        internal static string App_NotificationsToolTip
            => ResourceManager.GetString(nameof(App_NotificationsToolTip), _resourceCulture)!;

        internal static string App_CustomizeLayoutToolTip
            => ResourceManager.GetString(nameof(App_CustomizeLayoutToolTip), _resourceCulture)!;

        internal static string App_CommandPaletteToolTip
            => ResourceManager.GetString(nameof(App_CommandPaletteToolTip), _resourceCulture)!;

        internal static string App_WelcomePageToolTip
            => ResourceManager.GetString(nameof(App_WelcomePageToolTip), _resourceCulture)!;

        // ── File menu ──────────────────────────────────────────────────────

        internal static string App_Menu_File
            => ResourceManager.GetString(nameof(App_Menu_File), _resourceCulture)!;

        internal static string App_Menu_New
            => ResourceManager.GetString(nameof(App_Menu_New), _resourceCulture)!;

        internal static string App_Menu_NewSolution
            => ResourceManager.GetString(nameof(App_Menu_NewSolution), _resourceCulture)!;

        internal static string App_Menu_NewProject
            => ResourceManager.GetString(nameof(App_Menu_NewProject), _resourceCulture)!;

        internal static string App_Menu_NewFile
            => ResourceManager.GetString(nameof(App_Menu_NewFile), _resourceCulture)!;

        internal static string App_Menu_Open
            => ResourceManager.GetString(nameof(App_Menu_Open), _resourceCulture)!;

        internal static string App_Menu_OpenSolutionProject
            => ResourceManager.GetString(nameof(App_Menu_OpenSolutionProject), _resourceCulture)!;

        internal static string App_Menu_OpenFolder
            => ResourceManager.GetString(nameof(App_Menu_OpenFolder), _resourceCulture)!;

        internal static string App_Menu_OpenFile
            => ResourceManager.GetString(nameof(App_Menu_OpenFile), _resourceCulture)!;

        internal static string App_Menu_Close
            => ResourceManager.GetString(nameof(App_Menu_Close), _resourceCulture)!;

        internal static string App_Menu_CloseAllDocuments
            => ResourceManager.GetString(nameof(App_Menu_CloseAllDocuments), _resourceCulture)!;

        internal static string App_Menu_CloseSolution
            => ResourceManager.GetString(nameof(App_Menu_CloseSolution), _resourceCulture)!;

        internal static string App_Menu_Save
            => ResourceManager.GetString(nameof(App_Menu_Save), _resourceCulture)!;

        internal static string App_Menu_SaveAll
            => ResourceManager.GetString(nameof(App_Menu_SaveAll), _resourceCulture)!;

        internal static string App_Menu_WriteToDisk
            => ResourceManager.GetString(nameof(App_Menu_WriteToDisk), _resourceCulture)!;

        internal static string App_Menu_Workspace
            => ResourceManager.GetString(nameof(App_Menu_Workspace), _resourceCulture)!;

        internal static string App_Menu_NewWorkspace
            => ResourceManager.GetString(nameof(App_Menu_NewWorkspace), _resourceCulture)!;

        internal static string App_Menu_OpenWorkspace
            => ResourceManager.GetString(nameof(App_Menu_OpenWorkspace), _resourceCulture)!;

        internal static string App_Menu_SaveWorkspace
            => ResourceManager.GetString(nameof(App_Menu_SaveWorkspace), _resourceCulture)!;

        internal static string App_Menu_SaveWorkspaceAs
            => ResourceManager.GetString(nameof(App_Menu_SaveWorkspaceAs), _resourceCulture)!;

        internal static string App_Menu_CloseWorkspace
            => ResourceManager.GetString(nameof(App_Menu_CloseWorkspace), _resourceCulture)!;

        internal static string App_Menu_RecentSolutions
            => ResourceManager.GetString(nameof(App_Menu_RecentSolutions), _resourceCulture)!;

        internal static string App_Menu_RecentFiles
            => ResourceManager.GetString(nameof(App_Menu_RecentFiles), _resourceCulture)!;

        internal static string App_Menu_Exit
            => ResourceManager.GetString(nameof(App_Menu_Exit), _resourceCulture)!;

        // ── Edit menu ─────────────────────────────────────────────────────

        internal static string App_Menu_Edit
            => ResourceManager.GetString(nameof(App_Menu_Edit), _resourceCulture)!;

        internal static string App_Menu_Cut
            => ResourceManager.GetString(nameof(App_Menu_Cut), _resourceCulture)!;

        internal static string App_Menu_Copy
            => ResourceManager.GetString(nameof(App_Menu_Copy), _resourceCulture)!;

        internal static string App_Menu_Paste
            => ResourceManager.GetString(nameof(App_Menu_Paste), _resourceCulture)!;

        internal static string App_Menu_Delete
            => ResourceManager.GetString(nameof(App_Menu_Delete), _resourceCulture)!;

        internal static string App_Menu_SelectAll
            => ResourceManager.GetString(nameof(App_Menu_SelectAll), _resourceCulture)!;

        internal static string App_Menu_Find
            => ResourceManager.GetString(nameof(App_Menu_Find), _resourceCulture)!;

        internal static string App_Menu_AdvancedFindReplace
            => ResourceManager.GetString(nameof(App_Menu_AdvancedFindReplace), _resourceCulture)!;

        internal static string App_Menu_FindNext
            => ResourceManager.GetString(nameof(App_Menu_FindNext), _resourceCulture)!;

        internal static string App_Menu_FindPrevious
            => ResourceManager.GetString(nameof(App_Menu_FindPrevious), _resourceCulture)!;

        internal static string App_Menu_GoToOffset
            => ResourceManager.GetString(nameof(App_Menu_GoToOffset), _resourceCulture)!;

        internal static string App_Menu_FormatDocument
            => ResourceManager.GetString(nameof(App_Menu_FormatDocument), _resourceCulture)!;

        internal static string App_Menu_FormatSelection
            => ResourceManager.GetString(nameof(App_Menu_FormatSelection), _resourceCulture)!;

        // ── View / Project / Build menus ──────────────────────────────────

        internal static string App_Menu_View
            => ResourceManager.GetString(nameof(App_Menu_View), _resourceCulture)!;

        internal static string App_Menu_Project
            => ResourceManager.GetString(nameof(App_Menu_Project), _resourceCulture)!;

        internal static string App_Menu_AddNewItem
            => ResourceManager.GetString(nameof(App_Menu_AddNewItem), _resourceCulture)!;

        internal static string App_Menu_AddExistingItem
            => ResourceManager.GetString(nameof(App_Menu_AddExistingItem), _resourceCulture)!;

        internal static string App_Menu_AddNewProject
            => ResourceManager.GetString(nameof(App_Menu_AddNewProject), _resourceCulture)!;

        internal static string App_Menu_Properties
            => ResourceManager.GetString(nameof(App_Menu_Properties), _resourceCulture)!;

        internal static string App_Menu_Build
            => ResourceManager.GetString(nameof(App_Menu_Build), _resourceCulture)!;

        internal static string App_Menu_BuildSolution
            => ResourceManager.GetString(nameof(App_Menu_BuildSolution), _resourceCulture)!;

        internal static string App_Menu_BuildProject
            => ResourceManager.GetString(nameof(App_Menu_BuildProject), _resourceCulture)!;

        internal static string App_Menu_RebuildSolution
            => ResourceManager.GetString(nameof(App_Menu_RebuildSolution), _resourceCulture)!;

        internal static string App_Menu_RebuildProject
            => ResourceManager.GetString(nameof(App_Menu_RebuildProject), _resourceCulture)!;

        internal static string App_Menu_CleanSolution
            => ResourceManager.GetString(nameof(App_Menu_CleanSolution), _resourceCulture)!;

        internal static string App_Menu_CleanProject
            => ResourceManager.GetString(nameof(App_Menu_CleanProject), _resourceCulture)!;

        internal static string App_Menu_CancelBuild
            => ResourceManager.GetString(nameof(App_Menu_CancelBuild), _resourceCulture)!;

        internal static string App_Menu_ConfigurationManager
            => ResourceManager.GetString(nameof(App_Menu_ConfigurationManager), _resourceCulture)!;

        internal static string App_Menu_Debug
            => ResourceManager.GetString(nameof(App_Menu_Debug), _resourceCulture)!;

        // ── Window menu ───────────────────────────────────────────────────

        internal static string App_Menu_Window
            => ResourceManager.GetString(nameof(App_Menu_Window), _resourceCulture)!;

        internal static string App_Menu_CloseDocument
            => ResourceManager.GetString(nameof(App_Menu_CloseDocument), _resourceCulture)!;

        internal static string App_Menu_CloseAllButThis
            => ResourceManager.GetString(nameof(App_Menu_CloseAllButThis), _resourceCulture)!;

        internal static string App_Menu_CloseAllDocuments2
            => ResourceManager.GetString(nameof(App_Menu_CloseAllDocuments2), _resourceCulture)!;

        internal static string App_Menu_NextDocument
            => ResourceManager.GetString(nameof(App_Menu_NextDocument), _resourceCulture)!;

        internal static string App_Menu_PreviousDocument
            => ResourceManager.GetString(nameof(App_Menu_PreviousDocument), _resourceCulture)!;

        internal static string App_Menu_FullScreen
            => ResourceManager.GetString(nameof(App_Menu_FullScreen), _resourceCulture)!;

        internal static string App_Menu_TabGroups
            => ResourceManager.GetString(nameof(App_Menu_TabGroups), _resourceCulture)!;

        internal static string App_Menu_NewVerticalTabGroup
            => ResourceManager.GetString(nameof(App_Menu_NewVerticalTabGroup), _resourceCulture)!;

        internal static string App_Menu_NewHorizontalTabGroup
            => ResourceManager.GetString(nameof(App_Menu_NewHorizontalTabGroup), _resourceCulture)!;

        internal static string App_Menu_MoveToNextTabGroup
            => ResourceManager.GetString(nameof(App_Menu_MoveToNextTabGroup), _resourceCulture)!;

        internal static string App_Menu_MoveToPreviousTabGroup
            => ResourceManager.GetString(nameof(App_Menu_MoveToPreviousTabGroup), _resourceCulture)!;

        internal static string App_Menu_CloseTabGroup
            => ResourceManager.GetString(nameof(App_Menu_CloseTabGroup), _resourceCulture)!;

        internal static string App_Menu_CloseAllTabGroups
            => ResourceManager.GetString(nameof(App_Menu_CloseAllTabGroups), _resourceCulture)!;

        internal static string App_Menu_Layout
            => ResourceManager.GetString(nameof(App_Menu_Layout), _resourceCulture)!;

        internal static string App_Menu_SaveLayout
            => ResourceManager.GetString(nameof(App_Menu_SaveLayout), _resourceCulture)!;

        internal static string App_Menu_LoadLayout
            => ResourceManager.GetString(nameof(App_Menu_LoadLayout), _resourceCulture)!;

        internal static string App_Menu_ResetLayout
            => ResourceManager.GetString(nameof(App_Menu_ResetLayout), _resourceCulture)!;

        internal static string App_Menu_ToggleLockedLayout
            => ResourceManager.GetString(nameof(App_Menu_ToggleLockedLayout), _resourceCulture)!;

        // ── Tools / Extensions / Theme menus ─────────────────────────────

        internal static string App_Menu_Tools
            => ResourceManager.GetString(nameof(App_Menu_Tools), _resourceCulture)!;

        internal static string App_Menu_Terminal
            => ResourceManager.GetString(nameof(App_Menu_Terminal), _resourceCulture)!;

        internal static string App_Menu_Options
            => ResourceManager.GetString(nameof(App_Menu_Options), _resourceCulture)!;

        internal static string App_Menu_Extensions
            => ResourceManager.GetString(nameof(App_Menu_Extensions), _resourceCulture)!;

        internal static string App_Menu_ExtensionManager
            => ResourceManager.GetString(nameof(App_Menu_ExtensionManager), _resourceCulture)!;

        internal static string App_Menu_ExtensionsMonitor
            => ResourceManager.GetString(nameof(App_Menu_ExtensionsMonitor), _resourceCulture)!;

        internal static string App_Menu_ExtensionMarketplace
            => ResourceManager.GetString(nameof(App_Menu_ExtensionMarketplace), _resourceCulture)!;

        internal static string App_Menu_InstallFromFile
            => ResourceManager.GetString(nameof(App_Menu_InstallFromFile), _resourceCulture)!;

        internal static string App_Menu_RefreshAllExtensions
            => ResourceManager.GetString(nameof(App_Menu_RefreshAllExtensions), _resourceCulture)!;

        internal static string App_Menu_ExtensionDevWatch
            => ResourceManager.GetString(nameof(App_Menu_ExtensionDevWatch), _resourceCulture)!;

        internal static string App_Menu_ExtensionSystemSettings
            => ResourceManager.GetString(nameof(App_Menu_ExtensionSystemSettings), _resourceCulture)!;

        internal static string App_Menu_Theme
            => ResourceManager.GetString(nameof(App_Menu_Theme), _resourceCulture)!;

        internal static string App_Menu_ThemeDark
            => ResourceManager.GetString(nameof(App_Menu_ThemeDark), _resourceCulture)!;

        internal static string App_Menu_ThemeVS2022Dark
            => ResourceManager.GetString(nameof(App_Menu_ThemeVS2022Dark), _resourceCulture)!;

        internal static string App_Menu_ThemeVisualStudio
            => ResourceManager.GetString(nameof(App_Menu_ThemeVisualStudio), _resourceCulture)!;

        internal static string App_Menu_ThemeDarkGlass
            => ResourceManager.GetString(nameof(App_Menu_ThemeDarkGlass), _resourceCulture)!;

        internal static string App_Menu_ThemeCyberpunk
            => ResourceManager.GetString(nameof(App_Menu_ThemeCyberpunk), _resourceCulture)!;

        internal static string App_Menu_ThemeSynthwave
            => ResourceManager.GetString(nameof(App_Menu_ThemeSynthwave), _resourceCulture)!;

        internal static string App_Menu_ThemeMatrix
            => ResourceManager.GetString(nameof(App_Menu_ThemeMatrix), _resourceCulture)!;

        internal static string App_Menu_ThemeNord
            => ResourceManager.GetString(nameof(App_Menu_ThemeNord), _resourceCulture)!;

        internal static string App_Menu_ThemeDracula
            => ResourceManager.GetString(nameof(App_Menu_ThemeDracula), _resourceCulture)!;

        internal static string App_Menu_ThemeGruvbox
            => ResourceManager.GetString(nameof(App_Menu_ThemeGruvbox), _resourceCulture)!;

        internal static string App_Menu_ThemeCatppuccinMocha
            => ResourceManager.GetString(nameof(App_Menu_ThemeCatppuccinMocha), _resourceCulture)!;

        internal static string App_Menu_ThemeTokyoNight
            => ResourceManager.GetString(nameof(App_Menu_ThemeTokyoNight), _resourceCulture)!;

        internal static string App_Menu_ThemeLight
            => ResourceManager.GetString(nameof(App_Menu_ThemeLight), _resourceCulture)!;

        internal static string App_Menu_ThemeOffice
            => ResourceManager.GetString(nameof(App_Menu_ThemeOffice), _resourceCulture)!;

        internal static string App_Menu_ThemeCatppuccinLatte
            => ResourceManager.GetString(nameof(App_Menu_ThemeCatppuccinLatte), _resourceCulture)!;

        internal static string App_Menu_ThemeMinimal
            => ResourceManager.GetString(nameof(App_Menu_ThemeMinimal), _resourceCulture)!;

        internal static string App_Menu_ThemeForest
            => ResourceManager.GetString(nameof(App_Menu_ThemeForest), _resourceCulture)!;

        internal static string App_Menu_ThemeHighContrast
            => ResourceManager.GetString(nameof(App_Menu_ThemeHighContrast), _resourceCulture)!;

        // ── Image menu ────────────────────────────────────────────────────

        internal static string App_Menu_Image
            => ResourceManager.GetString(nameof(App_Menu_Image), _resourceCulture)!;

        internal static string App_Menu_RotateRight
            => ResourceManager.GetString(nameof(App_Menu_RotateRight), _resourceCulture)!;

        internal static string App_Menu_RotateLeft
            => ResourceManager.GetString(nameof(App_Menu_RotateLeft), _resourceCulture)!;

        internal static string App_Menu_FlipHorizontal
            => ResourceManager.GetString(nameof(App_Menu_FlipHorizontal), _resourceCulture)!;

        internal static string App_Menu_FlipVertical
            => ResourceManager.GetString(nameof(App_Menu_FlipVertical), _resourceCulture)!;

        internal static string App_Menu_CropMode
            => ResourceManager.GetString(nameof(App_Menu_CropMode), _resourceCulture)!;

        internal static string App_Menu_Resize
            => ResourceManager.GetString(nameof(App_Menu_Resize), _resourceCulture)!;

        internal static string App_Menu_Export
            => ResourceManager.GetString(nameof(App_Menu_Export), _resourceCulture)!;

        internal static string App_Menu_ResetImage
            => ResourceManager.GetString(nameof(App_Menu_ResetImage), _resourceCulture)!;

        // ── OptionsEditorControl.xaml ─────────────────────────────────────

        internal static string App_OptionsEditJsonToolTip
            => ResourceManager.GetString(nameof(App_OptionsEditJsonToolTip), _resourceCulture)!;

        internal static string App_OptionsAppliesToLabel
            => ResourceManager.GetString(nameof(App_OptionsAppliesToLabel), _resourceCulture)!;

        internal static string App_OptionsUserInstallation
            => ResourceManager.GetString(nameof(App_OptionsUserInstallation), _resourceCulture)!;

        internal static string App_OptionsFilterLabel
            => ResourceManager.GetString(nameof(App_OptionsFilterLabel), _resourceCulture)!;

        internal static string App_OptionsSearchPlaceholder
            => ResourceManager.GetString(nameof(App_OptionsSearchPlaceholder), _resourceCulture)!;

        internal static string App_OptionsClearToolTip
            => ResourceManager.GetString(nameof(App_OptionsClearToolTip), _resourceCulture)!;

        internal static string App_OptionsNoResults
            => ResourceManager.GetString(nameof(App_OptionsNoResults), _resourceCulture)!;

        // ── PasteConflictDialog.xaml ──────────────────────────────────────

        internal static string App_PasteConflict_Title
            => ResourceManager.GetString(nameof(App_PasteConflict_Title), _resourceCulture)!;

        internal static string App_PasteConflict_Rename
            => ResourceManager.GetString(nameof(App_PasteConflict_Rename), _resourceCulture)!;

        internal static string App_PasteConflict_Skip
            => ResourceManager.GetString(nameof(App_PasteConflict_Skip), _resourceCulture)!;

        internal static string App_PasteConflict_CancelAll
            => ResourceManager.GetString(nameof(App_PasteConflict_CancelAll), _resourceCulture)!;

        internal static string App_PasteConflict_AlreadyExists1
            => ResourceManager.GetString(nameof(App_PasteConflict_AlreadyExists1), _resourceCulture)!;

        internal static string App_PasteConflict_AlreadyExists2
            => ResourceManager.GetString(nameof(App_PasteConflict_AlreadyExists2), _resourceCulture)!;

        internal static string App_PasteConflict_Instructions
            => ResourceManager.GetString(nameof(App_PasteConflict_Instructions), _resourceCulture)!;

        internal static string App_PasteConflict_NewNameLabel
            => ResourceManager.GetString(nameof(App_PasteConflict_NewNameLabel), _resourceCulture)!;

        // ── SaveChangesDialog.xaml ────────────────────────────────────────

        internal static string App_SaveChanges_Title
            => ResourceManager.GetString(nameof(App_SaveChanges_Title), _resourceCulture)!;

        internal static string App_SaveChanges_SelectAll
            => ResourceManager.GetString(nameof(App_SaveChanges_SelectAll), _resourceCulture)!;

        internal static string App_SaveChanges_Save
            => ResourceManager.GetString(nameof(App_SaveChanges_Save), _resourceCulture)!;

        internal static string App_SaveChanges_DontSave
            => ResourceManager.GetString(nameof(App_SaveChanges_DontSave), _resourceCulture)!;

        internal static string App_SaveChanges_Cancel
            => ResourceManager.GetString(nameof(App_SaveChanges_Cancel), _resourceCulture)!;

        // ── GoToOffsetDialog.xaml ─────────────────────────────────────────

        internal static string App_GoToOffset_Title
            => ResourceManager.GetString(nameof(App_GoToOffset_Title), _resourceCulture)!;

        internal static string App_GoToOffset_EnterOffset
            => ResourceManager.GetString(nameof(App_GoToOffset_EnterOffset), _resourceCulture)!;

        internal static string App_GoToOffset_Hexadecimal
            => ResourceManager.GetString(nameof(App_GoToOffset_Hexadecimal), _resourceCulture)!;

        internal static string App_GoToOffset_Decimal
            => ResourceManager.GetString(nameof(App_GoToOffset_Decimal), _resourceCulture)!;

        internal static string App_GoToOffset_Go
            => ResourceManager.GetString(nameof(App_GoToOffset_Go), _resourceCulture)!;

        internal static string App_GoToOffset_Cancel
            => ResourceManager.GetString(nameof(App_GoToOffset_Cancel), _resourceCulture)!;

        // ── ImportEmbeddedFormatDialog.xaml ───────────────────────────────

        internal static string App_ImportFormat_Title
            => ResourceManager.GetString(nameof(App_ImportFormat_Title), _resourceCulture)!;

        internal static string App_ImportFormat_VersionLabel
            => ResourceManager.GetString(nameof(App_ImportFormat_VersionLabel), _resourceCulture)!;

        internal static string App_ImportFormat_AuthorLabel
            => ResourceManager.GetString(nameof(App_ImportFormat_AuthorLabel), _resourceCulture)!;

        internal static string App_ImportFormat_ExtensionsLabel
            => ResourceManager.GetString(nameof(App_ImportFormat_ExtensionsLabel), _resourceCulture)!;

        internal static string App_ImportFormat_QualityLabel
            => ResourceManager.GetString(nameof(App_ImportFormat_QualityLabel), _resourceCulture)!;

        internal static string App_ImportFormat_PreviewLabel
            => ResourceManager.GetString(nameof(App_ImportFormat_PreviewLabel), _resourceCulture)!;

        internal static string App_ImportFormat_DestinationFolder
            => ResourceManager.GetString(nameof(App_ImportFormat_DestinationFolder), _resourceCulture)!;

        internal static string App_ImportFormat_Import
            => ResourceManager.GetString(nameof(App_ImportFormat_Import), _resourceCulture)!;

        internal static string App_ImportFormat_Cancel
            => ResourceManager.GetString(nameof(App_ImportFormat_Cancel), _resourceCulture)!;

        // ── ImportEmbeddedSyntaxDialog.xaml ───────────────────────────────

        internal static string App_ImportSyntax_Title
            => ResourceManager.GetString(nameof(App_ImportSyntax_Title), _resourceCulture)!;

        internal static string App_ImportSyntax_ShowPreview
            => ResourceManager.GetString(nameof(App_ImportSyntax_ShowPreview), _resourceCulture)!;

        internal static string App_ImportSyntax_ExtensionsLabel
            => ResourceManager.GetString(nameof(App_ImportSyntax_ExtensionsLabel), _resourceCulture)!;

        internal static string App_ImportSyntax_DestinationFolder
            => ResourceManager.GetString(nameof(App_ImportSyntax_DestinationFolder), _resourceCulture)!;

        internal static string App_ImportSyntax_Import
            => ResourceManager.GetString(nameof(App_ImportSyntax_Import), _resourceCulture)!;

        internal static string App_ImportSyntax_Cancel
            => ResourceManager.GetString(nameof(App_ImportSyntax_Cancel), _resourceCulture)!;

        // ── Panel titles and dialog titles ────────────────────────────────

        internal static string App_PanelWelcome
            => ResourceManager.GetString(nameof(App_PanelWelcome), _resourceCulture)!;

        internal static string App_PanelSolutionExplorer
            => ResourceManager.GetString(nameof(App_PanelSolutionExplorer), _resourceCulture)!;

        internal static string App_PanelErrorList
            => ResourceManager.GetString(nameof(App_PanelErrorList), _resourceCulture)!;

        internal static string App_PanelExtensionsMonitor
            => ResourceManager.GetString(nameof(App_PanelExtensionsMonitor), _resourceCulture)!;

        internal static string App_PanelOutput
            => ResourceManager.GetString(nameof(App_PanelOutput), _resourceCulture)!;

        internal static string App_ExportFormatDefinitionTitle
            => ResourceManager.GetString(nameof(App_ExportFormatDefinitionTitle), _resourceCulture)!;

        internal static string App_FormatUpgradeRequired
            => ResourceManager.GetString(nameof(App_FormatUpgradeRequired), _resourceCulture)!;

        internal static string App_FormatUpgrade
            => ResourceManager.GetString(nameof(App_FormatUpgrade), _resourceCulture)!;

        internal static string App_ConvertTbl
            => ResourceManager.GetString(nameof(App_ConvertTbl), _resourceCulture)!;

        internal static string App_RemoveFromProject
            => ResourceManager.GetString(nameof(App_RemoveFromProject), _resourceCulture)!;

        internal static string App_RemoveFromProjectMessage
            => ResourceManager.GetString(nameof(App_RemoveFromProjectMessage), _resourceCulture)!;

        internal static string App_DeleteFile
            => ResourceManager.GetString(nameof(App_DeleteFile), _resourceCulture)!;

        internal static string App_DeleteFileMessage
            => ResourceManager.GetString(nameof(App_DeleteFileMessage), _resourceCulture)!;

        internal static string App_RemoveFolder
            => ResourceManager.GetString(nameof(App_RemoveFolder), _resourceCulture)!;

        internal static string App_RemoveSolutionFolder
            => ResourceManager.GetString(nameof(App_RemoveSolutionFolder), _resourceCulture)!;

        internal static string App_SelectImportFolder
            => ResourceManager.GetString(nameof(App_SelectImportFolder), _resourceCulture)!;

        internal static string App_OpenSolutionProject
            => ResourceManager.GetString(nameof(App_OpenSolutionProject), _resourceCulture)!;

        internal static string App_OpenFolder
            => ResourceManager.GetString(nameof(App_OpenFolder), _resourceCulture)!;

        internal static string App_FailedCreateSolution
            => ResourceManager.GetString(nameof(App_FailedCreateSolution), _resourceCulture)!;

        internal static string App_FailedOpenSolution
            => ResourceManager.GetString(nameof(App_FailedOpenSolution), _resourceCulture)!;

        internal static string App_RenameTitle
            => ResourceManager.GetString(nameof(App_RenameTitle), _resourceCulture)!;

        internal static string App_Error
            => ResourceManager.GetString(nameof(App_Error), _resourceCulture)!;

        internal static string App_RemoveFolderMessage
            => ResourceManager.GetString(nameof(App_RemoveFolderMessage), _resourceCulture)!;

        internal static string App_RemoveSolutionFolderMessage
            => ResourceManager.GetString(nameof(App_RemoveSolutionFolderMessage), _resourceCulture)!;

        internal static string App_ImportIntoProject
            => ResourceManager.GetString(nameof(App_ImportIntoProject), _resourceCulture)!;

        internal static string App_ImportIntoProjectMessage
            => ResourceManager.GetString(nameof(App_ImportIntoProjectMessage), _resourceCulture)!;

        internal static string App_FailedCreateProject
            => ResourceManager.GetString(nameof(App_FailedCreateProject), _resourceCulture)!;

        internal static string App_FailedCreateFile
            => ResourceManager.GetString(nameof(App_FailedCreateFile), _resourceCulture)!;

        internal static string App_FailedLoadLayout
            => ResourceManager.GetString(nameof(App_FailedLoadLayout), _resourceCulture)!;

        internal static string App_CompareWithHead
            => ResourceManager.GetString(nameof(App_CompareWithHead), _resourceCulture)!;

        internal static string App_CompareWithHeadNoRepo
            => ResourceManager.GetString(nameof(App_CompareWithHeadNoRepo), _resourceCulture)!;

        internal static string App_CompareWithHeadNoVersion
            => ResourceManager.GetString(nameof(App_CompareWithHeadNoVersion), _resourceCulture)!;

        internal static string App_SelectEntropyFile
            => ResourceManager.GetString(nameof(App_SelectEntropyFile), _resourceCulture)!;

        internal static string App_UpgradeMessagePattern
            => ResourceManager.GetString(nameof(App_UpgradeMessagePattern), _resourceCulture)!;

        internal static string App_UpgradeFailedMessage
            => ResourceManager.GetString(nameof(App_UpgradeFailedMessage), _resourceCulture)!;

        internal static string App_PanelOptions
            => ResourceManager.GetString(nameof(App_PanelOptions), _resourceCulture)!;

        internal static string App_PanelFormatCatalog
            => ResourceManager.GetString(nameof(App_PanelFormatCatalog), _resourceCulture)!;

        internal static string App_SaveAs
            => ResourceManager.GetString(nameof(App_SaveAs), _resourceCulture)!;

        internal static string App_AddExistingItem
            => ResourceManager.GetString(nameof(App_AddExistingItem), _resourceCulture)!;

        internal static string App_FailedWriteTblx
            => ResourceManager.GetString(nameof(App_FailedWriteTblx), _resourceCulture)!;

        internal static string App_InfoBar_Disable
            => ResourceManager.GetString(nameof(App_InfoBar_Disable), _resourceCulture)!;

        internal static string App_InfoBar_Restart
            => ResourceManager.GetString(nameof(App_InfoBar_Restart), _resourceCulture)!;

        internal static string App_InfoBar_Ignore
            => ResourceManager.GetString(nameof(App_InfoBar_Ignore), _resourceCulture)!;

        internal static string App_InfoBar_Reload
            => ResourceManager.GetString(nameof(App_InfoBar_Reload), _resourceCulture)!;

        internal static string App_InfoBar_KeepEdits
            => ResourceManager.GetString(nameof(App_InfoBar_KeepEdits), _resourceCulture)!;
    }
}
