//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexEditor.App.AssemblyExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AssemblyExplorerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssemblyExplorerResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexEditor.App.AssemblyExplorer.Properties.AssemblyExplorerResources", typeof(AssemblyExplorerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatically analyze file when opened in HexEditor.
        /// </summary>
        internal static string AE_AutoAnalyzeOption {
            get {
                return ResourceManager.GetString("AE_AutoAnalyzeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decompiler backend:.
        /// </summary>
        internal static string AE_BackendLabel {
            get {
                return ResourceManager.GetString("AE_BackendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Behaviour.
        /// </summary>
        internal static string AE_BehaviourSection {
            get {
                return ResourceManager.GetString("AE_BehaviourSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear All Recent.
        /// </summary>
        internal static string AE_ClearRecentButton {
            get {
                return ResourceManager.GetString("AE_ClearRecentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decompile language:.
        /// </summary>
        internal static string AE_DecompileLangLabel {
            get {
                return ResourceManager.GetString("AE_DecompileLangLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decompiler.
        /// </summary>
        internal static string AE_DecompilerSection {
            get {
                return ResourceManager.GetString("AE_DecompilerSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detail pane font size:.
        /// </summary>
        internal static string AE_DetailFontSizeLabel {
            get {
                return ResourceManager.GetString("AE_DetailFontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full (ILSpy + XML docs).
        /// </summary>
        internal static string AE_FullQuality {
            get {
                return ResourceManager.GetString("AE_FullQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ILSpy engine.
        /// </summary>
        internal static string AE_ILSpyOption {
            get {
                return ResourceManager.GetString("AE_ILSpyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inherit IDE global theme.
        /// </summary>
        internal static string AE_InheritThemeOption {
            get {
                return ResourceManager.GetString("AE_InheritThemeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C# language version:.
        /// </summary>
        internal static string AE_LangVersionLabel {
            get {
                return ResourceManager.GetString("AE_LangVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max loaded assemblies:.
        /// </summary>
        internal static string AE_MaxAssembliesLabel {
            get {
                return ResourceManager.GetString("AE_MaxAssembliesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (1 – 500).
        /// </summary>
        internal static string AE_MaxAssembliesRange {
            get {
                return ResourceManager.GetString("AE_MaxAssembliesRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Normal (ILSpy, no docs).
        /// </summary>
        internal static string AE_NormalQuality {
            get {
                return ResourceManager.GetString("AE_NormalQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable PDB integration (source mapping, local variable names).
        /// </summary>
        internal static string AE_PdbIntegration {
            get {
                return ResourceManager.GetString("AE_PdbIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pin loaded assemblies across active editor changes.
        /// </summary>
        internal static string AE_PinAssembliesOption {
            get {
                return ResourceManager.GetString("AE_PinAssembliesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decompilation quality:.
        /// </summary>
        internal static string AE_QualityLabel {
            get {
                return ResourceManager.GetString("AE_QualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recent Assemblies.
        /// </summary>
        internal static string AE_RecentSection {
            get {
                return ResourceManager.GetString("AE_RecentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show hidden (compiler-generated) members.
        /// </summary>
        internal static string AE_ShowHiddenMembers {
            get {
                return ResourceManager.GetString("AE_ShowHiddenMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show inherited members in type nodes.
        /// </summary>
        internal static string AE_ShowInheritedOption {
            get {
                return ResourceManager.GetString("AE_ShowInheritedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Metadata Tables group in the tree.
        /// </summary>
        internal static string AE_ShowMetadataOption {
            get {
                return ResourceManager.GetString("AE_ShowMetadataOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show non-public members (private, internal, protected).
        /// </summary>
        internal static string AE_ShowNonPublicOption {
            get {
                return ResourceManager.GetString("AE_ShowNonPublicOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Resources group in the tree.
        /// </summary>
        internal static string AE_ShowResourcesOption {
            get {
                return ResourceManager.GetString("AE_ShowResourcesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show XML documentation comments in decompiled output.
        /// </summary>
        internal static string AE_ShowXmlDocs {
            get {
                return ResourceManager.GetString("AE_ShowXmlDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skeleton (BCL-only stubs).
        /// </summary>
        internal static string AE_SkeletonOption {
            get {
                return ResourceManager.GetString("AE_SkeletonOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skeleton (fast, BCL stubs).
        /// </summary>
        internal static string AE_SkeletonQuality {
            get {
                return ResourceManager.GetString("AE_SkeletonQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sync HexEditor cursor when selecting a tree node.
        /// </summary>
        internal static string AE_SyncCursorOption {
            get {
                return ResourceManager.GetString("AE_SyncCursorOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analysis cancelled..
        /// </summary>
        internal static string AsmExplorer_AnalysisCancelled {
            get {
                return ResourceManager.GetString("AsmExplorer_AnalysisCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assembly path — type, paste (Ctrl+V) or drag a .dll / .exe.
        /// </summary>
        internal static string AsmExplorer_AssemblyPathHint {
            get {
                return ResourceManager.GetString("AsmExplorer_AssemblyPathHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Baseline:.
        /// </summary>
        internal static string AsmExplorer_BaselineLabel {
            get {
                return ResourceManager.GetString("AsmExplorer_BaselineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Baseline.
        /// </summary>
        internal static string AsmExplorer_BaselineTab {
            get {
                return ResourceManager.GetString("AsmExplorer_BaselineTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse….
        /// </summary>
        internal static string AsmExplorer_BrowseButton {
            get {
                return ResourceManager.GetString("AsmExplorer_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Building CFG….
        /// </summary>
        internal static string AsmExplorer_BuildingCfg {
            get {
                return ResourceManager.GetString("AsmExplorer_BuildingCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string AsmExplorer_Cancel {
            get {
                return ResourceManager.GetString("AsmExplorer_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à // Select a method node to view the Control Flow Graph..
        /// </summary>
        internal static string AsmExplorer_CfgPlaceholder {
            get {
                return ResourceManager.GetString("AsmExplorer_CfgPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear filter.
        /// </summary>
        internal static string AsmExplorer_ClearFilter {
            get {
                return ResourceManager.GetString("AsmExplorer_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear results.
        /// </summary>
        internal static string AsmExplorer_ClearResults {
            get {
                return ResourceManager.GetString("AsmExplorer_ClearResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear results.
        /// </summary>
        internal static string AsmExplorer_ClearResultsDiff {
            get {
                return ResourceManager.GetString("AsmExplorer_ClearResultsDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close All Assemblies.
        /// </summary>
        internal static string AsmExplorer_CloseAllAssemblies {
            get {
                return ResourceManager.GetString("AsmExplorer_CloseAllAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unload all assemblies from the workspace.
        /// </summary>
        internal static string AsmExplorer_CloseAllTooltip {
            get {
                return ResourceManager.GetString("AsmExplorer_CloseAllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close all assemblies.
        /// </summary>
        internal static string AsmExplorer_CloseAllTooltip2 {
            get {
                return ResourceManager.GetString("AsmExplorer_CloseAllTooltip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close Assembly.
        /// </summary>
        internal static string AsmExplorer_CloseAssembly {
            get {
                return ResourceManager.GetString("AsmExplorer_CloseAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assembly.
        /// </summary>
        internal static string AsmExplorer_ColAssembly {
            get {
                return ResourceManager.GetString("AsmExplorer_ColAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change.
        /// </summary>
        internal static string AsmExplorer_ColChange {
            get {
                return ResourceManager.GetString("AsmExplorer_ColChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Col.
        /// </summary>
        internal static string AsmExplorer_ColCol {
            get {
                return ResourceManager.GetString("AsmExplorer_ColCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IL Offset.
        /// </summary>
        internal static string AsmExplorer_ColILOffset {
            get {
                return ResourceManager.GetString("AsmExplorer_ColILOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kind.
        /// </summary>
        internal static string AsmExplorer_ColKind {
            get {
                return ResourceManager.GetString("AsmExplorer_ColKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collapse All.
        /// </summary>
        internal static string AsmExplorer_CollapseAll {
            get {
                return ResourceManager.GetString("AsmExplorer_CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collapse all.
        /// </summary>
        internal static string AsmExplorer_CollapseAllPanel {
            get {
                return ResourceManager.GetString("AsmExplorer_CollapseAllPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collapse all nodes in the tree.
        /// </summary>
        internal static string AsmExplorer_CollapseAllTooltip {
            get {
                return ResourceManager.GetString("AsmExplorer_CollapseAllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Line.
        /// </summary>
        internal static string AsmExplorer_ColLine {
            get {
                return ResourceManager.GetString("AsmExplorer_ColLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Member.
        /// </summary>
        internal static string AsmExplorer_ColMember {
            get {
                return ResourceManager.GetString("AsmExplorer_ColMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Namespace.
        /// </summary>
        internal static string AsmExplorer_ColNamespace {
            get {
                return ResourceManager.GetString("AsmExplorer_ColNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source File.
        /// </summary>
        internal static string AsmExplorer_ColSourceFile {
            get {
                return ResourceManager.GetString("AsmExplorer_ColSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Token.
        /// </summary>
        internal static string AsmExplorer_ColToken {
            get {
                return ResourceManager.GetString("AsmExplorer_ColToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string AsmExplorer_ColType {
            get {
                return ResourceManager.GetString("AsmExplorer_ColType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compare.
        /// </summary>
        internal static string AsmExplorer_CompareButton {
            get {
                return ResourceManager.GetString("AsmExplorer_CompareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open the Diff panel with this assembly pre-selected as baseline.
        /// </summary>
        internal static string AsmExplorer_CompareTooltip {
            get {
                return ResourceManager.GetString("AsmExplorer_CompareTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compare with….
        /// </summary>
        internal static string AsmExplorer_CompareWith {
            get {
                return ResourceManager.GetString("AsmExplorer_CompareWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparing….
        /// </summary>
        internal static string AsmExplorer_Comparing {
            get {
                return ResourceManager.GetString("AsmExplorer_Comparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy Full Name.
        /// </summary>
        internal static string AsmExplorer_CopyFullName {
            get {
                return ResourceManager.GetString("AsmExplorer_CopyFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy IL Offset.
        /// </summary>
        internal static string AsmExplorer_CopyILOffset {
            get {
                return ResourceManager.GetString("AsmExplorer_CopyILOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy Name.
        /// </summary>
        internal static string AsmExplorer_CopyName {
            get {
                return ResourceManager.GetString("AsmExplorer_CopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decompile.
        /// </summary>
        internal static string AsmExplorer_DecompileMenu {
            get {
                return ResourceManager.GetString("AsmExplorer_DecompileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decompile to….
        /// </summary>
        internal static string AsmExplorer_DecompileTo {
            get {
                return ResourceManager.GetString("AsmExplorer_DecompileTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decompile and add .cs file to the loaded project.
        /// </summary>
        internal static string AsmExplorer_DecompileTooltip {
            get {
                return ResourceManager.GetString("AsmExplorer_DecompileTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assembly Diff.
        /// </summary>
        internal static string AsmExplorer_DiffPanelTitle {
            get {
                return ResourceManager.GetString("AsmExplorer_DiffPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .NET Runtimes.
        /// </summary>
        internal static string AsmExplorer_DotNetRuntimes {
            get {
                return ResourceManager.GetString("AsmExplorer_DotNetRuntimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drop a .dll or .exe anywhere.
        /// </summary>
        internal static string AsmExplorer_DropHint {
            get {
                return ResourceManager.GetString("AsmExplorer_DropHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expand all.
        /// </summary>
        internal static string AsmExplorer_ExpandAll {
            get {
                return ResourceManager.GetString("AsmExplorer_ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expand/Collapse.
        /// </summary>
        internal static string AsmExplorer_ExpandCollapseMenu {
            get {
                return ResourceManager.GetString("AsmExplorer_ExpandCollapseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose Output Folder.
        /// </summary>
        internal static string AsmExplorer_Export_BrowseTitle {
            get {
                return ResourceManager.GetString("AsmExplorer_Export_BrowseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string AsmExplorer_Export_CloseButton {
            get {
                return ResourceManager.GetString("AsmExplorer_Export_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        internal static string AsmExplorer_Export_ExportButton {
            get {
                return ResourceManager.GetString("AsmExplorer_Export_ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose an output folder..
        /// </summary>
        internal static string AsmExplorer_Export_NoFolderSelected {
            get {
                return ResourceManager.GetString("AsmExplorer_Export_NoFolderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Output folder:.
        /// </summary>
        internal static string AsmExplorer_Export_OutputFolderLabel {
            get {
                return ResourceManager.GetString("AsmExplorer_Export_OutputFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export cancelled..
        /// </summary>
        internal static string AsmExplorer_ExportCancelled {
            get {
                return ResourceManager.GetString("AsmExplorer_ExportCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export C#.
        /// </summary>
        internal static string AsmExplorer_ExportCS {
            get {
                return ResourceManager.GetString("AsmExplorer_ExportCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export IL.
        /// </summary>
        internal static string AsmExplorer_ExportIL {
            get {
                return ResourceManager.GetString("AsmExplorer_ExportIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extract.
        /// </summary>
        internal static string AsmExplorer_Extract {
            get {
                return ResourceManager.GetString("AsmExplorer_Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extract decompiled code to the loaded project.
        /// </summary>
        internal static string AsmExplorer_ExtractCode {
            get {
                return ResourceManager.GetString("AsmExplorer_ExtractCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extract to Project….
        /// </summary>
        internal static string AsmExplorer_ExtractToProject {
            get {
                return ResourceManager.GetString("AsmExplorer_ExtractToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter assemblies by name.
        /// </summary>
        internal static string AsmExplorer_FilterAssemblies {
            get {
                return ResourceManager.GetString("AsmExplorer_FilterAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter results by change kind.
        /// </summary>
        internal static string AsmExplorer_FilterByChange {
            get {
                return ResourceManager.GetString("AsmExplorer_FilterByChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter by type kind.
        /// </summary>
        internal static string AsmExplorer_FilterByKind {
            get {
                return ResourceManager.GetString("AsmExplorer_FilterByKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter.
        /// </summary>
        internal static string AsmExplorer_FilterMenu {
            get {
                return ResourceManager.GetString("AsmExplorer_FilterMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter types….
        /// </summary>
        internal static string AsmExplorer_FilterTypes {
            get {
                return ResourceManager.GetString("AsmExplorer_FilterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to Source.
        /// </summary>
        internal static string AsmExplorer_GoToSource {
            get {
                return ResourceManager.GetString("AsmExplorer_GoToSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Highlight in Hex Editor.
        /// </summary>
        internal static string AsmExplorer_HighlightInHex {
            get {
                return ResourceManager.GetString("AsmExplorer_HighlightInHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à // Select a method node to view IL disassembly..
        /// </summary>
        internal static string AsmExplorer_ILPlaceholder {
            get {
                return ResourceManager.GetString("AsmExplorer_ILPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Include methods, fields, properties, events in results.
        /// </summary>
        internal static string AsmExplorer_IncludeMembers {
            get {
                return ResourceManager.GetString("AsmExplorer_IncludeMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading assembly....
        /// </summary>
        internal static string AsmExplorer_LoadingAssembly {
            get {
                return ResourceManager.GetString("AsmExplorer_LoadingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Members.
        /// </summary>
        internal static string AsmExplorer_MembersLabel {
            get {
                return ResourceManager.GetString("AsmExplorer_MembersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à More options.
        /// </summary>
        internal static string AsmExplorer_MoreOptions {
            get {
                return ResourceManager.GetString("AsmExplorer_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à More toolbar options.
        /// </summary>
        internal static string AsmExplorer_MoreToolbarOptions {
            get {
                return ResourceManager.GetString("AsmExplorer_MoreToolbarOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No assembly loaded.
        /// </summary>
        internal static string AsmExplorer_NoAssemblyLoaded {
            get {
                return ResourceManager.GetString("AsmExplorer_NoAssemblyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No portable PDB found next to the assembly..
        /// </summary>
        internal static string AsmExplorer_NoPdb {
            get {
                return ResourceManager.GetString("AsmExplorer_NoPdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à // No portable PDB found for this method..
        /// </summary>
        internal static string AsmExplorer_NoPdbMethod {
            get {
                return ResourceManager.GetString("AsmExplorer_NoPdbMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No recent assemblies.
        /// </summary>
        internal static string AsmExplorer_NoRecentAssemblies {
            get {
                return ResourceManager.GetString("AsmExplorer_NoRecentAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No results — type a search term above..
        /// </summary>
        internal static string AsmExplorer_NoResults {
            get {
                return ResourceManager.GetString("AsmExplorer_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No installed .NET runtimes found.
        /// </summary>
        internal static string AsmExplorer_NoRuntimes {
            get {
                return ResourceManager.GetString("AsmExplorer_NoRuntimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Assembly.
        /// </summary>
        internal static string AsmExplorer_OpenAssembly {
            get {
                return ResourceManager.GetString("AsmExplorer_OpenAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Assembly File in Hex Editor.
        /// </summary>
        internal static string AsmExplorer_OpenAssemblyInHex {
            get {
                return ResourceManager.GetString("AsmExplorer_OpenAssemblyInHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Assembly.
        /// </summary>
        internal static string AsmExplorer_OpenAssemblyTitle {
            get {
                return ResourceManager.GetString("AsmExplorer_OpenAssemblyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Assembly… (Ctrl+O).
        /// </summary>
        internal static string AsmExplorer_OpenAssemblyTooltip {
            get {
                return ResourceManager.GetString("AsmExplorer_OpenAssemblyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open in Code Editor.
        /// </summary>
        internal static string AsmExplorer_OpenInCodeEditor {
            get {
                return ResourceManager.GetString("AsmExplorer_OpenInCodeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open assembly file in hex editor and navigate to this member&apos;s byte range.
        /// </summary>
        internal static string AsmExplorer_OpenInHexTooltip {
            get {
                return ResourceManager.GetString("AsmExplorer_OpenInHexTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open local source file in the text editor.
        /// </summary>
        internal static string AsmExplorer_OpenLocalSource {
            get {
                return ResourceManager.GetString("AsmExplorer_OpenLocalSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open the raw assembly bytes in the hex editor (no navigation).
        /// </summary>
        internal static string AsmExplorer_OpenRawBytes {
            get {
                return ResourceManager.GetString("AsmExplorer_OpenRawBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open in browser via SourceLink.
        /// </summary>
        internal static string AsmExplorer_OpenSourceLink {
            get {
                return ResourceManager.GetString("AsmExplorer_OpenSourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assembly Explorer.
        /// </summary>
        internal static string AsmExplorer_PanelTitle {
            get {
                return ResourceManager.GetString("AsmExplorer_PanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pin Assembly.
        /// </summary>
        internal static string AsmExplorer_PinAssembly {
            get {
                return ResourceManager.GetString("AsmExplorer_PinAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pinned — this assembly will not be evicted automatically.
        /// </summary>
        internal static string AsmExplorer_Pinned {
            get {
                return ResourceManager.GetString("AsmExplorer_Pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pin this assembly so it is not evicted when the active file changes.
        /// </summary>
        internal static string AsmExplorer_PinTooltip {
            get {
                return ResourceManager.GetString("AsmExplorer_PinTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assembly Explorer.
        /// </summary>
        internal static string AsmExplorer_PluginName {
            get {
                return ResourceManager.GetString("AsmExplorer_PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Public.
        /// </summary>
        internal static string AsmExplorer_PublicLabel {
            get {
                return ResourceManager.GetString("AsmExplorer_PublicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show public members only.
        /// </summary>
        internal static string AsmExplorer_PublicOnly {
            get {
                return ResourceManager.GetString("AsmExplorer_PublicOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reading PDB….
        /// </summary>
        internal static string AsmExplorer_ReadingPdb {
            get {
                return ResourceManager.GetString("AsmExplorer_ReadingPdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recent.
        /// </summary>
        internal static string AsmExplorer_RecentLabel {
            get {
                return ResourceManager.GetString("AsmExplorer_RecentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove from recent list.
        /// </summary>
        internal static string AsmExplorer_RemoveFromRecent {
            get {
                return ResourceManager.GetString("AsmExplorer_RemoveFromRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run diff comparison.
        /// </summary>
        internal static string AsmExplorer_RunDiff {
            get {
                return ResourceManager.GetString("AsmExplorer_RunDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run search (Enter).
        /// </summary>
        internal static string AsmExplorer_RunSearch {
            get {
                return ResourceManager.GetString("AsmExplorer_RunSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scanning XRefs….
        /// </summary>
        internal static string AsmExplorer_ScanningXRefs {
            get {
                return ResourceManager.GetString("AsmExplorer_ScanningXRefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        internal static string AsmExplorer_SearchButton {
            get {
                return ResourceManager.GetString("AsmExplorer_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Searching….
        /// </summary>
        internal static string AsmExplorer_Searching {
            get {
                return ResourceManager.GetString("AsmExplorer_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assembly Search.
        /// </summary>
        internal static string AsmExplorer_SearchPanelTitle {
            get {
                return ResourceManager.GetString("AsmExplorer_SearchPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search types and members....
        /// </summary>
        internal static string AsmExplorer_SearchPlaceholder {
            get {
                return ResourceManager.GetString("AsmExplorer_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search types and members across all loaded assemblies.
        /// </summary>
        internal static string AsmExplorer_SearchTooltip {
            get {
                return ResourceManager.GetString("AsmExplorer_SearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the baseline (left) assembly.
        /// </summary>
        internal static string AsmExplorer_SelectBaseline {
            get {
                return ResourceManager.GetString("AsmExplorer_SelectBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a method node to view source information..
        /// </summary>
        internal static string AsmExplorer_SelectMethod {
            get {
                return ResourceManager.GetString("AsmExplorer_SelectMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the project to add the decompiled file to:.
        /// </summary>
        internal static string AsmExplorer_SelectProject {
            get {
                return ResourceManager.GetString("AsmExplorer_SelectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the target (right) assembly.
        /// </summary>
        internal static string AsmExplorer_SelectTarget {
            get {
                return ResourceManager.GetString("AsmExplorer_SelectTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show in Metadata Tables.
        /// </summary>
        internal static string AsmExplorer_ShowInMetadata {
            get {
                return ResourceManager.GetString("AsmExplorer_ShowInMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show/hide Metadata Tables.
        /// </summary>
        internal static string AsmExplorer_ShowMetadata {
            get {
                return ResourceManager.GetString("AsmExplorer_ShowMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show/hide References.
        /// </summary>
        internal static string AsmExplorer_ShowReferences {
            get {
                return ResourceManager.GetString("AsmExplorer_ShowReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show/hide Resources.
        /// </summary>
        internal static string AsmExplorer_ShowResources {
            get {
                return ResourceManager.GetString("AsmExplorer_ShowResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort alphabetically (off = sort by PE offset).
        /// </summary>
        internal static string AsmExplorer_SortAlpha {
            get {
                return ResourceManager.GetString("AsmExplorer_SortAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort.
        /// </summary>
        internal static string AsmExplorer_SortMenu {
            get {
                return ResourceManager.GetString("AsmExplorer_SortMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SourceLink.
        /// </summary>
        internal static string AsmExplorer_SourceLink {
            get {
                return ResourceManager.GetString("AsmExplorer_SourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sync selection with HexEditor.
        /// </summary>
        internal static string AsmExplorer_SyncHexEditor {
            get {
                return ResourceManager.GetString("AsmExplorer_SyncHexEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sync.
        /// </summary>
        internal static string AsmExplorer_SyncMenu {
            get {
                return ResourceManager.GetString("AsmExplorer_SyncMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CFG.
        /// </summary>
        internal static string AsmExplorer_TabCfg {
            get {
                return ResourceManager.GetString("AsmExplorer_TabCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code.
        /// </summary>
        internal static string AsmExplorer_TabCode {
            get {
                return ResourceManager.GetString("AsmExplorer_TabCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hex.
        /// </summary>
        internal static string AsmExplorer_TabHex {
            get {
                return ResourceManager.GetString("AsmExplorer_TabHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IL.
        /// </summary>
        internal static string AsmExplorer_TabIL {
            get {
                return ResourceManager.GetString("AsmExplorer_TabIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Info.
        /// </summary>
        internal static string AsmExplorer_TabInfo {
            get {
                return ResourceManager.GetString("AsmExplorer_TabInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        internal static string AsmExplorer_TabSource {
            get {
                return ResourceManager.GetString("AsmExplorer_TabSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XRefs.
        /// </summary>
        internal static string AsmExplorer_TabXRefs {
            get {
                return ResourceManager.GetString("AsmExplorer_TabXRefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target:.
        /// </summary>
        internal static string AsmExplorer_TargetLabel {
            get {
                return ResourceManager.GetString("AsmExplorer_TargetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target.
        /// </summary>
        internal static string AsmExplorer_TargetTab {
            get {
                return ResourceManager.GetString("AsmExplorer_TargetTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unified Diff.
        /// </summary>
        internal static string AsmExplorer_UnifiedDiff {
            get {
                return ResourceManager.GetString("AsmExplorer_UnifiedDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visibility.
        /// </summary>
        internal static string AsmExplorer_VisibilityMenu {
            get {
                return ResourceManager.GetString("AsmExplorer_VisibilityMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à // Select a method or field node to view cross-references..
        /// </summary>
        internal static string AsmExplorer_XRefsPlaceholder {
            get {
                return ResourceManager.GetString("AsmExplorer_XRefsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Offset.
        /// </summary>
        internal static string Common_ColOffset {
            get {
                return ResourceManager.GetString("Common_ColOffset", resourceCulture);
            }
        }
    }
}
