///////////////////////////////////////////////////////////////
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// GNU Affero General Public License v3.0  2026
// Author : Derek Tremblay (derektremblay666@gmail.com)
// Contributors: Claude Sonnet 4.6
// Project     : WpfHexEditor.Shell.Panels
// File        : ShellPanelsResources.Designer.cs
// Description : Strongly-typed accessor for ShellPanelsResources.resx.
///////////////////////////////////////////////////////////////

using System.Globalization;
using System.Resources;

namespace WpfHexEditor.Shell.Panels.Properties;

/// <summary>
/// Strongly-typed resource accessor for ShellPanelsResources.resx.
/// </summary>
internal static class ShellPanelsResources
{
    private static ResourceManager? _resourceManager;
    private static CultureInfo? _resourceCulture;

    /// <summary>
    /// Returns the cached <see cref="ResourceManager"/> for this resource class.
    /// </summary>
    internal static ResourceManager ResourceManager
    {
        get
        {
            _resourceManager ??= new ResourceManager(
                "WpfHexEditor.Shell.Panels.Properties.ShellPanelsResources",
                typeof(ShellPanelsResources).Assembly);
            return _resourceManager;
        }
    }

    /// <summary>
    /// Overrides the culture used for resource lookup.
    /// Pass <see langword="null"/> to use the current thread's UI culture.
    /// </summary>
    internal static CultureInfo? Culture
    {
        get => _resourceCulture;
        set => _resourceCulture = value;
    }

    private static string GetString(string name) =>
        ResourceManager.GetString(name, _resourceCulture) ?? name;

    // ═══════════════════════════════════════════════════════════════
    // BOOKMARKS PANEL
    // ═══════════════════════════════════════════════════════════════

    internal static string BookmarksPanel_RefreshToolTip      => GetString(nameof(BookmarksPanel_RefreshToolTip));
    internal static string BookmarksPanel_ClearAllToolTip     => GetString(nameof(BookmarksPanel_ClearAllToolTip));
    internal static string BookmarksPanel_EmptyCount          => GetString(nameof(BookmarksPanel_EmptyCount));
    internal static string BookmarksPanel_OffsetHeader        => GetString(nameof(BookmarksPanel_OffsetHeader));
    internal static string BookmarksPanel_DescriptionHeader   => GetString(nameof(BookmarksPanel_DescriptionHeader));
    internal static string BookmarksPanel_CategoryHeader      => GetString(nameof(BookmarksPanel_CategoryHeader));
    internal static string BookmarksPanel_EmptyMessage        => GetString(nameof(BookmarksPanel_EmptyMessage));

    // ═══════════════════════════════════════════════════════════════
    // ERROR PANEL
    // ═══════════════════════════════════════════════════════════════

    internal static string ErrorPanel_ScopeEntireSolution     => GetString(nameof(ErrorPanel_ScopeEntireSolution));
    internal static string ErrorPanel_ScopeCurrentProject     => GetString(nameof(ErrorPanel_ScopeCurrentProject));
    internal static string ErrorPanel_ScopeCurrentDocument    => GetString(nameof(ErrorPanel_ScopeCurrentDocument));
    internal static string ErrorPanel_ScopeOpenDocuments      => GetString(nameof(ErrorPanel_ScopeOpenDocuments));
    internal static string ErrorPanel_ScopeChangedDocuments   => GetString(nameof(ErrorPanel_ScopeChangedDocuments));
    internal static string ErrorPanel_OverflowButtonToolTip   => GetString(nameof(ErrorPanel_OverflowButtonToolTip));
    internal static string ErrorPanel_ShowErrorsMenu          => GetString(nameof(ErrorPanel_ShowErrorsMenu));
    internal static string ErrorPanel_ShowWarningsMenu        => GetString(nameof(ErrorPanel_ShowWarningsMenu));
    internal static string ErrorPanel_ShowMessagesMenu        => GetString(nameof(ErrorPanel_ShowMessagesMenu));
    internal static string ErrorPanel_SearchPlaceholder       => GetString(nameof(ErrorPanel_SearchPlaceholder));
    internal static string ErrorPanel_ErrorToggleToolTip      => GetString(nameof(ErrorPanel_ErrorToggleToolTip));
    internal static string ErrorPanel_ErrorCountText          => GetString(nameof(ErrorPanel_ErrorCountText));
    internal static string ErrorPanel_WarningToggleToolTip    => GetString(nameof(ErrorPanel_WarningToggleToolTip));
    internal static string ErrorPanel_WarningCountText        => GetString(nameof(ErrorPanel_WarningCountText));
    internal static string ErrorPanel_MessageToggleToolTip    => GetString(nameof(ErrorPanel_MessageToggleToolTip));
    internal static string ErrorPanel_MessageCountText        => GetString(nameof(ErrorPanel_MessageCountText));
    internal static string ErrorPanel_CodeHeader              => GetString(nameof(ErrorPanel_CodeHeader));
    internal static string ErrorPanel_DescriptionHeader       => GetString(nameof(ErrorPanel_DescriptionHeader));
    internal static string ErrorPanel_ProjectHeader           => GetString(nameof(ErrorPanel_ProjectHeader));
    internal static string ErrorPanel_FileHeader              => GetString(nameof(ErrorPanel_FileHeader));
    internal static string ErrorPanel_OffsetHeader            => GetString(nameof(ErrorPanel_OffsetHeader));
    internal static string ErrorPanel_LineColHeader           => GetString(nameof(ErrorPanel_LineColHeader));

    // ═══════════════════════════════════════════════════════════════
    // PROPERTIES PANEL
    // ═══════════════════════════════════════════════════════════════

    internal static string PropertiesPanel_ContextLabel          => GetString(nameof(PropertiesPanel_ContextLabel));
    internal static string PropertiesPanel_RefreshToolTip        => GetString(nameof(PropertiesPanel_RefreshToolTip));
    internal static string PropertiesPanel_OverflowToolTip       => GetString(nameof(PropertiesPanel_OverflowToolTip));
    internal static string PropertiesPanel_SortAlphabetically    => GetString(nameof(PropertiesPanel_SortAlphabetically));
    internal static string PropertiesPanel_CopyValue             => GetString(nameof(PropertiesPanel_CopyValue));
    internal static string PropertiesPanel_SortToggleToolTip     => GetString(nameof(PropertiesPanel_SortToggleToolTip));
    internal static string PropertiesPanel_CopyButtonToolTip     => GetString(nameof(PropertiesPanel_CopyButtonToolTip));
    internal static string PropertiesPanel_SearchPlaceholder     => GetString(nameof(PropertiesPanel_SearchPlaceholder));
    internal static string PropertiesPanel_OpenFolderToolTip     => GetString(nameof(PropertiesPanel_OpenFolderToolTip));
    internal static string PropertiesPanel_ThicknessLeft         => GetString(nameof(PropertiesPanel_ThicknessLeft));
    internal static string PropertiesPanel_ThicknessTop          => GetString(nameof(PropertiesPanel_ThicknessTop));
    internal static string PropertiesPanel_ThicknessRight        => GetString(nameof(PropertiesPanel_ThicknessRight));
    internal static string PropertiesPanel_ThicknessBottom       => GetString(nameof(PropertiesPanel_ThicknessBottom));
    internal static string PropertiesPanel_ThicknessLLabel       => GetString(nameof(PropertiesPanel_ThicknessLLabel));
    internal static string PropertiesPanel_ThicknessTLabel       => GetString(nameof(PropertiesPanel_ThicknessTLabel));
    internal static string PropertiesPanel_ThicknessRLabel       => GetString(nameof(PropertiesPanel_ThicknessRLabel));
    internal static string PropertiesPanel_ThicknessBLabel       => GetString(nameof(PropertiesPanel_ThicknessBLabel));
    internal static string PropertiesPanel_ContextMenu_CopyValue => GetString(nameof(PropertiesPanel_ContextMenu_CopyValue));
    internal static string PropertiesPanel_ContextMenu_CopyName  => GetString(nameof(PropertiesPanel_ContextMenu_CopyName));
    internal static string PropertiesPanel_ResetToDefaultToolTip => GetString(nameof(PropertiesPanel_ResetToDefaultToolTip));

    // ═══════════════════════════════════════════════════════════════
    // SOLUTION EXPLORER PANEL
    // ═══════════════════════════════════════════════════════════════

    internal static string SolutionExplorer_ShowAllFilesToolTip          => GetString(nameof(SolutionExplorer_ShowAllFilesToolTip));
    internal static string SolutionExplorer_CollapseAllToolTip           => GetString(nameof(SolutionExplorer_CollapseAllToolTip));
    internal static string SolutionExplorer_SyncWithActiveDocToolTip     => GetString(nameof(SolutionExplorer_SyncWithActiveDocToolTip));
    internal static string SolutionExplorer_RefreshToolTip               => GetString(nameof(SolutionExplorer_RefreshToolTip));
    internal static string SolutionExplorer_SortToolTip                  => GetString(nameof(SolutionExplorer_SortToolTip));
    internal static string SolutionExplorer_SortNone                     => GetString(nameof(SolutionExplorer_SortNone));
    internal static string SolutionExplorer_SortName                     => GetString(nameof(SolutionExplorer_SortName));
    internal static string SolutionExplorer_SortType                     => GetString(nameof(SolutionExplorer_SortType));
    internal static string SolutionExplorer_SortDateModified             => GetString(nameof(SolutionExplorer_SortDateModified));
    internal static string SolutionExplorer_SortSize                     => GetString(nameof(SolutionExplorer_SortSize));
    internal static string SolutionExplorer_FilterToolTip                => GetString(nameof(SolutionExplorer_FilterToolTip));
    internal static string SolutionExplorer_FilterAll                    => GetString(nameof(SolutionExplorer_FilterAll));
    internal static string SolutionExplorer_FilterBinary                 => GetString(nameof(SolutionExplorer_FilterBinary));
    internal static string SolutionExplorer_FilterText                   => GetString(nameof(SolutionExplorer_FilterText));
    internal static string SolutionExplorer_FilterImages                 => GetString(nameof(SolutionExplorer_FilterImages));
    internal static string SolutionExplorer_FilterLanguage               => GetString(nameof(SolutionExplorer_FilterLanguage));
    internal static string SolutionExplorer_SearchPlaceholder            => GetString(nameof(SolutionExplorer_SearchPlaceholder));
    internal static string SolutionExplorer_SearchModeFileName           => GetString(nameof(SolutionExplorer_SearchModeFileName));
    internal static string SolutionExplorer_SearchModeNameContent        => GetString(nameof(SolutionExplorer_SearchModeNameContent));
    internal static string SolutionExplorer_SearchModeContentOnly        => GetString(nameof(SolutionExplorer_SearchModeContentOnly));
    internal static string SolutionExplorer_SearchModeRegex              => GetString(nameof(SolutionExplorer_SearchModeRegex));
    internal static string SolutionExplorer_SolutionFolderTooltip        => GetString(nameof(SolutionExplorer_SolutionFolderTooltip));
    internal static string SolutionExplorer_PhysicalFolderTooltip        => GetString(nameof(SolutionExplorer_PhysicalFolderTooltip));
    internal static string SolutionExplorer_PropertiesFolderTooltip      => GetString(nameof(SolutionExplorer_PropertiesFolderTooltip));
    internal static string SolutionExplorer_BuildDirtyIndicator          => GetString(nameof(SolutionExplorer_BuildDirtyIndicator));
    internal static string SolutionExplorer_UnsavedModifications         => GetString(nameof(SolutionExplorer_UnsavedModifications));
    internal static string SolutionExplorer_ExternalFileIndicator        => GetString(nameof(SolutionExplorer_ExternalFileIndicator));
    internal static string SolutionExplorer_ExternalModIndicator         => GetString(nameof(SolutionExplorer_ExternalModIndicator));
    internal static string SolutionExplorer_LoadingIndicator             => GetString(nameof(SolutionExplorer_LoadingIndicator));
    internal static string SolutionExplorer_GoToDefinition               => GetString(nameof(SolutionExplorer_GoToDefinition));
    internal static string SolutionExplorer_Open                         => GetString(nameof(SolutionExplorer_Open));
    internal static string SolutionExplorer_OpenWith                     => GetString(nameof(SolutionExplorer_OpenWith));
    internal static string SolutionExplorer_OpenWithHexEditor            => GetString(nameof(SolutionExplorer_OpenWithHexEditor));
    internal static string SolutionExplorer_Add                          => GetString(nameof(SolutionExplorer_Add));
    internal static string SolutionExplorer_AddNewItem                   => GetString(nameof(SolutionExplorer_AddNewItem));
    internal static string SolutionExplorer_AddExistingItem              => GetString(nameof(SolutionExplorer_AddExistingItem));
    internal static string SolutionExplorer_ImportFormat                 => GetString(nameof(SolutionExplorer_ImportFormat));
    internal static string SolutionExplorer_ImportSyntax                 => GetString(nameof(SolutionExplorer_ImportSyntax));
    internal static string SolutionExplorer_NewFolder                    => GetString(nameof(SolutionExplorer_NewFolder));
    internal static string SolutionExplorer_NewSolutionFolder            => GetString(nameof(SolutionExplorer_NewSolutionFolder));
    internal static string SolutionExplorer_AddExistingFolder            => GetString(nameof(SolutionExplorer_AddExistingFolder));
    internal static string SolutionExplorer_IncludeInProject             => GetString(nameof(SolutionExplorer_IncludeInProject));
    internal static string SolutionExplorer_SetDefaultTbl                => GetString(nameof(SolutionExplorer_SetDefaultTbl));
    internal static string SolutionExplorer_ClearDefaultTbl              => GetString(nameof(SolutionExplorer_ClearDefaultTbl));
    internal static string SolutionExplorer_ConvertToTblx                => GetString(nameof(SolutionExplorer_ConvertToTblx));
    internal static string SolutionExplorer_ApplyTblToActive             => GetString(nameof(SolutionExplorer_ApplyTblToActive));
    internal static string SolutionExplorer_ApplyTblToAll                => GetString(nameof(SolutionExplorer_ApplyTblToAll));
    internal static string SolutionExplorer_OpenInExplorer               => GetString(nameof(SolutionExplorer_OpenInExplorer));
    internal static string SolutionExplorer_CopyPath                     => GetString(nameof(SolutionExplorer_CopyPath));
    internal static string SolutionExplorer_Copy                         => GetString(nameof(SolutionExplorer_Copy));
    internal static string SolutionExplorer_Cut                          => GetString(nameof(SolutionExplorer_Cut));
    internal static string SolutionExplorer_Paste                        => GetString(nameof(SolutionExplorer_Paste));
    internal static string SolutionExplorer_Rename                       => GetString(nameof(SolutionExplorer_Rename));
    internal static string SolutionExplorer_RemoveFromProject            => GetString(nameof(SolutionExplorer_RemoveFromProject));
    internal static string SolutionExplorer_Delete                       => GetString(nameof(SolutionExplorer_Delete));
    internal static string SolutionExplorer_ExcludeFromProject           => GetString(nameof(SolutionExplorer_ExcludeFromProject));
    internal static string SolutionExplorer_ImportIntoProject            => GetString(nameof(SolutionExplorer_ImportIntoProject));
    internal static string SolutionExplorer_ApplyToDisk                  => GetString(nameof(SolutionExplorer_ApplyToDisk));
    internal static string SolutionExplorer_DiscardChanges               => GetString(nameof(SolutionExplorer_DiscardChanges));
    internal static string SolutionExplorer_Build                        => GetString(nameof(SolutionExplorer_Build));
    internal static string SolutionExplorer_Rebuild                      => GetString(nameof(SolutionExplorer_Rebuild));
    internal static string SolutionExplorer_Clean                        => GetString(nameof(SolutionExplorer_Clean));
    internal static string SolutionExplorer_SetAsStartup                 => GetString(nameof(SolutionExplorer_SetAsStartup));
    internal static string SolutionExplorer_AddReference                 => GetString(nameof(SolutionExplorer_AddReference));
    internal static string SolutionExplorer_RemoveUnusedReferences       => GetString(nameof(SolutionExplorer_RemoveUnusedReferences));
    internal static string SolutionExplorer_ManageNugetPackages          => GetString(nameof(SolutionExplorer_ManageNugetPackages));
    internal static string SolutionExplorer_ManageNugetPackagesSolution  => GetString(nameof(SolutionExplorer_ManageNugetPackagesSolution));
    internal static string SolutionExplorer_Properties                   => GetString(nameof(SolutionExplorer_Properties));
    internal static string SolutionExplorer_SaveAll                      => GetString(nameof(SolutionExplorer_SaveAll));
    internal static string SolutionExplorer_CloseSolution                => GetString(nameof(SolutionExplorer_CloseSolution));

    // ═══════════════════════════════════════════════════════════════
    // WHFMT BROWSER PANEL
    // ═══════════════════════════════════════════════════════════════

    internal static string WhfmtBrowser_LoadFailureIndicator    => GetString(nameof(WhfmtBrowser_LoadFailureIndicator));
    internal static string WhfmtBrowser_OpenInEditorToolTip     => GetString(nameof(WhfmtBrowser_OpenInEditorToolTip));
    internal static string WhfmtBrowser_ExportToFileToolTip     => GetString(nameof(WhfmtBrowser_ExportToFileToolTip));
    internal static string WhfmtBrowser_ViewJsonToolTip         => GetString(nameof(WhfmtBrowser_ViewJsonToolTip));
    internal static string WhfmtBrowser_Open                    => GetString(nameof(WhfmtBrowser_Open));
    internal static string WhfmtBrowser_OpenReadOnly            => GetString(nameof(WhfmtBrowser_OpenReadOnly));
    internal static string WhfmtBrowser_ExportToFile            => GetString(nameof(WhfmtBrowser_ExportToFile));
    internal static string WhfmtBrowser_ViewJson                => GetString(nameof(WhfmtBrowser_ViewJson));
    internal static string WhfmtBrowser_CopyPath                => GetString(nameof(WhfmtBrowser_CopyPath));
    internal static string WhfmtBrowser_Delete                  => GetString(nameof(WhfmtBrowser_Delete));
    internal static string WhfmtBrowser_RevealInExplorer        => GetString(nameof(WhfmtBrowser_RevealInExplorer));
    internal static string WhfmtBrowser_DuplicateFormat         => GetString(nameof(WhfmtBrowser_DuplicateFormat));
    internal static string WhfmtBrowser_EditInCodeEditor        => GetString(nameof(WhfmtBrowser_EditInCodeEditor));

    // ═══════════════════════════════════════════════════════════════
    // WHFMT CATALOG DOCUMENT
    // ═══════════════════════════════════════════════════════════════

    internal static string WhfmtCatalog_NameHeader          => GetString(nameof(WhfmtCatalog_NameHeader));
    internal static string WhfmtCatalog_CategoryHeader      => GetString(nameof(WhfmtCatalog_CategoryHeader));
    internal static string WhfmtCatalog_ExtensionsHeader    => GetString(nameof(WhfmtCatalog_ExtensionsHeader));
    internal static string WhfmtCatalog_VersionHeader       => GetString(nameof(WhfmtCatalog_VersionHeader));
    internal static string WhfmtCatalog_QualityHeader       => GetString(nameof(WhfmtCatalog_QualityHeader));
    internal static string WhfmtCatalog_AuthorHeader        => GetString(nameof(WhfmtCatalog_AuthorHeader));
    internal static string WhfmtCatalog_SourceHeader        => GetString(nameof(WhfmtCatalog_SourceHeader));
    internal static string WhfmtCatalog_Open                => GetString(nameof(WhfmtCatalog_Open));
    internal static string WhfmtCatalog_OpenReadOnly        => GetString(nameof(WhfmtCatalog_OpenReadOnly));
    internal static string WhfmtCatalog_ExportToFile        => GetString(nameof(WhfmtCatalog_ExportToFile));
    internal static string WhfmtCatalog_ViewJson            => GetString(nameof(WhfmtCatalog_ViewJson));
    internal static string WhfmtCatalog_RevealInExplorer    => GetString(nameof(WhfmtCatalog_RevealInExplorer));
    internal static string WhfmtCatalog_ErrorText           => GetString(nameof(WhfmtCatalog_ErrorText));

    // ═══════════════════════════════════════════════════════════════
    // WHFMT FORMAT DETAIL PANEL
    // ═══════════════════════════════════════════════════════════════

    internal static string WhfmtDetail_EmptyPlaceholder              => GetString(nameof(WhfmtDetail_EmptyPlaceholder));
    internal static string WhfmtDetail_OpenInEditorToolTip           => GetString(nameof(WhfmtDetail_OpenInEditorToolTip));
    internal static string WhfmtDetail_ExportToFileToolTip           => GetString(nameof(WhfmtDetail_ExportToFileToolTip));
    internal static string WhfmtDetail_ViewRawJsonToolTip            => GetString(nameof(WhfmtDetail_ViewRawJsonToolTip));
    internal static string WhfmtDetail_RetryLoadToolTip              => GetString(nameof(WhfmtDetail_RetryLoadToolTip));
    internal static string WhfmtDetail_ExcludeFromCatalogToolTip     => GetString(nameof(WhfmtDetail_ExcludeFromCatalogToolTip));
    internal static string WhfmtDetail_FormatLoadedSuccessfully      => GetString(nameof(WhfmtDetail_FormatLoadedSuccessfully));
    internal static string WhfmtDetail_FormatLoadFailed              => GetString(nameof(WhfmtDetail_FormatLoadFailed));
    internal static string WhfmtDetail_OverviewTab                   => GetString(nameof(WhfmtDetail_OverviewTab));
    internal static string WhfmtDetail_VersionLabel                  => GetString(nameof(WhfmtDetail_VersionLabel));
    internal static string WhfmtDetail_AuthorLabel                   => GetString(nameof(WhfmtDetail_AuthorLabel));
    internal static string WhfmtDetail_CategoryLabel                 => GetString(nameof(WhfmtDetail_CategoryLabel));
    internal static string WhfmtDetail_PlatformLabel                 => GetString(nameof(WhfmtDetail_PlatformLabel));
    internal static string WhfmtDetail_EditorLabel                   => GetString(nameof(WhfmtDetail_EditorLabel));
    internal static string WhfmtDetail_DiffLabel                     => GetString(nameof(WhfmtDetail_DiffLabel));
    internal static string WhfmtDetail_StatusLabel                   => GetString(nameof(WhfmtDetail_StatusLabel));
    internal static string WhfmtDetail_ExtensionsLabel               => GetString(nameof(WhfmtDetail_ExtensionsLabel));
    internal static string WhfmtDetail_QualityScoreLabel             => GetString(nameof(WhfmtDetail_QualityScoreLabel));
    internal static string WhfmtDetail_DetectionLabel                => GetString(nameof(WhfmtDetail_DetectionLabel));
    internal static string WhfmtDetail_BlocksLabel                   => GetString(nameof(WhfmtDetail_BlocksLabel));
    internal static string WhfmtDetail_LoadErrorTitle                => GetString(nameof(WhfmtDetail_LoadErrorTitle));
    internal static string WhfmtDetail_ReferencesTab                 => GetString(nameof(WhfmtDetail_ReferencesTab));
    internal static string WhfmtDetail_SpecificationsLabel           => GetString(nameof(WhfmtDetail_SpecificationsLabel));
    internal static string WhfmtDetail_WebLinksLabel                 => GetString(nameof(WhfmtDetail_WebLinksLabel));
    internal static string WhfmtDetail_AssertionsTab                 => GetString(nameof(WhfmtDetail_AssertionsTab));
    internal static string WhfmtDetail_AIHintsTab                    => GetString(nameof(WhfmtDetail_AIHintsTab));
    internal static string WhfmtDetail_AnalysisContextLabel          => GetString(nameof(WhfmtDetail_AnalysisContextLabel));
    internal static string WhfmtDetail_KnownVulnerabilitiesLabel     => GetString(nameof(WhfmtDetail_KnownVulnerabilitiesLabel));
    internal static string WhfmtDetail_JsonTab                       => GetString(nameof(WhfmtDetail_JsonTab));
}
