//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexEditor.Shell.Panels.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShellPanelsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShellPanelsResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexEditor.Shell.Panels.Properties.ShellPanelsResources", typeof(ShellPanelsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Category.
        /// </summary>
        internal static string BookmarksPanel_CategoryHeader {
            get {
                return ResourceManager.GetString("BookmarksPanel_CategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear all bookmarks.
        /// </summary>
        internal static string BookmarksPanel_ClearAllToolTip {
            get {
                return ResourceManager.GetString("BookmarksPanel_ClearAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string BookmarksPanel_DescriptionHeader {
            get {
                return ResourceManager.GetString("BookmarksPanel_DescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0 bookmarks.
        /// </summary>
        internal static string BookmarksPanel_EmptyCount {
            get {
                return ResourceManager.GetString("BookmarksPanel_EmptyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No bookmarks. Press Ctrl+F2 to toggle a bookmark in the active editor..
        /// </summary>
        internal static string BookmarksPanel_EmptyMessage {
            get {
                return ResourceManager.GetString("BookmarksPanel_EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Offset.
        /// </summary>
        internal static string BookmarksPanel_OffsetHeader {
            get {
                return ResourceManager.GetString("BookmarksPanel_OffsetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh bookmarks.
        /// </summary>
        internal static string BookmarksPanel_RefreshToolTip {
            get {
                return ResourceManager.GetString("BookmarksPanel_RefreshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code.
        /// </summary>
        internal static string ErrorPanel_CodeHeader {
            get {
                return ResourceManager.GetString("ErrorPanel_CodeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string ErrorPanel_DescriptionHeader {
            get {
                return ResourceManager.GetString("ErrorPanel_DescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0 Errors.
        /// </summary>
        internal static string ErrorPanel_ErrorCountText {
            get {
                return ResourceManager.GetString("ErrorPanel_ErrorCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show/hide errors.
        /// </summary>
        internal static string ErrorPanel_ErrorToggleToolTip {
            get {
                return ResourceManager.GetString("ErrorPanel_ErrorToggleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File.
        /// </summary>
        internal static string ErrorPanel_FileHeader {
            get {
                return ResourceManager.GetString("ErrorPanel_FileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Line:Col.
        /// </summary>
        internal static string ErrorPanel_LineColHeader {
            get {
                return ResourceManager.GetString("ErrorPanel_LineColHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0 Messages.
        /// </summary>
        internal static string ErrorPanel_MessageCountText {
            get {
                return ResourceManager.GetString("ErrorPanel_MessageCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show/hide messages.
        /// </summary>
        internal static string ErrorPanel_MessageToggleToolTip {
            get {
                return ResourceManager.GetString("ErrorPanel_MessageToggleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Offset.
        /// </summary>
        internal static string ErrorPanel_OffsetHeader {
            get {
                return ResourceManager.GetString("ErrorPanel_OffsetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à More options.
        /// </summary>
        internal static string ErrorPanel_OverflowButtonToolTip {
            get {
                return ResourceManager.GetString("ErrorPanel_OverflowButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project.
        /// </summary>
        internal static string ErrorPanel_ProjectHeader {
            get {
                return ResourceManager.GetString("ErrorPanel_ProjectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changed Documents.
        /// </summary>
        internal static string ErrorPanel_ScopeChangedDocuments {
            get {
                return ResourceManager.GetString("ErrorPanel_ScopeChangedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current Document.
        /// </summary>
        internal static string ErrorPanel_ScopeCurrentDocument {
            get {
                return ResourceManager.GetString("ErrorPanel_ScopeCurrentDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current Project.
        /// </summary>
        internal static string ErrorPanel_ScopeCurrentProject {
            get {
                return ResourceManager.GetString("ErrorPanel_ScopeCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entire Solution.
        /// </summary>
        internal static string ErrorPanel_ScopeEntireSolution {
            get {
                return ResourceManager.GetString("ErrorPanel_ScopeEntireSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Documents.
        /// </summary>
        internal static string ErrorPanel_ScopeOpenDocuments {
            get {
                return ResourceManager.GetString("ErrorPanel_ScopeOpenDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search....
        /// </summary>
        internal static string ErrorPanel_SearchPlaceholder {
            get {
                return ResourceManager.GetString("ErrorPanel_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Errors.
        /// </summary>
        internal static string ErrorPanel_ShowErrorsMenu {
            get {
                return ResourceManager.GetString("ErrorPanel_ShowErrorsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Messages.
        /// </summary>
        internal static string ErrorPanel_ShowMessagesMenu {
            get {
                return ResourceManager.GetString("ErrorPanel_ShowMessagesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Warnings.
        /// </summary>
        internal static string ErrorPanel_ShowWarningsMenu {
            get {
                return ResourceManager.GetString("ErrorPanel_ShowWarningsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0 Warnings.
        /// </summary>
        internal static string ErrorPanel_WarningCountText {
            get {
                return ResourceManager.GetString("ErrorPanel_WarningCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show/hide warnings.
        /// </summary>
        internal static string ErrorPanel_WarningToggleToolTip {
            get {
                return ResourceManager.GetString("ErrorPanel_WarningToggleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Properties.
        /// </summary>
        internal static string PropertiesPanel_ContextLabel {
            get {
                return ResourceManager.GetString("PropertiesPanel_ContextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy Name.
        /// </summary>
        internal static string PropertiesPanel_ContextMenu_CopyName {
            get {
                return ResourceManager.GetString("PropertiesPanel_ContextMenu_CopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy Value.
        /// </summary>
        internal static string PropertiesPanel_ContextMenu_CopyValue {
            get {
                return ResourceManager.GetString("PropertiesPanel_ContextMenu_CopyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy selected property value.
        /// </summary>
        internal static string PropertiesPanel_CopyButtonToolTip {
            get {
                return ResourceManager.GetString("PropertiesPanel_CopyButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy Value.
        /// </summary>
        internal static string PropertiesPanel_CopyValue {
            get {
                return ResourceManager.GetString("PropertiesPanel_CopyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open containing folder in Explorer.
        /// </summary>
        internal static string PropertiesPanel_OpenFolderToolTip {
            get {
                return ResourceManager.GetString("PropertiesPanel_OpenFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à More options.
        /// </summary>
        internal static string PropertiesPanel_OverflowToolTip {
            get {
                return ResourceManager.GetString("PropertiesPanel_OverflowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh properties.
        /// </summary>
        internal static string PropertiesPanel_RefreshToolTip {
            get {
                return ResourceManager.GetString("PropertiesPanel_RefreshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset to default.
        /// </summary>
        internal static string PropertiesPanel_ResetToDefaultToolTip {
            get {
                return ResourceManager.GetString("PropertiesPanel_ResetToDefaultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter properties….
        /// </summary>
        internal static string PropertiesPanel_SearchPlaceholder {
            get {
                return ResourceManager.GetString("PropertiesPanel_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort Alphabetically.
        /// </summary>
        internal static string PropertiesPanel_SortAlphabetically {
            get {
                return ResourceManager.GetString("PropertiesPanel_SortAlphabetically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort properties alphabetically.
        /// </summary>
        internal static string PropertiesPanel_SortToggleToolTip {
            get {
                return ResourceManager.GetString("PropertiesPanel_SortToggleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à B.
        /// </summary>
        internal static string PropertiesPanel_ThicknessBLabel {
            get {
                return ResourceManager.GetString("PropertiesPanel_ThicknessBLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bottom.
        /// </summary>
        internal static string PropertiesPanel_ThicknessBottom {
            get {
                return ResourceManager.GetString("PropertiesPanel_ThicknessBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left.
        /// </summary>
        internal static string PropertiesPanel_ThicknessLeft {
            get {
                return ResourceManager.GetString("PropertiesPanel_ThicknessLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L.
        /// </summary>
        internal static string PropertiesPanel_ThicknessLLabel {
            get {
                return ResourceManager.GetString("PropertiesPanel_ThicknessLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right.
        /// </summary>
        internal static string PropertiesPanel_ThicknessRight {
            get {
                return ResourceManager.GetString("PropertiesPanel_ThicknessRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à R.
        /// </summary>
        internal static string PropertiesPanel_ThicknessRLabel {
            get {
                return ResourceManager.GetString("PropertiesPanel_ThicknessRLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à T.
        /// </summary>
        internal static string PropertiesPanel_ThicknessTLabel {
            get {
                return ResourceManager.GetString("PropertiesPanel_ThicknessTLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Top.
        /// </summary>
        internal static string PropertiesPanel_ThicknessTop {
            get {
                return ResourceManager.GetString("PropertiesPanel_ThicknessTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string SolutionExplorer_Add {
            get {
                return ResourceManager.GetString("SolutionExplorer_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Existing Folder....
        /// </summary>
        internal static string SolutionExplorer_AddExistingFolder {
            get {
                return ResourceManager.GetString("SolutionExplorer_AddExistingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Existing Item....
        /// </summary>
        internal static string SolutionExplorer_AddExistingItem {
            get {
                return ResourceManager.GetString("SolutionExplorer_AddExistingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add New Item....
        /// </summary>
        internal static string SolutionExplorer_AddNewItem {
            get {
                return ResourceManager.GetString("SolutionExplorer_AddNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Reference….
        /// </summary>
        internal static string SolutionExplorer_AddReference {
            get {
                return ResourceManager.GetString("SolutionExplorer_AddReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply to Active Document.
        /// </summary>
        internal static string SolutionExplorer_ApplyTblToActive {
            get {
                return ResourceManager.GetString("SolutionExplorer_ApplyTblToActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply to All Documents.
        /// </summary>
        internal static string SolutionExplorer_ApplyTblToAll {
            get {
                return ResourceManager.GetString("SolutionExplorer_ApplyTblToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply to Disk.
        /// </summary>
        internal static string SolutionExplorer_ApplyToDisk {
            get {
                return ResourceManager.GetString("SolutionExplorer_ApplyToDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Build.
        /// </summary>
        internal static string SolutionExplorer_Build {
            get {
                return ResourceManager.GetString("SolutionExplorer_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project has changes since last build (Ctrl+Alt+F7 to build dirty).
        /// </summary>
        internal static string SolutionExplorer_BuildDirtyIndicator {
            get {
                return ResourceManager.GetString("SolutionExplorer_BuildDirtyIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clean.
        /// </summary>
        internal static string SolutionExplorer_Clean {
            get {
                return ResourceManager.GetString("SolutionExplorer_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear Default TBL.
        /// </summary>
        internal static string SolutionExplorer_ClearDefaultTbl {
            get {
                return ResourceManager.GetString("SolutionExplorer_ClearDefaultTbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close Solution.
        /// </summary>
        internal static string SolutionExplorer_CloseSolution {
            get {
                return ResourceManager.GetString("SolutionExplorer_CloseSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collapse All.
        /// </summary>
        internal static string SolutionExplorer_CollapseAllToolTip {
            get {
                return ResourceManager.GetString("SolutionExplorer_CollapseAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Convert to TBLX....
        /// </summary>
        internal static string SolutionExplorer_ConvertToTblx {
            get {
                return ResourceManager.GetString("SolutionExplorer_ConvertToTblx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy.
        /// </summary>
        internal static string SolutionExplorer_Copy {
            get {
                return ResourceManager.GetString("SolutionExplorer_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy Path.
        /// </summary>
        internal static string SolutionExplorer_CopyPath {
            get {
                return ResourceManager.GetString("SolutionExplorer_CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cut.
        /// </summary>
        internal static string SolutionExplorer_Cut {
            get {
                return ResourceManager.GetString("SolutionExplorer_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string SolutionExplorer_Delete {
            get {
                return ResourceManager.GetString("SolutionExplorer_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discard Changes.
        /// </summary>
        internal static string SolutionExplorer_DiscardChanges {
            get {
                return ResourceManager.GetString("SolutionExplorer_DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exclude from Project.
        /// </summary>
        internal static string SolutionExplorer_ExcludeFromProject {
            get {
                return ResourceManager.GetString("SolutionExplorer_ExcludeFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File is located outside the project directory.
        /// </summary>
        internal static string SolutionExplorer_ExternalFileIndicator {
            get {
                return ResourceManager.GetString("SolutionExplorer_ExternalFileIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modified externally — consider reloading.
        /// </summary>
        internal static string SolutionExplorer_ExternalModIndicator {
            get {
                return ResourceManager.GetString("SolutionExplorer_ExternalModIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        internal static string SolutionExplorer_FilterAll {
            get {
                return ResourceManager.GetString("SolutionExplorer_FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Binary.
        /// </summary>
        internal static string SolutionExplorer_FilterBinary {
            get {
                return ResourceManager.GetString("SolutionExplorer_FilterBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Images.
        /// </summary>
        internal static string SolutionExplorer_FilterImages {
            get {
                return ResourceManager.GetString("SolutionExplorer_FilterImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string SolutionExplorer_FilterLanguage {
            get {
                return ResourceManager.GetString("SolutionExplorer_FilterLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text.
        /// </summary>
        internal static string SolutionExplorer_FilterText {
            get {
                return ResourceManager.GetString("SolutionExplorer_FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter.
        /// </summary>
        internal static string SolutionExplorer_FilterToolTip {
            get {
                return ResourceManager.GetString("SolutionExplorer_FilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to Definition.
        /// </summary>
        internal static string SolutionExplorer_GoToDefinition {
            get {
                return ResourceManager.GetString("SolutionExplorer_GoToDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Built-in Format....
        /// </summary>
        internal static string SolutionExplorer_ImportFormat {
            get {
                return ResourceManager.GetString("SolutionExplorer_ImportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import into Project....
        /// </summary>
        internal static string SolutionExplorer_ImportIntoProject {
            get {
                return ResourceManager.GetString("SolutionExplorer_ImportIntoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import Built-in Syntax....
        /// </summary>
        internal static string SolutionExplorer_ImportSyntax {
            get {
                return ResourceManager.GetString("SolutionExplorer_ImportSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Include in Project.
        /// </summary>
        internal static string SolutionExplorer_IncludeInProject {
            get {
                return ResourceManager.GetString("SolutionExplorer_IncludeInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading….
        /// </summary>
        internal static string SolutionExplorer_LoadingIndicator {
            get {
                return ResourceManager.GetString("SolutionExplorer_LoadingIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage NuGet Packages….
        /// </summary>
        internal static string SolutionExplorer_ManageNugetPackages {
            get {
                return ResourceManager.GetString("SolutionExplorer_ManageNugetPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage NuGet Packages for Solution….
        /// </summary>
        internal static string SolutionExplorer_ManageNugetPackagesSolution {
            get {
                return ResourceManager.GetString("SolutionExplorer_ManageNugetPackagesSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Folder.
        /// </summary>
        internal static string SolutionExplorer_NewFolder {
            get {
                return ResourceManager.GetString("SolutionExplorer_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Solution Folder.
        /// </summary>
        internal static string SolutionExplorer_NewSolutionFolder {
            get {
                return ResourceManager.GetString("SolutionExplorer_NewSolutionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        internal static string SolutionExplorer_Open {
            get {
                return ResourceManager.GetString("SolutionExplorer_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open in File Explorer.
        /// </summary>
        internal static string SolutionExplorer_OpenInExplorer {
            get {
                return ResourceManager.GetString("SolutionExplorer_OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open With.
        /// </summary>
        internal static string SolutionExplorer_OpenWith {
            get {
                return ResourceManager.GetString("SolutionExplorer_OpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hex Editor.
        /// </summary>
        internal static string SolutionExplorer_OpenWithHexEditor {
            get {
                return ResourceManager.GetString("SolutionExplorer_OpenWithHexEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste.
        /// </summary>
        internal static string SolutionExplorer_Paste {
            get {
                return ResourceManager.GetString("SolutionExplorer_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Physical folder.
        /// </summary>
        internal static string SolutionExplorer_PhysicalFolderTooltip {
            get {
                return ResourceManager.GetString("SolutionExplorer_PhysicalFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Properties.
        /// </summary>
        internal static string SolutionExplorer_Properties {
            get {
                return ResourceManager.GetString("SolutionExplorer_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Properties folder.
        /// </summary>
        internal static string SolutionExplorer_PropertiesFolderTooltip {
            get {
                return ResourceManager.GetString("SolutionExplorer_PropertiesFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rebuild.
        /// </summary>
        internal static string SolutionExplorer_Rebuild {
            get {
                return ResourceManager.GetString("SolutionExplorer_Rebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        internal static string SolutionExplorer_RefreshToolTip {
            get {
                return ResourceManager.GetString("SolutionExplorer_RefreshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove from Project.
        /// </summary>
        internal static string SolutionExplorer_RemoveFromProject {
            get {
                return ResourceManager.GetString("SolutionExplorer_RemoveFromProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove Unused References….
        /// </summary>
        internal static string SolutionExplorer_RemoveUnusedReferences {
            get {
                return ResourceManager.GetString("SolutionExplorer_RemoveUnusedReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename.
        /// </summary>
        internal static string SolutionExplorer_Rename {
            get {
                return ResourceManager.GetString("SolutionExplorer_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save All.
        /// </summary>
        internal static string SolutionExplorer_SaveAll {
            get {
                return ResourceManager.GetString("SolutionExplorer_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Content Only.
        /// </summary>
        internal static string SolutionExplorer_SearchModeContentOnly {
            get {
                return ResourceManager.GetString("SolutionExplorer_SearchModeContentOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File Name.
        /// </summary>
        internal static string SolutionExplorer_SearchModeFileName {
            get {
                return ResourceManager.GetString("SolutionExplorer_SearchModeFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name + Content.
        /// </summary>
        internal static string SolutionExplorer_SearchModeNameContent {
            get {
                return ResourceManager.GetString("SolutionExplorer_SearchModeNameContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Regex (file name).
        /// </summary>
        internal static string SolutionExplorer_SearchModeRegex {
            get {
                return ResourceManager.GetString("SolutionExplorer_SearchModeRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search Solution Explorer (Ctrl+;).
        /// </summary>
        internal static string SolutionExplorer_SearchPlaceholder {
            get {
                return ResourceManager.GetString("SolutionExplorer_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set as Startup Project.
        /// </summary>
        internal static string SolutionExplorer_SetAsStartup {
            get {
                return ResourceManager.GetString("SolutionExplorer_SetAsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set as Default TBL.
        /// </summary>
        internal static string SolutionExplorer_SetDefaultTbl {
            get {
                return ResourceManager.GetString("SolutionExplorer_SetDefaultTbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show All Files.
        /// </summary>
        internal static string SolutionExplorer_ShowAllFilesToolTip {
            get {
                return ResourceManager.GetString("SolutionExplorer_ShowAllFilesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Solution folder (logical).
        /// </summary>
        internal static string SolutionExplorer_SolutionFolderTooltip {
            get {
                return ResourceManager.GetString("SolutionExplorer_SolutionFolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date Modified.
        /// </summary>
        internal static string SolutionExplorer_SortDateModified {
            get {
                return ResourceManager.GetString("SolutionExplorer_SortDateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string SolutionExplorer_SortName {
            get {
                return ResourceManager.GetString("SolutionExplorer_SortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string SolutionExplorer_SortNone {
            get {
                return ResourceManager.GetString("SolutionExplorer_SortNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size.
        /// </summary>
        internal static string SolutionExplorer_SortSize {
            get {
                return ResourceManager.GetString("SolutionExplorer_SortSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sort.
        /// </summary>
        internal static string SolutionExplorer_SortToolTip {
            get {
                return ResourceManager.GetString("SolutionExplorer_SortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string SolutionExplorer_SortType {
            get {
                return ResourceManager.GetString("SolutionExplorer_SortType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sync with Active Document.
        /// </summary>
        internal static string SolutionExplorer_SyncWithActiveDocToolTip {
            get {
                return ResourceManager.GetString("SolutionExplorer_SyncWithActiveDocToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unsaved modifications.
        /// </summary>
        internal static string SolutionExplorer_UnsavedModifications {
            get {
                return ResourceManager.GetString("SolutionExplorer_UnsavedModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy Path.
        /// </summary>
        internal static string WhfmtBrowser_CopyPath {
            get {
                return ResourceManager.GetString("WhfmtBrowser_CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string WhfmtBrowser_Delete {
            get {
                return ResourceManager.GetString("WhfmtBrowser_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duplicate Format….
        /// </summary>
        internal static string WhfmtBrowser_DuplicateFormat {
            get {
                return ResourceManager.GetString("WhfmtBrowser_DuplicateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit in Code Editor.
        /// </summary>
        internal static string WhfmtBrowser_EditInCodeEditor {
            get {
                return ResourceManager.GetString("WhfmtBrowser_EditInCodeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export to File….
        /// </summary>
        internal static string WhfmtBrowser_ExportToFile {
            get {
                return ResourceManager.GetString("WhfmtBrowser_ExportToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export to file….
        /// </summary>
        internal static string WhfmtBrowser_ExportToFileToolTip {
            get {
                return ResourceManager.GetString("WhfmtBrowser_ExportToFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One or more formats failed to load.
        /// </summary>
        internal static string WhfmtBrowser_LoadFailureIndicator {
            get {
                return ResourceManager.GetString("WhfmtBrowser_LoadFailureIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        internal static string WhfmtBrowser_Open {
            get {
                return ResourceManager.GetString("WhfmtBrowser_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open in Structure Editor.
        /// </summary>
        internal static string WhfmtBrowser_OpenInEditorToolTip {
            get {
                return ResourceManager.GetString("WhfmtBrowser_OpenInEditorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open as Read-Only.
        /// </summary>
        internal static string WhfmtBrowser_OpenReadOnly {
            get {
                return ResourceManager.GetString("WhfmtBrowser_OpenReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reveal in Explorer.
        /// </summary>
        internal static string WhfmtBrowser_RevealInExplorer {
            get {
                return ResourceManager.GetString("WhfmtBrowser_RevealInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View JSON.
        /// </summary>
        internal static string WhfmtBrowser_ViewJson {
            get {
                return ResourceManager.GetString("WhfmtBrowser_ViewJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View JSON.
        /// </summary>
        internal static string WhfmtBrowser_ViewJsonToolTip {
            get {
                return ResourceManager.GetString("WhfmtBrowser_ViewJsonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author.
        /// </summary>
        internal static string WhfmtCatalog_AuthorHeader {
            get {
                return ResourceManager.GetString("WhfmtCatalog_AuthorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Category.
        /// </summary>
        internal static string WhfmtCatalog_CategoryHeader {
            get {
                return ResourceManager.GetString("WhfmtCatalog_CategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Error.
        /// </summary>
        internal static string WhfmtCatalog_ErrorText {
            get {
                return ResourceManager.GetString("WhfmtCatalog_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export to File….
        /// </summary>
        internal static string WhfmtCatalog_ExportToFile {
            get {
                return ResourceManager.GetString("WhfmtCatalog_ExportToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions.
        /// </summary>
        internal static string WhfmtCatalog_ExtensionsHeader {
            get {
                return ResourceManager.GetString("WhfmtCatalog_ExtensionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detail Bottom.
        /// </summary>
        internal static string WhfmtCatalog_LayoutBottom {
            get {
                return ResourceManager.GetString("WhfmtCatalog_LayoutBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detail Left.
        /// </summary>
        internal static string WhfmtCatalog_LayoutLeft {
            get {
                return ResourceManager.GetString("WhfmtCatalog_LayoutLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detail Right.
        /// </summary>
        internal static string WhfmtCatalog_LayoutRight {
            get {
                return ResourceManager.GetString("WhfmtCatalog_LayoutRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detail panel position.
        /// </summary>
        internal static string WhfmtCatalog_LayoutTooltip {
            get {
                return ResourceManager.GetString("WhfmtCatalog_LayoutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detail Top.
        /// </summary>
        internal static string WhfmtCatalog_LayoutTop {
            get {
                return ResourceManager.GetString("WhfmtCatalog_LayoutTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string WhfmtCatalog_NameHeader {
            get {
                return ResourceManager.GetString("WhfmtCatalog_NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        internal static string WhfmtCatalog_Open {
            get {
                return ResourceManager.GetString("WhfmtCatalog_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open as Read-Only.
        /// </summary>
        internal static string WhfmtCatalog_OpenReadOnly {
            get {
                return ResourceManager.GetString("WhfmtCatalog_OpenReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quality.
        /// </summary>
        internal static string WhfmtCatalog_QualityHeader {
            get {
                return ResourceManager.GetString("WhfmtCatalog_QualityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reveal in Explorer.
        /// </summary>
        internal static string WhfmtCatalog_RevealInExplorer {
            get {
                return ResourceManager.GetString("WhfmtCatalog_RevealInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        internal static string WhfmtCatalog_SourceHeader {
            get {
                return ResourceManager.GetString("WhfmtCatalog_SourceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        internal static string WhfmtCatalog_VersionHeader {
            get {
                return ResourceManager.GetString("WhfmtCatalog_VersionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View JSON.
        /// </summary>
        internal static string WhfmtCatalog_ViewJson {
            get {
                return ResourceManager.GetString("WhfmtCatalog_ViewJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AI Hints.
        /// </summary>
        internal static string WhfmtDetail_AIHintsTab {
            get {
                return ResourceManager.GetString("WhfmtDetail_AIHintsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analysis Context.
        /// </summary>
        internal static string WhfmtDetail_AnalysisContextLabel {
            get {
                return ResourceManager.GetString("WhfmtDetail_AnalysisContextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assertions.
        /// </summary>
        internal static string WhfmtDetail_AssertionsTab {
            get {
                return ResourceManager.GetString("WhfmtDetail_AssertionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author.
        /// </summary>
        internal static string WhfmtDetail_AuthorLabel {
            get {
                return ResourceManager.GetString("WhfmtDetail_AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blocks.
        /// </summary>
        internal static string WhfmtDetail_BlocksLabel {
            get {
                return ResourceManager.GetString("WhfmtDetail_BlocksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Category.
        /// </summary>
        internal static string WhfmtDetail_CategoryLabel {
            get {
                return ResourceManager.GetString("WhfmtDetail_CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detection.
        /// </summary>
        internal static string WhfmtDetail_DetectionLabel {
            get {
                return ResourceManager.GetString("WhfmtDetail_DetectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diff.
        /// </summary>
        internal static string WhfmtDetail_DiffLabel {
            get {
                return ResourceManager.GetString("WhfmtDetail_DiffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editor.
        /// </summary>
        internal static string WhfmtDetail_EditorLabel {
            get {
                return ResourceManager.GetString("WhfmtDetail_EditorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a format to see details..
        /// </summary>
        internal static string WhfmtDetail_EmptyPlaceholder {
            get {
                return ResourceManager.GetString("WhfmtDetail_EmptyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exclude this format from catalog.
        /// </summary>
        internal static string WhfmtDetail_ExcludeFromCatalogToolTip {
            get {
                return ResourceManager.GetString("WhfmtDetail_ExcludeFromCatalogToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export to file….
        /// </summary>
        internal static string WhfmtDetail_ExportToFileToolTip {
            get {
                return ResourceManager.GetString("WhfmtDetail_ExportToFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions.
        /// </summary>
        internal static string WhfmtDetail_ExtensionsLabel {
            get {
                return ResourceManager.GetString("WhfmtDetail_ExtensionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format loaded successfully.
        /// </summary>
        internal static string WhfmtDetail_FormatLoadedSuccessfully {
            get {
                return ResourceManager.GetString("WhfmtDetail_FormatLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format failed to load.
        /// </summary>
        internal static string WhfmtDetail_FormatLoadFailed {
            get {
                return ResourceManager.GetString("WhfmtDetail_FormatLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JSON.
        /// </summary>
        internal static string WhfmtDetail_JsonTab {
            get {
                return ResourceManager.GetString("WhfmtDetail_JsonTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Known Vulnerabilities.
        /// </summary>
        internal static string WhfmtDetail_KnownVulnerabilitiesLabel {
            get {
                return ResourceManager.GetString("WhfmtDetail_KnownVulnerabilitiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load Error.
        /// </summary>
        internal static string WhfmtDetail_LoadErrorTitle {
            get {
                return ResourceManager.GetString("WhfmtDetail_LoadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open in Structure Editor.
        /// </summary>
        internal static string WhfmtDetail_OpenInEditorToolTip {
            get {
                return ResourceManager.GetString("WhfmtDetail_OpenInEditorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Overview.
        /// </summary>
        internal static string WhfmtDetail_OverviewTab {
            get {
                return ResourceManager.GetString("WhfmtDetail_OverviewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Platform.
        /// </summary>
        internal static string WhfmtDetail_PlatformLabel {
            get {
                return ResourceManager.GetString("WhfmtDetail_PlatformLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quality Score.
        /// </summary>
        internal static string WhfmtDetail_QualityScoreLabel {
            get {
                return ResourceManager.GetString("WhfmtDetail_QualityScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à References.
        /// </summary>
        internal static string WhfmtDetail_ReferencesTab {
            get {
                return ResourceManager.GetString("WhfmtDetail_ReferencesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retry loading this format.
        /// </summary>
        internal static string WhfmtDetail_RetryLoadToolTip {
            get {
                return ResourceManager.GetString("WhfmtDetail_RetryLoadToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specifications.
        /// </summary>
        internal static string WhfmtDetail_SpecificationsLabel {
            get {
                return ResourceManager.GetString("WhfmtDetail_SpecificationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        internal static string WhfmtDetail_StatusLabel {
            get {
                return ResourceManager.GetString("WhfmtDetail_StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        internal static string WhfmtDetail_VersionLabel {
            get {
                return ResourceManager.GetString("WhfmtDetail_VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View raw JSON.
        /// </summary>
        internal static string WhfmtDetail_ViewRawJsonToolTip {
            get {
                return ResourceManager.GetString("WhfmtDetail_ViewRawJsonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web Links.
        /// </summary>
        internal static string WhfmtDetail_WebLinksLabel {
            get {
                return ResourceManager.GetString("WhfmtDetail_WebLinksLabel", resourceCulture);
            }
        }

        internal static string Whfmt_AddFormatTitle {
            get { return ResourceManager.GetString("Whfmt_AddFormatTitle", resourceCulture); }
        }
        internal static string Whfmt_AddFormatFilter {
            get { return ResourceManager.GetString("Whfmt_AddFormatFilter", resourceCulture); }
        }
        internal static string Whfmt_AddFormatError {
            get { return ResourceManager.GetString("Whfmt_AddFormatError", resourceCulture); }
        }
        internal static string Whfmt_DeleteFormatTitle {
            get { return ResourceManager.GetString("Whfmt_DeleteFormatTitle", resourceCulture); }
        }
    }
}
